import { Topic } from '../../../types/content';

export const TOPIC_03: Topic = {
  "id": "cit220-unit-03",
  "slug": "03-identity-and-access-management",
  "topicNumber": "03",
  "title": "Identity & Access Management (IAM)",
  "subtitle": "The 4 A's, Multi-Factor Authentication, Identity Federation, IGA & PAM",
  "description": "Comprehensive guide to enterprise identity: the 4 A's, credential lifecycle, federation protocols (SAML/OAuth/OIDC), cloud identity governance, and Privileged Access Management (PAM).",
  "author": "Chin Ann Feliprada",
  "originalPath": "cit220_03_identity_and_access_management",
  "badge": "Identity & Access",
  "tags": ["IAM", "MFA", "The 4 A's", "SAML", "OAuth 2.0", "OIDC", "Single Sign-On", "Cloud IAM", "IGA", "PAM"],
  "totalSlides": 32,
  "sections": [
    {
      "id": "iam-foundations",
      "title": "Introduction to IAM & Securing Modern Enterprises",
      "eyebrow": "IAM Foundations",
      "summary": "Definition of IAM, business drivers, regulatory mandates, and risks of misconfigured access controls.",
      "slides": [
          {
            "id": "slide-1",
            "slideNumber": 1,
            "title": "Unit 3 - CIT 220 INFORMATION ASSURANCE AND SECURITY 2",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Introduction to IAM & Securing Modern Enterprises",
            "lead": "Unit 3 - CIT 220 INFORMATION ASSURANCE AND SECURITY 2 Identity and Access Management (IAM)",
            "byline": "Prof. Chin Ann Feliprada • WVSU CICT Main Campus, Iloilo City",
            "isTitleSlide": true,
            "isSectionDivider": false,
            "rawHtml": "<div class=\"intro-author-card\"><div class=\"institution-badge\"><span>West Visayas State University • CICT Main Campus, Iloilo City</span></div><h2>Identity &amp; Access Management (IAM)</h2><p class=\"intro-tagline\">CIT 220 Information Assurance and Security 2 • Unit 03</p><p class=\"mt-4 text-xs text-slate-500 dark:text-slate-400\">Course Instructor: Prof. Chin Ann Feliprada</p></div>",
            "cleanText": "Unit 3 - CIT 220 INFORMATION ASSURANCE AND SECURITY 2 Identity and Access Management (IAM)",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-2",
            "slideNumber": 2,
            "title": "Table of Contents",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Introduction to IAM & Securing Modern Enterprises",
            "lead": "Table of Contents - Introduction - The Core Components of IAM",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Table of Contents</h3><p class=\"lead-statement\">Trust access management</p><div class=\"info-card mt-3\"><p>Unit 3 -  CIT 220</p></div><ul class=\"compact mt-3\"><li>Introduction</li><li>The Core Components of IAM</li><li>Importance of IAM</li><li>The IAM Lifecycle</li><li>IAM as the Foundation of Zero</li><li>Advanced authentication methods</li><li>Access control models</li><li>Identity governance and privileged</li></ul>",
            "cleanText": "Table of Contents - Introduction - The Core Components of IAM - Importance of IAM - The IAM Lifecycle - IAM as the Foundation of Zero Trust - Advanced authentication methods - Access control models - Identity governance and privileged access management Unit 3 -  CIT 220",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-3",
            "slideNumber": 3,
            "title": "What Is Identity And Access",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Introduction to IAM & Securing Modern Enterprises",
            "lead": "What Is Identity And Access Management (IAM)? Unit 3 - CIT 220",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>What Is Identity And Access</h3><p class=\"lead-statement\">Management (IAM)? Unit 3 - CIT 220</p><div class=\"info-card mt-3\"><p>procedures, and technologies adopted by a business for efficient management of electronics and digital personas or identities to prevent authorized access. data, in order to safeguard it. Based upon the organizational needs and abilities, IAM can be made up of many layers. factor authentication (MFA) to let you do privilege verification.</p></div><ul class=\"compact mt-3\"><li>IAM is a framework that manages key policy terms, standards,</li><li>Using IAM, IT officers can control how users access business-critical</li><li>For instance, it could feature single sign-on systems, ask for 2 or multi-</li></ul>",
            "cleanText": "What Is Identity And Access Management (IAM)? Unit 3 - CIT 220 - IAM is a framework that manages key policy terms, standards, procedures, and technologies adopted by a business for efficient management of electronics and digital personas or identities to prevent authorized access. - Using IAM, IT officers can control how users access business-critical data, in order to safeguard it. Based upon the organizational needs and abilities, IAM can be made up of many layers. - For instance, it could feature single sign-on systems, ask for 2 or multi- factor authentication (MFA) to let you do privilege verification.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-4",
            "slideNumber": 4,
            "title": "Unit 3 - CIT 220",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Introduction to IAM & Securing Modern Enterprises",
            "lead": "Unit 3 - CIT 220 Why IAM Is Necessary? 1.Unauthorized Access- Hackers rejoice every time they find a system",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Unit 3 - CIT 220</h3><p class=\"lead-statement\">Why IAM Is Necessary? 1.Unauthorized Access- Hackers rejoice every time they find a system</p><div class=\"info-card mt-3\"><p>with what they consider a pathetic level of access control. When an organization has a weak IAM system, hackers can quickly take advantage of the system&#x27;s blind spots to get into the systems with restricted access to the information. 1.Human Error- Even the most diligent and well-intentioned employees can make mistakes. This is very dangerous because one can easily stumble across secured documents or misuse permissions in a way that costs a lot. Without IAM, organizations leave themselves vulnerable to: Imagine a company where employees share login credentials for various applications, and no one tracks who accesses what.</p></div>",
            "cleanText": "Unit 3 - CIT 220 Why IAM Is Necessary? 1.Unauthorized Access- Hackers rejoice every time they find a system with what they consider a pathetic level of access control. When an organization has a weak IAM system, hackers can quickly take advantage of the system's blind spots to get into the systems with restricted access to the information. 1.Human Error- Even the most diligent and well-intentioned employees can make mistakes. This is very dangerous because one can easily stumble across secured documents or misuse permissions in a way that costs a lot. Without IAM, organizations leave themselves vulnerable to: Imagine a company where employees share login credentials for various applications, and no one tracks who accesses what.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-5",
            "slideNumber": 5,
            "title": "Unit 3 - CIT 220",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Introduction to IAM & Securing Modern Enterprises",
            "lead": "Unit 3 - CIT 220 Why IAM Is Necessary? 3. Compliance Risks- Data protection laws such as the GDPR, HIPAA, and PCI",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Unit 3 - CIT 220</h3><p class=\"lead-statement\">Why IAM Is Necessary? 3. Compliance Risks- Data protection laws such as the GDPR, HIPAA, and PCI</p><div class=\"info-card mt-3\"><p>DSS demand that companies maintain a strong handle on user access. Non- compliance leads to hefty fines and tarnishing of the companies&#x27; reputations. 4. Inefficiency- As an organization grows, it is almost impossible to manage user access and their permissions manually. IAM gets rid of these issues because it can autonomously manage and enforce security access attributes, minimize the involvement of human input which can cause mistakes, and grant the correct level of access only to people who require it. Without IAM, organizations leave themselves vulnerable to:</p></div>",
            "cleanText": "Unit 3 - CIT 220 Why IAM Is Necessary? 3. Compliance Risks- Data protection laws such as the GDPR, HIPAA, and PCI DSS demand that companies maintain a strong handle on user access. Non- compliance leads to hefty fines and tarnishing of the companies' reputations. 4. Inefficiency- As an organization grows, it is almost impossible to manage user access and their permissions manually. IAM gets rid of these issues because it can autonomously manage and enforce security access attributes, minimize the involvement of human input which can cause mistakes, and grant the correct level of access only to people who require it. Without IAM, organizations leave themselves vulnerable to:",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-6",
            "slideNumber": 6,
            "title": "Unit 3 - CIT 220",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Introduction to IAM & Securing Modern Enterprises",
            "lead": "Unit 3 - CIT 220 Securing the Modern Enterprise Benefits of Identity and Access Management",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Unit 3 - CIT 220</h3><p class=\"lead-statement\">Securing the Modern Enterprise Benefits of Identity and Access Management</p><div class=\"info-card mt-3\"><p>Key Benefits: breaches. reducing manual work for IT. and legal requirements (e.g., GDPR, HIPAA). the sense that the tasks that require a lot of work from IT departments are eliminated leaving them with more work to do. always can maintain high levels of security without compromising growth.</p></div><ul class=\"compact mt-3\"><li>Enhanced Security: Prevents unauthorized access and mitigates data</li><li>Improved Efficiency: Automates user provisioning and deprovisioning,</li><li>Regulatory Compliance: Helps organizations meet industry standards</li><li>Cost Savings- Automation in accessing management is also beneficial in</li><li>Scalability- In organizations, as they expand, IAM becomes elastic and</li></ul>",
            "cleanText": "Unit 3 - CIT 220 Securing the Modern Enterprise Benefits of Identity and Access Management Key Benefits: - Enhanced Security: Prevents unauthorized access and mitigates data breaches. - Improved Efficiency: Automates user provisioning and deprovisioning, reducing manual work for IT. - Regulatory Compliance: Helps organizations meet industry standards and legal requirements (e.g., GDPR, HIPAA). - Cost Savings- Automation in accessing management is also beneficial in the sense that the tasks that require a lot of work from IT departments are eliminated leaving them with more work to do. - Scalability- In organizations, as they expand, IAM becomes elastic and always can maintain high levels of security without compromising growth.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-7",
            "slideNumber": 7,
            "title": "What Are The Risks of",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Introduction to IAM & Securing Modern Enterprises",
            "lead": "What Are The Risks of Implementing IAM? Unit 3 - CIT 220",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>What Are The Risks of</h3><p class=\"lead-statement\">Implementing IAM? Unit 3 - CIT 220</p><div class=\"info-card mt-3\"><p>‍1. IAM configuration oversights There are three crucial IAM oversights that should not be neglected for sure. They can be stated as: 2. Problems with Biometrics It&#x27;s crucial to ensure that the biometric database is secure and yet easily accessible. It&#x27;s hard to do effective disposal of the biometrics data that is no longer needed.</p></div><ul class=\"compact mt-3\"><li>Poor process automation</li><li>Insufficient provisioning</li><li>Inadequate reviews</li></ul>",
            "cleanText": "What Are The Risks of Implementing IAM? Unit 3 - CIT 220 ‍1. IAM configuration oversights There are three crucial IAM oversights that should not be neglected for sure. They can be stated as: - Poor process automation - Insufficient provisioning - Inadequate reviews 2. Problems with Biometrics It's crucial to ensure that the biometric database is secure and yet easily accessible. It's hard to do effective disposal of the biometrics data that is no longer needed.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-8",
            "slideNumber": 8,
            "title": "What Are The Risks of",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Introduction to IAM & Securing Modern Enterprises",
            "lead": "What Are The Risks of Implementing IAM? Unit 3 - CIT 220",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>What Are The Risks of</h3><p class=\"lead-statement\">Implementing IAM? Unit 3 - CIT 220</p><div class=\"info-card mt-3\"><p>3. Adhering to the Security Policy Ensure security policy implementation. Proper security practices are implemented across the IAM implementation, it&#x27;s important to pay attention to the principle of least privilege. 4. Issues with Cloud In provisioning and deprovisioning user accounts in cloud, it should be handled with the utmost diligence, as there are tons of inactive vulnerabilities assigned to user accounts.</p></div>",
            "cleanText": "What Are The Risks of Implementing IAM? Unit 3 - CIT 220 3. Adhering to the Security Policy Ensure security policy implementation. Proper security practices are implemented across the IAM implementation, it's important to pay attention to the principle of least privilege. 4. Issues with Cloud In provisioning and deprovisioning user accounts in cloud, it should be handled with the utmost diligence, as there are tons of inactive vulnerabilities assigned to user accounts.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-9",
            "slideNumber": 9,
            "title": "What Are The Risks of",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Introduction to IAM & Securing Modern Enterprises",
            "lead": "What Are The Risks of Implementing IAM? Unit 3 - CIT 220",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>What Are The Risks of</h3><p class=\"lead-statement\">Implementing IAM? Unit 3 - CIT 220</p><div class=\"info-card mt-3\"><p>5. Old-school Systems Implementation of multi-factor authentication seems a piece of cake in cloud-based IAM systems as compared to the on-premise system. 6. Change Management Keeping a track of access audits is tough as access granted to an employee changes with the change of job roles.</p></div>",
            "cleanText": "What Are The Risks of Implementing IAM? Unit 3 - CIT 220 5. Old-school Systems Implementation of multi-factor authentication seems a piece of cake in cloud-based IAM systems as compared to the on-premise system. 6. Change Management Keeping a track of access audits is tough as access granted to an employee changes with the change of job roles.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "the-four-as",
      "title": "The Core Components: The 4 A's of IAM",
      "eyebrow": "Core Components",
      "summary": "Administration, Authentication, Authorization, and Audit (Accounting) with multi-factor and biometric modalities.",
      "slides": [
          {
            "id": "slide-10",
            "slideNumber": 10,
            "title": "The Core Component  of",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "The Core Components: The 4 A's of IAM",
            "lead": "The Core Component  of IAM‍\"4A's\"",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>The Core Component  of</h3><p class=\"lead-statement\">IAM‍&quot;4A&#x27;s&quot;</p>",
            "cleanText": "The Core Component  of IAM‍\"4A's\"",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-11",
            "slideNumber": 11,
            "title": "This involves managing user identities and their",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "The Core Components: The 4 A's of IAM",
            "lead": "This involves managing user identities and their associated permissions, including the creation, modification, and deletion of user accounts and roles.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>This involves managing user identities and their</h3><p class=\"lead-statement\">associated permissions, including the creation, modification, and deletion of user accounts and roles.</p><div class=\"info-card mt-3\"><p>The Core Components of  IAM Administration Unit 3 -  CIT 220 Authorization determines what actions they are allowed to perform and what resources they can access, based on their assigned roles and permissions. Grants or denies access to specific resources based on a user&#x27;s verified identity. What are you allowed to do? Privilege. Authorization</p></div><ul class=\"compact mt-3\"><li>Examples: Role-Based Access Control (RBAC), Least</li></ul>",
            "cleanText": "This involves managing user identities and their associated permissions, including the creation, modification, and deletion of user accounts and roles. The Core Components of  IAM Administration Unit 3 -  CIT 220 Authorization determines what actions they are allowed to perform and what resources they can access, based on their assigned roles and permissions. Grants or denies access to specific resources based on a user's verified identity. What are you allowed to do? - Examples: Role-Based Access Control (RBAC), Least Privilege. Authorization",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-12",
            "slideNumber": 12,
            "title": "This process verifies that a user is who they claim to be,",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "The Core Components: The 4 A's of IAM",
            "lead": "This process verifies that a user is who they claim to be, typically through credentials like passwords, biometrics, or multi-factor authentication.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>This process verifies that a user is who they claim to be,</h3><p class=\"lead-statement\">typically through credentials like passwords, biometrics, or multi-factor authentication.</p><div class=\"info-card mt-3\"><p>authentication (MFA). The Core Components of  IAM Authentication Unit 3 -  CIT 220 tracks user activity, logging events to provide visibility into who accessed what and when, which is essential for security and compliance. behavior and ensure compliance. Auditing</p></div><ul class=\"compact mt-3\"><li>Examples: Passwords, biometrics, multi-factor</li><li>What did you do?</li><li>Tracks and logs user activity to monitor for suspicious</li><li>Examples: Activity logs, access reviews.</li></ul>",
            "cleanText": "This process verifies that a user is who they claim to be, typically through credentials like passwords, biometrics, or multi-factor authentication. - Examples: Passwords, biometrics, multi-factor authentication (MFA). The Core Components of  IAM Authentication Unit 3 -  CIT 220 tracks user activity, logging events to provide visibility into who accessed what and when, which is essential for security and compliance. - What did you do? - Tracks and logs user activity to monitor for suspicious behavior and ensure compliance. - Examples: Activity logs, access reviews. Auditing",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-13",
            "slideNumber": 13,
            "title": "Types of User Authentication",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "The Core Components: The 4 A's of IAM",
            "lead": "Types of User Authentication Unit 3 -  CIT 220 1. Multi-factor Authentication",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Types of User Authentication</h3><p class=\"lead-statement\">Unit 3 -  CIT 220 1. Multi-factor Authentication</p><div class=\"info-card mt-3\"><p>The Procedure involves combining two or more verification procedures and login credentials together. So, when a user requests access to a particular tool and software, he will have to enter a code after login into a resource. 2. Unique Passwords This method is mostly adopted by users for secured access. It involves using safe and tough passwords for protecting the resource. Usually, a unique combination of digits, characters, and special characters. 3. Pre-shared Key (PSK) PSK or Pre-shared Key is a kind of digital authentication wherein a unique password is shared only with authorized personals. The most common example of PSK is sharing Wi-Fi passwords with the team. It is not as safe as individual passwords.</p></div>",
            "cleanText": "Types of User Authentication Unit 3 -  CIT 220 1. Multi-factor Authentication The Procedure involves combining two or more verification procedures and login credentials together. So, when a user requests access to a particular tool and software, he will have to enter a code after login into a resource. 2. Unique Passwords This method is mostly adopted by users for secured access. It involves using safe and tough passwords for protecting the resource. Usually, a unique combination of digits, characters, and special characters. 3. Pre-shared Key (PSK) PSK or Pre-shared Key is a kind of digital authentication wherein a unique password is shared only with authorized personals. The most common example of PSK is sharing Wi-Fi passwords with the team. It is not as safe as individual passwords.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-14",
            "slideNumber": 14,
            "title": "Types of User Authentication",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "The Core Components: The 4 A's of IAM",
            "lead": "Types of User Authentication Unit 3 -  CIT 220 4. Behavioral Authentication",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Types of User Authentication</h3><p class=\"lead-statement\">Unit 3 -  CIT 220 4. Behavioral Authentication</p><div class=\"info-card mt-3\"><p>It involves AI to figure out that the user trying to gain access to a particular resource is a human or machine. The process checks if the behavior is appropriate or not. For this, it analyzes granular characteristics, such as mouse-use tracking. Once the IAM figures out that something is not right, the system gets closed automatically. 5. Biometrics Biometrics components used are the face and finger authentication, iris and voice recognition, and even DNA matching. It is considered a highly reliable and dependable method for identity verification, but there is a catch here.</p></div>",
            "cleanText": "Types of User Authentication Unit 3 -  CIT 220 4. Behavioral Authentication It involves AI to figure out that the user trying to gain access to a particular resource is a human or machine. The process checks if the behavior is appropriate or not. For this, it analyzes granular characteristics, such as mouse-use tracking. Once the IAM figures out that something is not right, the system gets closed automatically. 5. Biometrics Biometrics components used are the face and finger authentication, iris and voice recognition, and even DNA matching. It is considered a highly reliable and dependable method for identity verification, but there is a catch here.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-15",
            "slideNumber": 15,
            "title": "Unit 3 - CIT 220",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "The Core Components: The 4 A's of IAM",
            "lead": "Unit 3 - CIT 220",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Unit 3 - CIT 220</h3>",
            "cleanText": "Unit 3 - CIT 220",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "iam-lifecycle-technologies",
      "title": "Identity Lifecycle, SAML, OAuth & Federation",
      "eyebrow": "Federation & Protocols",
      "summary": "Onboarding to deprovisioning, Single Sign-On (SSO), SAML assertions, OAuth 2.0 delegated tokens, and OpenID Connect.",
      "slides": [
          {
            "id": "slide-16",
            "slideNumber": 16,
            "title": "KEY FUNCTIONS OF IAM",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Identity Lifecycle, SAML, OAuth & Federation",
            "lead": "KEY FUNCTIONS OF IAM Unit 3 - CIT 220",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>KEY FUNCTIONS OF IAM</h3><p class=\"lead-statement\">Unit 3 - CIT 220</p>",
            "cleanText": "KEY FUNCTIONS OF IAM Unit 3 - CIT 220",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-17",
            "slideNumber": 17,
            "title": "IDENTITY MANAGEMENT LIFE CYCLE",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Identity Lifecycle, SAML, OAuth & Federation",
            "lead": "IDENTITY MANAGEMENT LIFE CYCLE Unit 3 - CIT 220",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>IDENTITY MANAGEMENT LIFE CYCLE</h3><p class=\"lead-statement\">Unit 3 - CIT 220</p>",
            "cleanText": "IDENTITY MANAGEMENT LIFE CYCLE Unit 3 - CIT 220",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-18",
            "slideNumber": 18,
            "title": "involves streamlining the",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Identity Lifecycle, SAML, OAuth & Federation",
            "lead": "involves streamlining the activities of enrollment or de-enrollment involving",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>involves streamlining the</h3><p class=\"lead-statement\">activities of enrollment or de-enrollment involving</p><div class=\"info-card mt-3\"><p>users with various systems. User Provisioning and De-provisioning Single Sign-On (SSO) Allows a user to log in with a single set of credentials to access multiple, independent systems. KEY FUNCTIONS OF IAM Unit 3 - CIT 220 Multi-Factor Authentication (MFA) Extra layers of security are added to the identification process so that even if passwords have been hacked it is still safe.</p></div>",
            "cleanText": "involves streamlining the activities of enrollment or de-enrollment involving users with various systems. User Provisioning and De-provisioning Single Sign-On (SSO) Allows a user to log in with a single set of credentials to access multiple, independent systems. KEY FUNCTIONS OF IAM Unit 3 - CIT 220 Multi-Factor Authentication (MFA) Extra layers of security are added to the identification process so that even if passwords have been hacked it is still safe.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-19",
            "slideNumber": 19,
            "title": "-  Extra layers of security",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Identity Lifecycle, SAML, OAuth & Federation",
            "lead": "-  Extra layers of security are added to the identification process so",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>-  Extra layers of security</h3><p class=\"lead-statement\">are added to the identification process so</p><div class=\"info-card mt-3\"><p>that even if passwords have been hacked it is still safe. Multi-Factor Authentication (MFA) Principle Access Management systems and data to the minimum privileges required for a user&#x27;s job function, a concept known as the principle of least privilege. Monitoring and Reporting - IAM constantly monitors usage trends, reporting and raising alarms in the case of unusual usage, and creates records of usage for compliance. Unit 3 - CIT 220 KEY FUNCTIONS OF IAM</p></div><ul class=\"compact mt-3\"><li></li><li>Limits access to critical</li></ul>",
            "cleanText": "-  Extra layers of security are added to the identification process so that even if passwords have been hacked it is still safe. Multi-Factor Authentication (MFA) - Principle Access Management - Limits access to critical systems and data to the minimum privileges required for a user's job function, a concept known as the principle of least privilege. Monitoring and Reporting - IAM constantly monitors usage trends, reporting and raising alarms in the case of unusual usage, and creates records of usage for compliance. Unit 3 - CIT 220 KEY FUNCTIONS OF IAM",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-20",
            "slideNumber": 20,
            "title": "Identity And Access",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Identity Lifecycle, SAML, OAuth & Federation",
            "lead": "Identity And Access Management Tools The key tools used by an IAM system are a security policy tool, password",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Identity And Access</h3><p class=\"lead-statement\">Management Tools The key tools used by an IAM system are a security policy tool, password</p><div class=\"info-card mt-3\"><p>management applications, reporting &amp; monitoring tools, provisioning software, and identity repositories. Popular IAM tools include Microsoft Azure AD, Okta, and SailPoint. These tools provide features like SSO, MFA, and access monitoring. Other than this, MFA is another crucial tool assisting IAM. It deals with 2 or more access control related factors. Single sign-on (SSO) is also a widely used IAM tool that allows users to sign in only once and provide a centralized platform to manage all sorts of access. Unit 3 - CIT 220</p></div>",
            "cleanText": "Identity And Access Management Tools The key tools used by an IAM system are a security policy tool, password management applications, reporting & monitoring tools, provisioning software, and identity repositories. Popular IAM tools include Microsoft Azure AD, Okta, and SailPoint. These tools provide features like SSO, MFA, and access monitoring. Other than this, MFA is another crucial tool assisting IAM. It deals with 2 or more access control related factors. Single sign-on (SSO) is also a widely used IAM tool that allows users to sign in only once and provide a centralized platform to manage all sorts of access. Unit 3 - CIT 220",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-21",
            "slideNumber": 21,
            "title": "IAM Technologies",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Identity Lifecycle, SAML, OAuth & Federation",
            "lead": "IAM Technologies 1.SAML (Security Access Markup",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>IAM Technologies</h3><p class=\"lead-statement\">1.SAML (Security Access Markup</p><div class=\"info-card mt-3\"><p>Language) 2. OpenID Connect (OIDC) 3. System for Cross- domain Identity Management (SCIM) It is an open standard in which an information exchange happens between an identity provider and a service/application. IAM systems often make use of it to ensure a secure login to an application OIDC is a relatively new standard allowing end-users to gain instant access to the resource from an identity provider and it is built using the OAuth 2.0 This technology is called up for help to do quick and effective identity information exchange between two different systems and is used to keep every piece of information updated during the deployment of new users. Unit 3 - CIT 220 The IAM technologies are bound to adhere to certain standards to make sure everything has complied. Here are key technologies and standards adopted for IAM framework:</p></div>",
            "cleanText": "IAM Technologies 1.SAML (Security Access Markup Language) 2. OpenID Connect (OIDC) 3. System for Cross- domain Identity Management (SCIM) It is an open standard in which an information exchange happens between an identity provider and a service/application. IAM systems often make use of it to ensure a secure login to an application OIDC is a relatively new standard allowing end-users to gain instant access to the resource from an identity provider and it is built using the OAuth 2.0 This technology is called up for help to do quick and effective identity information exchange between two different systems and is used to keep every piece of information updated during the deployment of new users. Unit 3 - CIT 220 The IAM technologies are bound to adhere to certain standards to make sure everything has complied. Here are key technologies and standards adopted for IAM framework:",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-22",
            "slideNumber": 22,
            "title": "- It's crucial to decide who is going to lead the team in strategy",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Identity Lifecycle, SAML, OAuth & Federation",
            "lead": "- It's crucial to decide who is going to lead the team in strategy development, policy enforcement, and their enactment. - IAM implementation is going to impact every department and team",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>- It&#x27;s crucial to decide who is going to lead the team in strategy</h3><p class=\"lead-statement\">development, policy enforcement, and their enactment. player of an organization. So, it should be done as per everyone&#x27;s</p><div class=\"info-card mt-3\"><p>needs and as per the corporate operational. knowledge of the IAM design pattern for careful identity management. enforcement and policy decisions. They both are different and deal with different IAM aspects. Consideration in Implementing IAM In The Enterprise: Unit 3 - CIT 220</p></div><ul class=\"compact mt-3\"><li>IAM implementation is going to impact every department and team</li><li>On-premise solutions should be capable of having an in-depth</li><li>In implementing IAM, shows the distinction between policy</li></ul>",
            "cleanText": "- It's crucial to decide who is going to lead the team in strategy development, policy enforcement, and their enactment. - IAM implementation is going to impact every department and team player of an organization. So, it should be done as per everyone's needs and as per the corporate operational. - On-premise solutions should be capable of having an in-depth knowledge of the IAM design pattern for careful identity management. - In implementing IAM, shows the distinction between policy enforcement and policy decisions. They both are different and deal with different IAM aspects. Consideration in Implementing IAM In The Enterprise: Unit 3 - CIT 220",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "cloud-iam-zero-trust",
      "title": "Cloud IAM & The Identity Foundation of Zero Trust",
      "eyebrow": "Cloud & Zero Trust",
      "summary": "Managing access in AWS/Azure/GCP, SaaS application governance, and identity as the primary Zero Trust perimeter.",
      "slides": [
          {
            "id": "slide-23",
            "slideNumber": 23,
            "title": "Cloud Platforms:",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Cloud IAM & The Identity Foundation of Zero Trust",
            "lead": "Cloud Platforms: - IAM is fundamental to managing user access to cloud resources and services on platforms such as AWS, Azure,",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Cloud Platforms:</h3><p class=\"lead-statement\">resources and services on platforms such as AWS, Azure, and Google Cloud.</p><div class=\"info-card mt-3\"><p>Internal Business Applications: WordPress that employees use daily can be integrated with IAM for user access and permission management. Applications where IAM is used Unit 3 - CIT 220</p></div><ul class=\"compact mt-3\"><li>IAM is fundamental to managing user access to cloud</li><li>Workforce Productivity Apps: Applications like Slack or</li></ul>",
            "cleanText": "Cloud Platforms: - IAM is fundamental to managing user access to cloud resources and services on platforms such as AWS, Azure, and Google Cloud. Internal Business Applications: - Workforce Productivity Apps: Applications like Slack or WordPress that employees use daily can be integrated with IAM for user access and permission management. Applications where IAM is used Unit 3 - CIT 220",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-24",
            "slideNumber": 24,
            "title": "- Third-Party and External Applications:",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Cloud IAM & The Identity Foundation of Zero Trust",
            "lead": "- Third-Party and External Applications: ⚬ SaaS Applications: Applications accessed by employees from external providers, such as Google Workspace, can",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>- Third-Party and External Applications:</h3><p class=\"lead-statement\">⚬ SaaS Applications: Applications accessed by employees from external providers, such as Google Workspace, can</p><div class=\"info-card mt-3\"><p>integrate with IAM for unified access. ⚬ Directory Services: On-premises directory services like Active Directory or OpenLDAP can be considered a form of IAM, managing users and permissions within a local IT environment. Applications where IAM is used Unit 3 - CIT 220</p></div><ul class=\"compact mt-3\"><li>Legacy and On-Premises Systems:</li></ul>",
            "cleanText": "- Third-Party and External Applications: ⚬ SaaS Applications: Applications accessed by employees from external providers, such as Google Workspace, can integrate with IAM for unified access. - Legacy and On-Premises Systems: ⚬ Directory Services: On-premises directory services like Active Directory or OpenLDAP can be considered a form of IAM, managing users and permissions within a local IT environment. Applications where IAM is used Unit 3 - CIT 220",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-25",
            "slideNumber": 25,
            "title": "IAM as the Foundation of",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Cloud IAM & The Identity Foundation of Zero Trust",
            "lead": "IAM as the Foundation of Zero Trust Identity and Access Management (IAM) forms the bedrock of a Zero",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>IAM as the Foundation of</h3><p class=\"lead-statement\">Zero Trust Identity and Access Management (IAM) forms the bedrock of a Zero</p><div class=\"info-card mt-3\"><p>Trust architecture because it manages digital identities and rigorously verifies access requests, embodying the &quot;never trust, always verify&quot; principle of Zero Trust by ensuring only authorized users and devices gain access to resources. Unit 3 - CIT 220</p></div>",
            "cleanText": "IAM as the Foundation of Zero Trust Identity and Access Management (IAM) forms the bedrock of a Zero Trust architecture because it manages digital identities and rigorously verifies access requests, embodying the \"never trust, always verify\" principle of Zero Trust by ensuring only authorized users and devices gain access to resources. Unit 3 - CIT 220",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-26",
            "slideNumber": 26,
            "title": "IAM as the Foundation of",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Cloud IAM & The Identity Foundation of Zero Trust",
            "lead": "IAM as the Foundation of Zero Trust IAM enables granular control through",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>IAM as the Foundation of</h3><p class=\"lead-statement\">Zero Trust IAM enables granular control through</p><div class=\"info-card mt-3\"><p>limiting risk by granting least privilege, simplifying compliance, and securing modern, distributed work environments. Unit 3 - CIT 220</p></div><ul class=\"compact mt-3\"><li>multi-factor authentication (MFA),</li><li>role-based access control (RBAC), and;</li><li>privileged access management (PAM)</li></ul>",
            "cleanText": "IAM as the Foundation of Zero Trust IAM enables granular control through - multi-factor authentication (MFA), - role-based access control (RBAC), and; - privileged access management (PAM) limiting risk by granting least privilege, simplifying compliance, and securing modern, distributed work environments. Unit 3 - CIT 220",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-27",
            "slideNumber": 27,
            "title": "These are frameworks that define rules for who can access specific resources and",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Cloud IAM & The Identity Foundation of Zero Trust",
            "lead": "These are frameworks that define rules for who can access specific resources and when. Common models include:",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>These are frameworks that define rules for who can access specific resources and</h3><p class=\"lead-statement\">when. Common models include:</p><div class=\"info-card mt-3\"><p> Discretionary Access Control (DAC), where resource owners manage permissions;  Role-Based Access Control (RBAC), which assigns access based on job functions;  Mandatory Access Control (MAC), a highly restrictive model where a central authority controls all access based on security labels and;  Attribute-Based Access Control (ABAC), which grants access based on various user, resource, and environmental attributes. The choice of model depends on an organization&#x27;s security needs, resource type, and operational infrastructure. Access Control Models</p></div>",
            "cleanText": "These are frameworks that define rules for who can access specific resources and when. Common models include:  Discretionary Access Control (DAC), where resource owners manage permissions;  Role-Based Access Control (RBAC), which assigns access based on job functions;  Mandatory Access Control (MAC), a highly restrictive model where a central authority controls all access based on security labels and;  Attribute-Based Access Control (ABAC), which grants access based on various user, resource, and environmental attributes. The choice of model depends on an organization's security needs, resource type, and operational infrastructure. Access Control Models",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "iga-pam-governance",
      "title": "Identity Governance (IGA) & Privileged Access (PAM)",
      "eyebrow": "Governance & PAM",
      "summary": "Access certifications, separation of duties (SoD), vaulting root/admin credentials, and session auditing.",
      "slides": [
          {
            "id": "slide-28",
            "slideNumber": 28,
            "title": "Defining Identity governance and privileged access",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Identity Governance (IGA) & Privileged Access (PAM)",
            "lead": "Defining Identity governance and privileged access management Focus",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Defining Identity governance and privileged access</h3><p class=\"lead-statement\">management Focus</p><div class=\"info-card mt-3\"><p>Purpose Key Features Manages the entire identity lifecycle and access controls for all users, including the granting, modifying, and revoking of access. Ensures that users have the proper level of access for their role, helps maintain compliance with regulations, and reinforces the principle of least privilege for regular users. Identity lifecycle management, access requests and provisioning, access certification and attestation, and role-based access controls. Unit 3 - CIT 220 Identity Governance and Administration (IGA)</p></div>",
            "cleanText": "Defining Identity governance and privileged access management Focus Purpose Key Features Manages the entire identity lifecycle and access controls for all users, including the granting, modifying, and revoking of access. Ensures that users have the proper level of access for their role, helps maintain compliance with regulations, and reinforces the principle of least privilege for regular users. Identity lifecycle management, access requests and provisioning, access certification and attestation, and role-based access controls. Unit 3 - CIT 220 Identity Governance and Administration (IGA)",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-29",
            "slideNumber": 29,
            "title": "Defining Identity governance and privileged access",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Identity Governance (IGA) & Privileged Access (PAM)",
            "lead": "Defining Identity governance and privileged access management Focus",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Defining Identity governance and privileged access</h3><p class=\"lead-statement\">management Focus</p><div class=\"info-card mt-3\"><p>Purpose Key Features Securing and managing accounts that have elevated privileges, such as administrative accounts. Protects against threats, like unauthorized changes to critical systems or the exfiltration of sensitive data, by closely monitoring and controlling these powerful accounts. Secure credential vaulting, session recording and monitoring, just-in-time (JIT) access, and privileged access threat analytics. Unit 3 - CIT 220 Privileged Access Management (PAM)</p></div>",
            "cleanText": "Defining Identity governance and privileged access management Focus Purpose Key Features Securing and managing accounts that have elevated privileges, such as administrative accounts. Protects against threats, like unauthorized changes to critical systems or the exfiltration of sensitive data, by closely monitoring and controlling these powerful accounts. Secure credential vaulting, session recording and monitoring, just-in-time (JIT) access, and privileged access threat analytics. Unit 3 - CIT 220 Privileged Access Management (PAM)",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-30",
            "slideNumber": 30,
            "title": "Complementary Roles:",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Identity Governance (IGA) & Privileged Access (PAM)",
            "lead": "Complementary Roles: IGA provides the foundational framework for managing all identities and their baseline access, while PAM provides the specialized controls for the most",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Complementary Roles:</h3><p class=\"lead-statement\">IGA provides the foundational framework for managing all identities and their baseline access, while PAM provides the specialized controls for the most</p><div class=\"info-card mt-3\"><p>sensitive identities. Integrated Security: Integrating IGA and PAM creates a more robust security strategy by giving a unified view of all user activities, from regular users to privileged administrators. Enhanced Risk Management: Combining these solutions helps organizations better manage risks, enforce policies consistently, and improve overall security by providing complete visibility and control. How They Complement Each Other</p></div>",
            "cleanText": "Complementary Roles: IGA provides the foundational framework for managing all identities and their baseline access, while PAM provides the specialized controls for the most sensitive identities. Integrated Security: Integrating IGA and PAM creates a more robust security strategy by giving a unified view of all user activities, from regular users to privileged administrators. Enhanced Risk Management: Combining these solutions helps organizations better manage risks, enforce policies consistently, and improve overall security by providing complete visibility and control. How They Complement Each Other",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-31",
            "slideNumber": 31,
            "title": "References: https://www.lepide.com/blog/what-is-identity-and-access-management/",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Identity Governance (IGA) & Privileged Access (PAM)",
            "lead": "References https://www.lepide.com/blog/what-is-identity-and-access-management/ https://www.wallarm.com/what/what-is-identity-and-access-",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>References: https://www.lepide.com/blog/what-is-identity-and-access-management/</h3><p class=\"lead-statement\">https://www.lepide.com/blog/what-is-identity-and-access-management/ https://www.wallarm.com/what/what-is-identity-and-access-</p><div class=\"info-card mt-3\"><p>management Unit 3 - CIT 220</p></div>",
            "cleanText": "References https://www.lepide.com/blog/what-is-identity-and-access-management/ https://www.wallarm.com/what/what-is-identity-and-access- management Unit 3 - CIT 220",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-32",
            "slideNumber": 32,
            "title": "Thank You: for your attention",
            "eyebrow": "CIT 220 • Unit 03",
            "subtitle": "Identity Governance (IGA) & Privileged Access (PAM)",
            "lead": "Thank You for your attention",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<div class=\"intro-author-card\"><div class=\"institution-badge\"><span>West Visayas State University • CICT Main Campus, Iloilo City</span></div><h2>Thank You!</h2><p class=\"intro-tagline\">CIT 220 Information Assurance and Security 2 • Unit 03 Complete</p><p class=\"mt-4 text-xs text-slate-500 dark:text-slate-400\">Curriculum instruction by Prof. Chin Ann Feliprada • WVSU CICT</p></div>",
            "cleanText": "Thank You for your attention",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    }
  ]
};
