import { Topic } from '../../../types/content';

export const TOPIC_01: Topic = {
  "id": "cit220-unit-01",
  "slug": "01-foundations-of-advanced-security",
  "topicNumber": "01",
  "title": "Foundations of Advanced Security",
  "subtitle": "Core Principles, Enterprise Architecture, STRIDE Threat Modeling & Risk Management",
  "description": "Comprehensive foundations of information assurance: beyond the CIA triad, business-driven architectures (SABSA/TOGAF), threat modeling with STRIDE, risk treatment, APT intelligence, and compliance gap analysis.",
  "author": "Chin Ann Feliprada",
  "originalPath": "cit220_01_foundations_of_advanced_security",
  "badge": "Security Foundations",
  "tags": ["CIA Triad", "SABSA", "TOGAF", "STRIDE", "Threat Modeling", "Risk Management", "APTs", "Compliance Gap Analysis", "HIPAA"],
  "totalSlides": 56,
  "sections": [
    {
      "id": "core-principles",
      "title": "Core Security Principles & Beyond CIA Triad",
      "eyebrow": "Security Foundations",
      "summary": "CIA triad fundamentals, authentication, authorization, accountability, and non-repudiation in advanced security architectures.",
      "slides": [
          {
            "id": "slide-1",
            "slideNumber": 1,
            "title": "Information Assurance and Security 2",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Core Security Principles & Beyond CIA Triad",
            "lead": "Information Assurance and Security 2 01/15 FOUNDATIONS OF",
            "byline": "Prof. Chin Ann Feliprada • WVSU CICT Main Campus, Iloilo City",
            "isTitleSlide": true,
            "isSectionDivider": false,
            "rawHtml": "<div class=\"intro-author-card\"><div class=\"institution-badge\"><span>West Visayas State University • CICT Main Campus, Iloilo City</span></div><h2>Foundations of Advanced Security</h2><p class=\"intro-tagline\">CIT 220 Information Assurance and Security 2 • Unit 01</p><p class=\"mt-4 text-xs text-slate-500 dark:text-slate-400\">Course Instructor: Prof. Chin Ann Feliprada</p></div>",
            "cleanText": "Information Assurance and Security 2 01/15 FOUNDATIONS OF ADVANCED SECURITY UNIT 1",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-2",
            "slideNumber": 2,
            "title": "- Review core security principles.",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Core Security Principles & Beyond CIA Triad",
            "lead": "- Review core security principles. - Understand Enterprise Security Architecture frameworks.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>- Review core security principles.</h3><p class=\"lead-statement\">Architecture frameworks. methodologies.</p><div class=\"info-card mt-3\"><p>Intelligence and APTs. 02/15 OBJECTIVES LEARNING Information Assurance and Security 2</p></div><ul class=\"compact mt-3\"><li>Understand Enterprise Security</li><li>Apply risk management</li><li>Define and analyze Threat</li></ul>",
            "cleanText": "- Review core security principles. - Understand Enterprise Security Architecture frameworks. - Apply risk management methodologies. - Define and analyze Threat Intelligence and APTs. 02/15 OBJECTIVES LEARNING Information Assurance and Security 2",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-3",
            "slideNumber": 3,
            "title": "CORE SECURITY PRINCIPLES",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Core Security Principles & Beyond CIA Triad",
            "lead": "03/15 CORE SECURITY PRINCIPLES Confidentiality, Integrity, Availability (CIA",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>CORE SECURITY PRINCIPLES</h3><p class=\"lead-statement\">CORE SECURITY PRINCIPLES Confidentiality, Integrity, Availability (CIA</p><div class=\"info-card mt-3\"><p>Triad): unauthorized access. destroyed in an unauthorized manner. and systems when needed. REVIEW 1.1</p></div><ul class=\"compact mt-3\"><li>Confidentiality: Protecting data from</li><li>Integrity: Ensuring data is not altered or</li><li>Availability: Guaranteeing access to data</li></ul>",
            "cleanText": "03/15 CORE SECURITY PRINCIPLES Confidentiality, Integrity, Availability (CIA Triad): - Confidentiality: Protecting data from unauthorized access. - Integrity: Ensuring data is not altered or destroyed in an unauthorized manner. - Availability: Guaranteeing access to data and systems when needed. REVIEW 1.1",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-4",
            "slideNumber": 4,
            "title": "- Authentication: Verifying the identity of a",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Core Security Principles & Beyond CIA Triad",
            "lead": "03/15 - Authentication: Verifying the identity of a user or system.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>- Authentication: Verifying the identity of a</h3><p class=\"lead-statement\">user or system. to an authenticated entity.</p><div class=\"info-card mt-3\"><p>performed by a specific party. BEYOND THE CIA TRIAD: 1.1</p></div><ul class=\"compact mt-3\"><li>Authentication: Verifying the identity of a</li><li>Authorization: Granting specific permissions</li><li>Non-repudiation: Proving an action was</li></ul>",
            "cleanText": "03/15 - Authentication: Verifying the identity of a user or system. - Authorization: Granting specific permissions to an authenticated entity. - Non-repudiation: Proving an action was performed by a specific party. BEYOND THE CIA TRIAD: 1.1",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-5",
            "slideNumber": 5,
            "title": "BEYOND THE CIA TRIAD: 1.1",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Core Security Principles & Beyond CIA Triad",
            "lead": "03/15 BEYOND THE CIA TRIAD: 1.1",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>BEYOND THE CIA TRIAD: 1.1</h3><p class=\"lead-statement\">BEYOND THE CIA TRIAD: 1.1</p>",
            "cleanText": "03/15 BEYOND THE CIA TRIAD: 1.1",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-6",
            "slideNumber": 6,
            "title": "- Authentication: Verifying the identity of a",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Core Security Principles & Beyond CIA Triad",
            "lead": "03/15 - Authentication: Verifying the identity of a user or system.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>- Authentication: Verifying the identity of a</h3><p class=\"lead-statement\">user or system. to an authenticated entity.</p><div class=\"info-card mt-3\"><p>performed by a specific party. BEYOND THE CIA TRIAD: 1.1</p></div><ul class=\"compact mt-3\"><li>Authentication: Verifying the identity of a</li><li>Authorization: Granting specific permissions</li><li>Non-repudiation: Proving an action was</li></ul>",
            "cleanText": "03/15 - Authentication: Verifying the identity of a user or system. - Authorization: Granting specific permissions to an authenticated entity. - Non-repudiation: Proving an action was performed by a specific party. BEYOND THE CIA TRIAD: 1.1",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-7",
            "slideNumber": 7,
            "title": "Information Assurance and Security 2",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Core Security Principles & Beyond CIA Triad",
            "lead": "04/15 Information Assurance and Security 2 ENTERPRISE SECURITY",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Information Assurance and Security 2</h3><p class=\"lead-statement\">Information Assurance and Security 2 ENTERPRISE SECURITY</p><div class=\"info-card mt-3\"><p>ARCHITECTURE Enterprise Security Architecture (ESA) is a comprehensive, strategic framework that aligns an organization&#x27;s security policies, processes, and technologies with its business goals. It essentially integrates security principles into the overall enterprise architecture to protect data, systems, and networks from threats and vulnerabilities.</p></div>",
            "cleanText": "04/15 Information Assurance and Security 2 ENTERPRISE SECURITY ARCHITECTURE Enterprise Security Architecture (ESA) is a comprehensive, strategic framework that aligns an organization's security policies, processes, and technologies with its business goals. It essentially integrates security principles into the overall enterprise architecture to protect data, systems, and networks from threats and vulnerabilities.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-8",
            "slideNumber": 8,
            "title": "Lorem ipsum dolor sit amet, consectetur",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Core Security Principles & Beyond CIA Triad",
            "lead": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Lorem ipsum dolor sit amet, consectetur</h3><p class=\"lead-statement\">adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna</p><div class=\"info-card mt-3\"><p>aliqua. . Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. . Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. . Information Assurance and Security 2 05/15</p></div>",
            "cleanText": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. . Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. . Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. . Information Assurance and Security 2 05/15",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-9",
            "slideNumber": 9,
            "title": "Complex Environments:",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Core Security Principles & Beyond CIA Triad",
            "lead": "06/15 Complex Environments: Modern enterprises have vast, interconnected systems distributed",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Complex Environments:</h3><p class=\"lead-statement\">Complex Environments: Modern enterprises have vast, interconnected systems distributed</p><div class=\"info-card mt-3\"><p>across various locations and technologies, making them vulnerable to attacks. Evolving Threats: The nature of cyber threats is constantly changing, requiring a dynamic and adaptable security approach. Data Protection: ESA helps protect sensitive data from unauthorized access, theft, or misuse. Business Continuity: By preventing and mitigating attacks, ESA helps ensure business operations can continue without disruption. Cost Savings: Proactive security measures can prevent costly data breaches and recovery efforts. ESA  WHY IS  IMPORTANT?</p></div>",
            "cleanText": "06/15 Complex Environments: Modern enterprises have vast, interconnected systems distributed across various locations and technologies, making them vulnerable to attacks. Evolving Threats: The nature of cyber threats is constantly changing, requiring a dynamic and adaptable security approach. Data Protection: ESA helps protect sensitive data from unauthorized access, theft, or misuse. Business Continuity: By preventing and mitigating attacks, ESA helps ensure business operations can continue without disruption. Cost Savings: Proactive security measures can prevent costly data breaches and recovery efforts. ESA  WHY IS  IMPORTANT?",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-10",
            "slideNumber": 10,
            "title": "Ensures consistent security controls across the",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Core Security Principles & Beyond CIA Triad",
            "lead": "06/15 Ensures consistent security controls across the organization.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Ensures consistent security controls across the</h3><p class=\"lead-statement\">Ensures consistent security controls across the organization.</p><div class=\"info-card mt-3\"><p>Aligns security with business objectives. Facilitates informed decision-making and resource allocation. ESA  WHY IS  IMPORTANT?</p></div>",
            "cleanText": "06/15 Ensures consistent security controls across the organization. Aligns security with business objectives. Facilitates informed decision-making and resource allocation. ESA  WHY IS  IMPORTANT?",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "enterprise-architecture",
      "title": "Enterprise Security Architecture Frameworks",
      "eyebrow": "Architecture & Governance",
      "summary": "Business-driven security frameworks including SABSA, TOGAF, and enterprise security governance.",
      "slides": [
          {
            "id": "slide-11",
            "slideNumber": 11,
            "title": "KEY: FRAMEWORK",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Enterprise Security Architecture Frameworks",
            "lead": "07/15 KEY FRAMEWORK",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>KEY: FRAMEWORK</h3><p class=\"lead-statement\">KEY FRAMEWORK</p><div class=\"info-card mt-3\"><p>A widely-used enterprise architecture framework that includes a security dimension. TOGAF (The Open Group Architecture Framework): A security-specific framework that links security to business goals from the start. SABSA (Sherwood Applied Business Security Architecture): Information Assurance and Security 2 ESA</p></div>",
            "cleanText": "07/15 KEY FRAMEWORK A widely-used enterprise architecture framework that includes a security dimension. TOGAF (The Open Group Architecture Framework): A security-specific framework that links security to business goals from the start. SABSA (Sherwood Applied Business Security Architecture): Information Assurance and Security 2 ESA",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-12",
            "slideNumber": 12,
            "title": "Foundations of Advanced Security - Slide 12",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Enterprise Security Architecture Frameworks",
            "lead": "06/15",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Foundations of Advanced Security - Slide 12</h3>",
            "cleanText": "06/15",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-13",
            "slideNumber": 13,
            "title": "SABSA (Sherwood Applied Business Security",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Enterprise Security Architecture Frameworks",
            "lead": "07/15 SABSA (Sherwood Applied Business Security Architecture) is a model and methodology for",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>SABSA (Sherwood Applied Business Security</h3><p class=\"lead-statement\">SABSA (Sherwood Applied Business Security Architecture) is a model and methodology for</p><div class=\"info-card mt-3\"><p>developing a risk-driven enterprise information security architecture and service management, to support critical business processes. It was developed independently from the Zachman Framework, but has a similar structure. SABSA (Sherwood Applied Business Security Architecture): Information Assurance and Security 2</p></div>",
            "cleanText": "07/15 SABSA (Sherwood Applied Business Security Architecture) is a model and methodology for developing a risk-driven enterprise information security architecture and service management, to support critical business processes. It was developed independently from the Zachman Framework, but has a similar structure. SABSA (Sherwood Applied Business Security Architecture): Information Assurance and Security 2",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-14",
            "slideNumber": 14,
            "title": "THREAT: MODELING",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Enterprise Security Architecture Frameworks",
            "lead": "10/15 THREAT MODELING",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>THREAT: MODELING</h3><p class=\"lead-statement\">THREAT MODELING</p><div class=\"info-card mt-3\"><p>&amp; RISK ANALYSIS 1.2 Information Assurance and Security 2</p></div>",
            "cleanText": "10/15 THREAT MODELING & RISK ANALYSIS 1.2 Information Assurance and Security 2",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-15",
            "slideNumber": 15,
            "title": "Information Assurance and Security 2",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Enterprise Security Architecture Frameworks",
            "lead": "04/15 Information Assurance and Security 2 RELATIONSHIP BETWEEN",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Information Assurance and Security 2</h3><p class=\"lead-statement\">Information Assurance and Security 2 RELATIONSHIP BETWEEN</p><div class=\"info-card mt-3\"><p>THREAT MODELING AND RISK ANALYSIS: complementary practices. organizations can develop a comprehensive understanding of their security posture and prioritize their security efforts.</p></div><ul class=\"compact mt-3\"><li>Threat modeling and risk analysis are</li><li>By combining these approaches,</li></ul>",
            "cleanText": "04/15 Information Assurance and Security 2 RELATIONSHIP BETWEEN THREAT MODELING AND RISK ANALYSIS: - Threat modeling and risk analysis are complementary practices. - By combining these approaches, organizations can develop a comprehensive understanding of their security posture and prioritize their security efforts.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-16",
            "slideNumber": 16,
            "title": "11/15  THREAT MODELING AND RISK",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Enterprise Security Architecture Frameworks",
            "lead": "11/15  THREAT MODELING AND RISK ANALYSIS Threat modeling",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>11/15  THREAT MODELING AND RISK</h3><p class=\"lead-statement\">ANALYSIS Threat modeling</p><div class=\"info-card mt-3\"><p>involves systematically analyzing a system to identify potential vulnerabilities and threats, Risk Analysis risk analysis assesses the likelihood and impact of those threats. Threat modeling and risk analysis are crucial practices for proactively identifying and mitigating potential security threats to systems, applications, and organizations.</p></div>",
            "cleanText": "11/15  THREAT MODELING AND RISK ANALYSIS Threat modeling involves systematically analyzing a system to identify potential vulnerabilities and threats, Risk Analysis risk analysis assesses the likelihood and impact of those threats. Threat modeling and risk analysis are crucial practices for proactively identifying and mitigating potential security threats to systems, applications, and organizations.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-17",
            "slideNumber": 17,
            "title": "Information Assurance and Security 2",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Enterprise Security Architecture Frameworks",
            "lead": "04/15 Information Assurance and Security 2 RELATIONSHIP BETWEEN",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Information Assurance and Security 2</h3><p class=\"lead-statement\">Information Assurance and Security 2 RELATIONSHIP BETWEEN</p><div class=\"info-card mt-3\"><p>THREAT MODELING AND RISK ANALYSIS: identify a vulnerability, and risk analysis would assess the likelihood of that vulnerability being exploited and the potential impact on the organization.</p></div><ul class=\"compact mt-3\"><li>For example, a threat model might</li></ul>",
            "cleanText": "04/15 Information Assurance and Security 2 RELATIONSHIP BETWEEN THREAT MODELING AND RISK ANALYSIS: - For example, a threat model might identify a vulnerability, and risk analysis would assess the likelihood of that vulnerability being exploited and the potential impact on the organization.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-18",
            "slideNumber": 18,
            "title": "Attack Trees:",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Enterprise Security Architecture Frameworks",
            "lead": "06/15 Attack Trees: A visual representation of potential attack paths that can be used",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Attack Trees:</h3><p class=\"lead-statement\">Attack Trees: A visual representation of potential attack paths that can be used</p><div class=\"info-card mt-3\"><p>in threat modeling and risk analysis. DREAD: A risk assessment method that considers Damage potential, Reproducibility, Exploitability, Affected users, and Discoverability. LLM-Specific Threats: Advanced threat modeling and risk analysis are becoming increasingly important for Large Language Model (LLM)-powered applications, addressing unique threats like data poisoning, prompt injection, and jailbreaking. THREAT MODELING AND RISK ANALYSIS ADVANCED CONCEPTS:</p></div>",
            "cleanText": "06/15 Attack Trees: A visual representation of potential attack paths that can be used in threat modeling and risk analysis. DREAD: A risk assessment method that considers Damage potential, Reproducibility, Exploitability, Affected users, and Discoverability. LLM-Specific Threats: Advanced threat modeling and risk analysis are becoming increasingly important for Large Language Model (LLM)-powered applications, addressing unique threats like data poisoning, prompt injection, and jailbreaking. THREAT MODELING AND RISK ANALYSIS ADVANCED CONCEPTS:",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "threat-modeling-stride",
      "title": "Threat Modeling & The STRIDE Methodology",
      "eyebrow": "Threat Modeling",
      "summary": "Deconstructing threat vectors, attack trees, and comprehensive threat coverage with the STRIDE model.",
      "slides": [
          {
            "id": "slide-19",
            "slideNumber": 19,
            "title": "RISK MANAGEMENT",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Modeling & The STRIDE Methodology",
            "lead": "RISK MANAGEMENT 07/15 AND METHODOLOGIES",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>RISK MANAGEMENT</h3><p class=\"lead-statement\">07/15 AND METHODOLOGIES</p><div class=\"info-card mt-3\"><p>Information Assurance and Security 2</p></div>",
            "cleanText": "RISK MANAGEMENT 07/15 AND METHODOLOGIES Information Assurance and Security 2",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-20",
            "slideNumber": 20,
            "title": "RISK: MANAGEMENT",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Modeling & The STRIDE Methodology",
            "lead": "08/15 RISK MANAGEMENT",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>RISK: MANAGEMENT</h3><p class=\"lead-statement\">RISK MANAGEMENT</p><div class=\"info-card mt-3\"><p>PROCESS Information Assurance and Security 2</p></div>",
            "cleanText": "08/15 RISK MANAGEMENT PROCESS Information Assurance and Security 2",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-21",
            "slideNumber": 21,
            "title": "Information Assurance and Security 2",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Modeling & The STRIDE Methodology",
            "lead": "Information Assurance and Security 2 08/15 RISK",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Information Assurance and Security 2</h3><p class=\"lead-statement\">08/15 RISK</p><div class=\"info-card mt-3\"><p>MANAGEMENT PROCESS</p></div>",
            "cleanText": "Information Assurance and Security 2 08/15 RISK MANAGEMENT PROCESS",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-22",
            "slideNumber": 22,
            "title": "08/15  RISK  MANAGEMENT PROCESS",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Modeling & The STRIDE Methodology",
            "lead": "08/15  RISK  MANAGEMENT PROCESS",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>08/15  RISK  MANAGEMENT PROCESS</h3>",
            "cleanText": "08/15  RISK  MANAGEMENT PROCESS",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-23",
            "slideNumber": 23,
            "title": "THREAT: INTELLIGENCE,",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Modeling & The STRIDE Methodology",
            "lead": "06/15 THREAT INTELLIGENCE,",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>THREAT: INTELLIGENCE,</h3><p class=\"lead-statement\">THREAT INTELLIGENCE,</p><div class=\"info-card mt-3\"><p>THREAT ASSESSMENT AND THREAT MODELING</p></div>",
            "cleanText": "06/15 THREAT INTELLIGENCE, THREAT ASSESSMENT AND THREAT MODELING",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-24",
            "slideNumber": 24,
            "title": "THREAT: INTELLIGENCE",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Modeling & The STRIDE Methodology",
            "lead": "10/15 THREAT INTELLIGENCE",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>THREAT: INTELLIGENCE</h3><p class=\"lead-statement\">THREAT INTELLIGENCE</p><div class=\"info-card mt-3\"><p>&amp; APTS 1.2 Information Assurance and Security 2</p></div>",
            "cleanText": "10/15 THREAT INTELLIGENCE & APTS 1.2 Information Assurance and Security 2",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-25",
            "slideNumber": 25,
            "title": "10/15  THREAT INTELLIGENCE  LIFECYCLE",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Modeling & The STRIDE Methodology",
            "lead": "10/15  THREAT INTELLIGENCE  LIFECYCLE 01 Defining",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>10/15  THREAT INTELLIGENCE  LIFECYCLE</h3><p class=\"lead-statement\">01 Defining</p><div class=\"info-card mt-3\"><p>requirements Planning 02 Gathering raw data Collection 01 Normalizing and structuring the data Processing 02 Extracting insights Analysis 02 Sharing the intelligence with stakeholders Dissemination Threat Intelligence: The process of collecting and analyzing information about potential and current threats to an organization. It&#x27;s not just data, but actionable insights.</p></div>",
            "cleanText": "10/15  THREAT INTELLIGENCE  LIFECYCLE 01 Defining requirements Planning 02 Gathering raw data Collection 01 Normalizing and structuring the data Processing 02 Extracting insights Analysis 02 Sharing the intelligence with stakeholders Dissemination Threat Intelligence: The process of collecting and analyzing information about potential and current threats to an organization. It's not just data, but actionable insights.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-26",
            "slideNumber": 26,
            "title": "Highly sophisticated, prolonged",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Modeling & The STRIDE Methodology",
            "lead": "06/15 Highly sophisticated, prolonged attacks where an intruder establishes",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Highly sophisticated, prolonged</h3><p class=\"lead-statement\">Highly sophisticated, prolonged attacks where an intruder establishes</p><div class=\"info-card mt-3\"><p>a long-term presence on a network to steal sensitive data. APTs are often state-sponsored and target specific organizations. ADVANCE PESISTENT THREATS (APT)</p></div>",
            "cleanText": "06/15 Highly sophisticated, prolonged attacks where an intruder establishes a long-term presence on a network to steal sensitive data. APTs are often state-sponsored and target specific organizations. ADVANCE PESISTENT THREATS (APT)",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-27",
            "slideNumber": 27,
            "title": "ADVANCE PESISTENT THREATS",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Modeling & The STRIDE Methodology",
            "lead": "06/15 ADVANCE PESISTENT THREATS EXAMPLES",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>ADVANCE PESISTENT THREATS</h3><p class=\"lead-statement\">ADVANCE PESISTENT THREATS EXAMPLES</p><div class=\"info-card mt-3\"><p>Stuxnet: This highly sophisticated malware was specifically designed to target and damage Iran&#x27;s nuclear facilities, demonstrating the potential for physical damage caused by cyberattacks. APT41: This Chinese state-sponsored group engages in both espionage and financially motivated attacks, demonstrating a dual-purpose approach. APT29 (Cozy Bear): Also linked to Russian intelligence, this group has been involved in cyber espionage campaigns, particularly targeting government and healthcare sectors APT28 (Fancy Bear): Linked to Russian military intelligence, this group has been known for targeting political entities and organizations worldwide, including election interference.</p></div>",
            "cleanText": "06/15 ADVANCE PESISTENT THREATS EXAMPLES Stuxnet: This highly sophisticated malware was specifically designed to target and damage Iran's nuclear facilities, demonstrating the potential for physical damage caused by cyberattacks. APT41: This Chinese state-sponsored group engages in both espionage and financially motivated attacks, demonstrating a dual-purpose approach. APT29 (Cozy Bear): Also linked to Russian intelligence, this group has been involved in cyber espionage campaigns, particularly targeting government and healthcare sectors APT28 (Fancy Bear): Linked to Russian military intelligence, this group has been known for targeting political entities and organizations worldwide, including election interference.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "risk-management",
      "title": "Risk Management Lifecycle & Frameworks",
      "eyebrow": "Risk Analysis",
      "summary": "Risk assessment, evaluation, treatment strategies (avoid, mitigate, transfer, accept), and continuous monitoring.",
      "slides": [
          {
            "id": "slide-28",
            "slideNumber": 28,
            "title": "& REGULATIONS",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Risk Management Lifecycle & Frameworks",
            "lead": "12/15 & REGULATIONS SECURITY",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>&amp; REGULATIONS</h3><p class=\"lead-statement\">&amp; REGULATIONS SECURITY</p><div class=\"info-card mt-3\"><p>FRAMEWORKS, STANDARDS 1.4</p></div>",
            "cleanText": "12/15 & REGULATIONS SECURITY FRAMEWORKS, STANDARDS 1.4",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-29",
            "slideNumber": 29,
            "title": "1.4: An IT security framework is a series of",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Risk Management Lifecycle & Frameworks",
            "lead": "12/15 1.4 An IT security framework is a series of",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>1.4: An IT security framework is a series of</h3><p class=\"lead-statement\">1.4 An IT security framework is a series of</p><div class=\"info-card mt-3\"><p>documented processes that define policies and procedures around the implementation and ongoing management of information security controls. These frameworks are a blueprint for managing risk and reducing vulnerabilities. WHAT IS AN IT SECURITY FRAMEWORK?</p></div>",
            "cleanText": "12/15 1.4 An IT security framework is a series of documented processes that define policies and procedures around the implementation and ongoing management of information security controls. These frameworks are a blueprint for managing risk and reducing vulnerabilities. WHAT IS AN IT SECURITY FRAMEWORK?",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-30",
            "slideNumber": 30,
            "title": "Foundations of Advanced Security - Slide 30",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Risk Management Lifecycle & Frameworks",
            "lead": "12/15",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Foundations of Advanced Security - Slide 30</h3>",
            "cleanText": "12/15",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-31",
            "slideNumber": 31,
            "title": "The choice to use a particular IT security",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Risk Management Lifecycle & Frameworks",
            "lead": "12/15 The choice to use a particular IT security framework can be driven by multiple factors.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>The choice to use a particular IT security</h3><p class=\"lead-statement\">The choice to use a particular IT security framework can be driven by multiple factors.</p><div class=\"info-card mt-3\"><p>The type of industry or compliance requirements could be deciding factors. Publicly traded companies, for example, may wish to use COBIT to comply with SOX, while the healthcare sector may consider HITRUST. The ISO 27000 series of information security frameworks, on the other hand, is applicable in public and private sectors. HOW TO CHOOSE AN IT SECURITY FRAMEWORK</p></div>",
            "cleanText": "12/15 The choice to use a particular IT security framework can be driven by multiple factors. The type of industry or compliance requirements could be deciding factors. Publicly traded companies, for example, may wish to use COBIT to comply with SOX, while the healthcare sector may consider HITRUST. The ISO 27000 series of information security frameworks, on the other hand, is applicable in public and private sectors. HOW TO CHOOSE AN IT SECURITY FRAMEWORK",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-32",
            "slideNumber": 32,
            "title": "SECURITY FRAMEWORKS",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Risk Management Lifecycle & Frameworks",
            "lead": "12/15 SECURITY FRAMEWORKS NIST Risk Management Framework (RMF): A",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>SECURITY FRAMEWORKS</h3><p class=\"lead-statement\">SECURITY FRAMEWORKS NIST Risk Management Framework (RMF): A</p><div class=\"info-card mt-3\"><p>six-step process (Categorize, Select, Implement, Assess, Authorize, Monitor) for managing security risks in federal information systems. ISO 27005: An international standard that provides guidelines for information security risk management. COMMON  1.4</p></div>",
            "cleanText": "12/15 SECURITY FRAMEWORKS NIST Risk Management Framework (RMF): A six-step process (Categorize, Select, Implement, Assess, Authorize, Monitor) for managing security risks in federal information systems. ISO 27005: An international standard that provides guidelines for information security risk management. COMMON  1.4",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-33",
            "slideNumber": 33,
            "title": "Foundations of Advanced Security - Slide 33",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Risk Management Lifecycle & Frameworks",
            "lead": "12/15",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Foundations of Advanced Security - Slide 33</h3>",
            "cleanText": "12/15",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-34",
            "slideNumber": 34,
            "title": "SUMMARY & KEY TAKEAWAYS",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Risk Management Lifecycle & Frameworks",
            "lead": "10/15 SUMMARY & KEY TAKEAWAYS Advanced security requires a strategic, architectural approach to",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>SUMMARY &amp; KEY TAKEAWAYS</h3><p class=\"lead-statement\">SUMMARY &amp; KEY TAKEAWAYS Advanced security requires a strategic, architectural approach to</p><div class=\"info-card mt-3\"><p>protect the entire enterprise. Risk management frameworks provide a structured way to identify and mitigate threats. Information Assurance and Security 2 Threat intelligence is crucial for proactive defense against sophisticated attackers like APTs. Security is not just a technical problem; it&#x27;s a business challenge that requires strategic planning and governance.</p></div>",
            "cleanText": "10/15 SUMMARY & KEY TAKEAWAYS Advanced security requires a strategic, architectural approach to protect the entire enterprise. Risk management frameworks provide a structured way to identify and mitigate threats. Information Assurance and Security 2 Threat intelligence is crucial for proactive defense against sophisticated attackers like APTs. Security is not just a technical problem; it's a business challenge that requires strategic planning and governance.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-35",
            "slideNumber": 35,
            "title": "Studio Shodwe",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Risk Management Lifecycle & Frameworks",
            "lead": "Studio Shodwe 06/15 www.reallygreatsite.com",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Studio Shodwe</h3><p class=\"lead-statement\">06/15 www.reallygreatsite.com</p><div class=\"info-card mt-3\"><p>BEST  PRACTICES Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Strong Passwords Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Employee Training Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Access Control Regular Backups</p></div>",
            "cleanText": "Studio Shodwe 06/15 www.reallygreatsite.com BEST  PRACTICES Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Strong Passwords Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Employee Training Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Access Control Regular Backups",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "threat-intelligence-apts",
      "title": "Threat Intelligence & Advanced Persistent Threats",
      "eyebrow": "Threat Intelligence",
      "summary": "The Cyber Threat Intelligence lifecycle, tactics, techniques, and procedures (TTPs) of prolonged APT campaigns.",
      "slides": [
          {
            "id": "slide-36",
            "slideNumber": 36,
            "title": "APPLICATION OF THREAT",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Intelligence & Advanced Persistent Threats",
            "lead": "12/15 APPLICATION OF THREAT MODELING AND ANALYSIS",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>APPLICATION OF THREAT</h3><p class=\"lead-statement\">APPLICATION OF THREAT MODELING AND ANALYSIS</p>",
            "cleanText": "12/15 APPLICATION OF THREAT MODELING AND ANALYSIS",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-37",
            "slideNumber": 37,
            "title": "STRIDE is a threat modeling methodology used to",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Intelligence & Advanced Persistent Threats",
            "lead": "03/15 STRIDE is a threat modeling methodology used to identify potential security weaknesses in a system by",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>STRIDE is a threat modeling methodology used to</h3><p class=\"lead-statement\">STRIDE is a threat modeling methodology used to identify potential security weaknesses in a system by</p><div class=\"info-card mt-3\"><p>categorizing threats into six types. Developed by Microsoft, STRIDE helps security professionals and developers proactively address vulnerabilities by thinking like attackers and assessing potential risks. STRIDE</p></div>",
            "cleanText": "03/15 STRIDE is a threat modeling methodology used to identify potential security weaknesses in a system by categorizing threats into six types. Developed by Microsoft, STRIDE helps security professionals and developers proactively address vulnerabilities by thinking like attackers and assessing potential risks. STRIDE",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-38",
            "slideNumber": 38,
            "title": "08/15  HERE'S A BREAKDOWN OF EACH STRIDE CATEGORY:",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Intelligence & Advanced Persistent Threats",
            "lead": "08/15  HERE'S A BREAKDOWN OF EACH STRIDE CATEGORY: - -",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>08/15  HERE&#x27;S A BREAKDOWN OF EACH STRIDE CATEGORY:</h3><ul class=\"compact mt-3\"><li></li><li></li><li></li><li></li><li></li><li></li></ul>",
            "cleanText": "08/15  HERE'S A BREAKDOWN OF EACH STRIDE CATEGORY: - - - - - -",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-39",
            "slideNumber": 39,
            "title": "USING STRIDE IN THREAT MODELING:",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Intelligence & Advanced Persistent Threats",
            "lead": "06/15 USING STRIDE IN THREAT MODELING: System Modeling:",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>USING STRIDE IN THREAT MODELING:</h3><p class=\"lead-statement\">USING STRIDE IN THREAT MODELING: System Modeling:</p><div class=\"info-card mt-3\"><p>Create a visual representation of the system, including components, data flows, and trust boundaries. Mitigation: Develop security controls and countermeasures to address the identified vulnerabilities. Applying STRIDE: For each element in the system model, analyze potential threats based on the six STRIDE categories. Identifying Vulnerabilities: Determine how an attacker could exploit each potential threat. 03 04 01 02</p></div>",
            "cleanText": "06/15 USING STRIDE IN THREAT MODELING: System Modeling: Create a visual representation of the system, including components, data flows, and trust boundaries. Mitigation: Develop security controls and countermeasures to address the identified vulnerabilities. Applying STRIDE: For each element in the system model, analyze potential threats based on the six STRIDE categories. Identifying Vulnerabilities: Determine how an attacker could exploit each potential threat. 03 04 01 02",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-40",
            "slideNumber": 40,
            "title": "Comprehensive Threat Coverage:",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Intelligence & Advanced Persistent Threats",
            "lead": "03/15 Comprehensive Threat Coverage: - STRIDE ensures a thorough assessment by",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Comprehensive Threat Coverage:</h3><p class=\"lead-statement\">Comprehensive Threat Coverage: considering a wide range of threat categories.</p><div class=\"info-card mt-3\"><p>Early Vulnerability Detection: potential weaknesses early in the development lifecycle. Improved Security Posture: the development of more robust and resilient systems. BENEFITS OF STRIDE:</p></div><ul class=\"compact mt-3\"><li>STRIDE ensures a thorough assessment by</li><li>By thinking like an attacker, STRIDE helps identify</li><li>STRIDE fosters a security-first mindset and promotes</li></ul>",
            "cleanText": "03/15 Comprehensive Threat Coverage: - STRIDE ensures a thorough assessment by considering a wide range of threat categories. Early Vulnerability Detection: - By thinking like an attacker, STRIDE helps identify potential weaknesses early in the development lifecycle. Improved Security Posture: - STRIDE fosters a security-first mindset and promotes the development of more robust and resilient systems. BENEFITS OF STRIDE:",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-41",
            "slideNumber": 41,
            "title": "SECURITY FRAMEWORKS,",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Intelligence & Advanced Persistent Threats",
            "lead": "12/15 SECURITY FRAMEWORKS, STANDARDS & COMPLIANCE",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>SECURITY FRAMEWORKS,</h3><p class=\"lead-statement\">SECURITY FRAMEWORKS, STANDARDS &amp; COMPLIANCE</p>",
            "cleanText": "12/15 SECURITY FRAMEWORKS, STANDARDS & COMPLIANCE",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-42",
            "slideNumber": 42,
            "title": "12/15  WHAT IS A COMPLIANCE GAP ANALYSIS",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Intelligence & Advanced Persistent Threats",
            "lead": "12/15  WHAT IS A COMPLIANCE GAP ANALYSIS",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>12/15  WHAT IS A COMPLIANCE GAP ANALYSIS</h3>",
            "cleanText": "12/15  WHAT IS A COMPLIANCE GAP ANALYSIS",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-43",
            "slideNumber": 43,
            "title": "12/15  IDENTIFY SECURITY FRAMEWORK",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Intelligence & Advanced Persistent Threats",
            "lead": "12/15  IDENTIFY SECURITY FRAMEWORK",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>12/15  IDENTIFY SECURITY FRAMEWORK</h3>",
            "cleanText": "12/15  IDENTIFY SECURITY FRAMEWORK",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-44",
            "slideNumber": 44,
            "title": "Foundations of Advanced Security - Slide 44",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Threat Intelligence & Advanced Persistent Threats",
            "lead": "12/15",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Foundations of Advanced Security - Slide 44</h3>",
            "cleanText": "12/15",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "compliance-gap-analysis",
      "title": "Compliance Gap Analysis & Regulatory Case Study",
      "eyebrow": "Compliance & Audit",
      "summary": "Assessing regulatory compliance (HIPAA, PCI-DSS, ISO 27001), gap remediation, and healthcare clinic operational case study.",
      "slides": [
          {
            "id": "slide-45",
            "slideNumber": 45,
            "title": "10/15  EXAMPLE SCENARIO: HEALTHCARE CLINIC",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Compliance Gap Analysis & Regulatory Case Study",
            "lead": "10/15  EXAMPLE SCENARIO: HEALTHCARE CLINIC 01 Identify the",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>10/15  EXAMPLE SCENARIO: HEALTHCARE CLINIC</h3><p class=\"lead-statement\">01 Identify the</p><div class=\"info-card mt-3\"><p>Applicable Regulations 02 Define the Current State 03 Define the Desired State 04 Identify the Gaps 05 Develop a Remediation Plan Let&#x27;s say a healthcare clinic has a compliance gap related to patient data privacy:</p></div>",
            "cleanText": "10/15  EXAMPLE SCENARIO: HEALTHCARE CLINIC 01 Identify the Applicable Regulations 02 Define the Current State 03 Define the Desired State 04 Identify the Gaps 05 Develop a Remediation Plan Let's say a healthcare clinic has a compliance gap related to patient data privacy:",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-46",
            "slideNumber": 46,
            "title": "Let's say a healthcare clinic has a",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Compliance Gap Analysis & Regulatory Case Study",
            "lead": "03/15 Let's say a healthcare clinic has a compliance gap related to patient",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Let&#x27;s say a healthcare clinic has a</h3><p class=\"lead-statement\">Let&#x27;s say a healthcare clinic has a compliance gap related to patient</p><div class=\"info-card mt-3\"><p>data privacy: EXAMPLE SCENARIO:  HEALTHCARE CLINIC</p></div>",
            "cleanText": "03/15 Let's say a healthcare clinic has a compliance gap related to patient data privacy: EXAMPLE SCENARIO:  HEALTHCARE CLINIC",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-47",
            "slideNumber": 47,
            "title": "The clinic needs to determine which",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Compliance Gap Analysis & Regulatory Case Study",
            "lead": "03/15 The clinic needs to determine which regulations apply to their operations,",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>The clinic needs to determine which</h3><p class=\"lead-statement\">The clinic needs to determine which regulations apply to their operations,</p><div class=\"info-card mt-3\"><p>such as HIPAA (Health Insurance Portability and Accountability Act). 1. IDENTIFY THE APPLICABLE REGULATIONS</p></div>",
            "cleanText": "03/15 The clinic needs to determine which regulations apply to their operations, such as HIPAA (Health Insurance Portability and Accountability Act). 1. IDENTIFY THE APPLICABLE REGULATIONS",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-48",
            "slideNumber": 48,
            "title": "HIPAA compliance refers to adhering to the",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Compliance Gap Analysis & Regulatory Case Study",
            "lead": "03/15 HIPAA compliance refers to adhering to the standards set by the Health Insurance Portability",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>HIPAA compliance refers to adhering to the</h3><p class=\"lead-statement\">HIPAA compliance refers to adhering to the standards set by the Health Insurance Portability</p><div class=\"info-card mt-3\"><p>and Accountability Act (HIPAA) for protecting sensitive patient data. This involves implementing physical, network, and process security measures to safeguard protected health information (PHI). Both covered entities (healthcare providers, etc.) and business associates (those handling PHI) must be in compliance. 1. IDENTIFY THE APPLICABLE REGULATIONS</p></div>",
            "cleanText": "03/15 HIPAA compliance refers to adhering to the standards set by the Health Insurance Portability and Accountability Act (HIPAA) for protecting sensitive patient data. This involves implementing physical, network, and process security measures to safeguard protected health information (PHI). Both covered entities (healthcare providers, etc.) and business associates (those handling PHI) must be in compliance. 1. IDENTIFY THE APPLICABLE REGULATIONS",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-49",
            "slideNumber": 49,
            "title": "The clinic assesses its current practices",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Compliance Gap Analysis & Regulatory Case Study",
            "lead": "03/15 The clinic assesses its current practices regarding patient data handling, storage,",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>The clinic assesses its current practices</h3><p class=\"lead-statement\">The clinic assesses its current practices regarding patient data handling, storage,</p><div class=\"info-card mt-3\"><p>and access. This might involve reviewing existing policies, interviewing staff, and examining data security measures. 2. DEFINE THE CURRENT STATE</p></div>",
            "cleanText": "03/15 The clinic assesses its current practices regarding patient data handling, storage, and access. This might involve reviewing existing policies, interviewing staff, and examining data security measures. 2. DEFINE THE CURRENT STATE",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-50",
            "slideNumber": 50,
            "title": "The clinic identifies the specific",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Compliance Gap Analysis & Regulatory Case Study",
            "lead": "03/15 The clinic identifies the specific requirements of HIPAA related to patient",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>The clinic identifies the specific</h3><p class=\"lead-statement\">The clinic identifies the specific requirements of HIPAA related to patient</p><div class=\"info-card mt-3\"><p>data privacy, including data encryption, access controls, and breach notification procedures. 3. DESIRE THE CURRENT STATE</p></div>",
            "cleanText": "03/15 The clinic identifies the specific requirements of HIPAA related to patient data privacy, including data encryption, access controls, and breach notification procedures. 3. DESIRE THE CURRENT STATE",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-51",
            "slideNumber": 51,
            "title": "The clinic compares its current state with",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Compliance Gap Analysis & Regulatory Case Study",
            "lead": "03/15 The clinic compares its current state with the desired state, identifying areas where",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>The clinic compares its current state with</h3><p class=\"lead-statement\">The clinic compares its current state with the desired state, identifying areas where</p><div class=\"info-card mt-3\"><p>it falls short of HIPAA compliance. For example, they might discover that patient data is not consistently encrypted at rest or in transit, or that staff training on data privacy is insufficient. 4. IDENTIFY THE GAPS</p></div>",
            "cleanText": "03/15 The clinic compares its current state with the desired state, identifying areas where it falls short of HIPAA compliance. For example, they might discover that patient data is not consistently encrypted at rest or in transit, or that staff training on data privacy is insufficient. 4. IDENTIFY THE GAPS",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-52",
            "slideNumber": 52,
            "title": "Once the gaps are identified, the clinic",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Compliance Gap Analysis & Regulatory Case Study",
            "lead": "03/15 Once the gaps are identified, the clinic develops a plan to address them. This",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Once the gaps are identified, the clinic</h3><p class=\"lead-statement\">Once the gaps are identified, the clinic develops a plan to address them. This</p><div class=\"info-card mt-3\"><p>might include updating policies, implementing encryption protocols, providing staff training, and enhancing security measures. 5. DEVELOP A REMEDIATION PLAN</p></div>",
            "cleanText": "03/15 Once the gaps are identified, the clinic develops a plan to address them. This might include updating policies, implementing encryption protocols, providing staff training, and enhancing security measures. 5. DEVELOP A REMEDIATION PLAN",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-53",
            "slideNumber": 53,
            "title": "KEY COMPONENT OF CGA",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Compliance Gap Analysis & Regulatory Case Study",
            "lead": "10/15 KEY COMPONENT OF CGA - Scope Definition: Clearly defining the regulations, standards,",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>KEY COMPONENT OF CGA</h3><p class=\"lead-statement\">KEY COMPONENT OF CGA and business processes to be included in the analysis.</p><div class=\"info-card mt-3\"><p>organization&#x27;s current practices and procedures. Information Assurance and Security 2 requirements of the relevant regulations and standards.</p></div><ul class=\"compact mt-3\"><li>Scope Definition: Clearly defining the regulations, standards,</li><li>Current State Assessment: Evaluating the</li><li>Desired State Definition: Clearly outlining the</li></ul>",
            "cleanText": "10/15 KEY COMPONENT OF CGA - Scope Definition: Clearly defining the regulations, standards, and business processes to be included in the analysis. - Current State Assessment: Evaluating the organization's current practices and procedures. Information Assurance and Security 2 - Desired State Definition: Clearly outlining the requirements of the relevant regulations and standards.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-54",
            "slideNumber": 54,
            "title": "KEY COMPONENT OF CGA",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Compliance Gap Analysis & Regulatory Case Study",
            "lead": "10/15 KEY COMPONENT OF CGA - Gap Identification: Pinpointing the discrepancies between",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>KEY COMPONENT OF CGA</h3><p class=\"lead-statement\">KEY COMPONENT OF CGA the current and desired states.</p><div class=\"info-card mt-3\"><p>exist. Information Assurance and Security 2 the identified gaps and achieve compliance.</p></div><ul class=\"compact mt-3\"><li>Gap Identification: Pinpointing the discrepancies between</li><li>Root Cause Analysis: Understanding why the gaps</li><li>Remediation Planning: Developing a plan to address</li></ul>",
            "cleanText": "10/15 KEY COMPONENT OF CGA - Gap Identification: Pinpointing the discrepancies between the current and desired states. - Root Cause Analysis: Understanding why the gaps exist. Information Assurance and Security 2 - Remediation Planning: Developing a plan to address the identified gaps and achieve compliance.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-55",
            "slideNumber": 55,
            "title": "By conducting a thorough compliance gap",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Compliance Gap Analysis & Regulatory Case Study",
            "lead": "15/15 By conducting a thorough compliance gap analysis, organizations can proactively identify and",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>By conducting a thorough compliance gap</h3><p class=\"lead-statement\">By conducting a thorough compliance gap analysis, organizations can proactively identify and</p><div class=\"info-card mt-3\"><p>address potential compliance issues, minimizing risks and ensuring they meet their regulatory obligations, according to compliance experts.</p></div>",
            "cleanText": "15/15 By conducting a thorough compliance gap analysis, organizations can proactively identify and address potential compliance issues, minimizing risks and ensuring they meet their regulatory obligations, according to compliance experts.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-56",
            "slideNumber": 56,
            "title": "Foundations of Advanced Security - Slide 56",
            "eyebrow": "CIT 220 • Unit 01",
            "subtitle": "Compliance Gap Analysis & Regulatory Case Study",
            "lead": "Key conceptual lecture material.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<div class=\"intro-author-card\"><div class=\"institution-badge\"><span>West Visayas State University • CICT Main Campus, Iloilo City</span></div><h2>Thank You!</h2><p class=\"intro-tagline\">CIT 220 Information Assurance and Security 2 • Unit 01 Complete</p><p class=\"mt-4 text-xs text-slate-500 dark:text-slate-400\">Curriculum instruction by Prof. Chin Ann Feliprada • WVSU CICT</p></div>",
            "cleanText": "Foundations of Advanced Security - Slide 56",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    }
  ]
};
