import { Topic } from '../../../types/content';

export const TOPIC_02_1: Topic = {
  "id": "cit220-unit-02-zta",
  "slug": "02-1-zero-trust-architecture",
  "topicNumber": "02.1",
  "title": "Zero Trust Architecture (ZTA)",
  "subtitle": "From Castle-and-Moat to 'Never Trust, Always Verify' & The 5 Pillars of Defense",
  "description": "Comprehensive exploration of Zero Trust: perimeter obsolescence, NIST SP 800-207 tenets, the 5 architectural pillars, continuous behavioral telemetry, and lessons from high-profile breaches.",
  "author": "Chin Ann Feliprada",
  "originalPath": "cit220_02_1_zero_trust_architecture",
  "badge": "Zero Trust",
  "tags": ["Zero Trust", "ZTA", "NIST SP 800-207", "Microsegmentation", "Assume Breach", "Least Privilege", "SolarWinds", "MS Exchange"],
  "totalSlides": 39,
  "sections": [
    {
      "id": "legacy-perimeter",
      "title": "The Legacy Perimeter & The Castle-and-Moat Breakdown",
      "eyebrow": "Perimeter Evolution",
      "summary": "Why traditional perimeter firewalls fail in modern hybrid, cloud, and remote work environments.",
      "slides": [
          {
            "id": "slide-1",
            "slideNumber": 1,
            "title": "UNIT 2: Advanced Network",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Legacy Perimeter & The Castle-and-Moat Breakdown",
            "lead": "✓ UNIT 2: Advanced Network and System Security",
            "byline": "Prof. Chin Ann Feliprada • WVSU CICT Main Campus, Iloilo City",
            "isTitleSlide": true,
            "isSectionDivider": false,
            "rawHtml": "<div class=\"intro-author-card\"><div class=\"institution-badge\"><span>West Visayas State University • CICT Main Campus, Iloilo City</span></div><h2>Zero Trust Architecture (ZTA)</h2><p class=\"intro-tagline\">CIT 220 Information Assurance and Security 2 • Unit 02.1</p><p class=\"mt-4 text-xs text-slate-500 dark:text-slate-400\">Course Instructor: Prof. Chin Ann Feliprada</p></div>",
            "cleanText": "✓ UNIT 2: Advanced Network and System Security 2.1   Zero Trust Architecture & Perimeter Defense From \"trust but verify\" to \"never trust, always verify\" -- a practical guide with real-world scenarios for every concept.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-2",
            "slideNumber": 2,
            "title": "ROADMAP: What We'll Cover",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Legacy Perimeter & The Castle-and-Moat Breakdown",
            "lead": "ROADMAP What We'll Cover 01",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>ROADMAP: What We&#x27;ll Cover</h3><p class=\"lead-statement\">What We&#x27;ll Cover 01</p><div class=\"info-card mt-3\"><p>The Perimeter Model Castle-and-moat security and why it once worked 02 Why Perimeters Fail Cloud, remote work, and the vanishing network edge 03 Zero Trust Fundamentals Definition and the four core principles 04 The Five Pillars Identity, devices, network, apps, and data 05 Monitoring &amp; Analytics Continuous verification in action 06 Zero Trust vs. Perimeter A side-by-side comparison 07 Implementation Roadmap A phased path to adoption 08 Pitfalls &amp; Takeaways Common mistakes and how to avoid them 02 / 20</p></div>",
            "cleanText": "ROADMAP What We'll Cover 01 The Perimeter Model Castle-and-moat security and why it once worked 02 Why Perimeters Fail Cloud, remote work, and the vanishing network edge 03 Zero Trust Fundamentals Definition and the four core principles 04 The Five Pillars Identity, devices, network, apps, and data 05 Monitoring & Analytics Continuous verification in action 06 Zero Trust vs. Perimeter A side-by-side comparison 07 Implementation Roadmap A phased path to adoption 08 Pitfalls & Takeaways Common mistakes and how to avoid them 02 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-3",
            "slideNumber": 3,
            "title": "THE LEGACY MODEL",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Legacy Perimeter & The Castle-and-Moat Breakdown",
            "lead": "THE LEGACY MODEL Perimeter Defense: The Castle-and-Moat Trusted",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>THE LEGACY MODEL</h3><p class=\"lead-statement\">Perimeter Defense: The Castle-and-Moat Trusted</p><div class=\"info-card mt-3\"><p>Internal LAN INTERNET FIREWALL DMZ The old assumption: everything inside the network edge is safe. &quot;trust anyone inside the network&quot; A hardened outer boundary (firewalls, VPNs, gateways) separates &quot;trusted&quot; internal traffic from the &quot;untrusted&quot; internet. Once authenticated at the edge, users and devices are broadly trusted to roam the internal network. Security investment concentrates on keeping attackers out -- not on limiting what happens if they get in. 03 / 20</p></div>",
            "cleanText": "THE LEGACY MODEL Perimeter Defense: The Castle-and-Moat Trusted Internal LAN INTERNET FIREWALL DMZ The old assumption: everything inside the network edge is safe. \"trust anyone inside the network\" A hardened outer boundary (firewalls, VPNs, gateways) separates \"trusted\" internal traffic from the \"untrusted\" internet. Once authenticated at the edge, users and devices are broadly trusted to roam the internal network. Security investment concentrates on keeping attackers out -- not on limiting what happens if they get in. 03 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-4",
            "slideNumber": 4,
            "title": "THE LEGACY MODEL",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Legacy Perimeter & The Castle-and-Moat Breakdown",
            "lead": "THE LEGACY MODEL Perimeter Defense: The Castle-and-Moat Trusted",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>THE LEGACY MODEL</h3><p class=\"lead-statement\">Perimeter Defense: The Castle-and-Moat Trusted</p><div class=\"info-card mt-3\"><p>Internal LAN INTERNET FIREWALL DMZ EXAMPLE SCENARIO A retail chain protects its data center with a next-gen firewall and requires VPN login for remote staff. An attacker steals a store manager&#x27;s VPN credentials via phishing. Once connected, the VPN treats them as fully trusted freely, because the network has no internal checkpoints. 03 / 20</p></div><ul class=\"compact mt-3\"><li>they browse file shares and POS systems</li></ul>",
            "cleanText": "THE LEGACY MODEL Perimeter Defense: The Castle-and-Moat Trusted Internal LAN INTERNET FIREWALL DMZ EXAMPLE SCENARIO A retail chain protects its data center with a next-gen firewall and requires VPN login for remote staff. An attacker steals a store manager's VPN credentials via phishing. Once connected, the VPN treats them as fully trusted -- they browse file shares and POS systems freely, because the network has no internal checkpoints. 03 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-5",
            "slideNumber": 5,
            "title": "THE PROBLEM: Why the Perimeter Is Disappearing",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Legacy Perimeter & The Castle-and-Moat Breakdown",
            "lead": "THE PROBLEM Why the Perimeter Is Disappearing ☁",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>THE PROBLEM: Why the Perimeter Is Disappearing</h3><p class=\"lead-statement\">Why the Perimeter Is Disappearing ☁</p><div class=\"info-card mt-3\"><p>Cloud &amp; SaaS Data and apps now live outside any single network boundary you control. ⌂ Remote Work Employees connect from home Wi-Fi, cafes, and airports -- not the office LAN. ⌘ BYOD &amp; Mobile Personal phones and laptops access corporate resources from everywhere. ⚠ Insider Risk Compromised or malicious insiders start out already &quot;inside&quot; the moat. EXAMPLE SCENARIO A logistics company migrates its scheduling system to a cloud SaaS platform and lets employees use personal laptops while working from home. There is no longer a single network edge to defend -- users, devices, and data are scattered across the internet. When an employee&#x27;s home router is compromised, the attacker reaches corporate cloud data directly, with no perimeter firewall ever in the path. 04 / 20</p></div>",
            "cleanText": "THE PROBLEM Why the Perimeter Is Disappearing ☁ Cloud & SaaS Data and apps now live outside any single network boundary you control. ⌂ Remote Work Employees connect from home Wi-Fi, cafes, and airports -- not the office LAN. ⌘ BYOD & Mobile Personal phones and laptops access corporate resources from everywhere. ⚠ Insider Risk Compromised or malicious insiders start out already \"inside\" the moat. EXAMPLE SCENARIO A logistics company migrates its scheduling system to a cloud SaaS platform and lets employees use personal laptops while working from home. There is no longer a single network edge to defend -- users, devices, and data are scattered across the internet. When an employee's home router is compromised, the attacker reaches corporate cloud data directly, with no perimeter firewall ever in the path. 04 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-6",
            "slideNumber": 6,
            "title": "THE NEW MODEL",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Legacy Perimeter & The Castle-and-Moat Breakdown",
            "lead": "THE NEW MODEL What Is Zero Trust Architecture? \"Never trust, always verify.\"",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>THE NEW MODEL</h3><p class=\"lead-statement\">What Is Zero Trust Architecture? &quot;Never trust, always verify.&quot;</p><div class=\"info-card mt-3\"><p>Zero Trust Architecture (ZTA) is a security model that assumes no user, device, or network segment -- inside or outside the organization -- should be trusted by default. Every request for access must be authenticated, authorized, and continuously validated. 05 / 20 Originated in 2011  with John Kindervag (former Forrester analyst)- he wrote the foundational Zero Trust papers. ✔ ZTA is a SECURITY STRATEGY , NOT A PRODUCT - eliminates the assumption of trust within a network ✔ ZTS (Zero Trust Security) -an IT model that demands strict identity checks for every person and device accessing a private network ✔ ZTNA (Zero Trust Network Access) - core technology linked to ZTA</p></div>",
            "cleanText": "THE NEW MODEL What Is Zero Trust Architecture? \"Never trust, always verify.\" Zero Trust Architecture (ZTA) is a security model that assumes no user, device, or network segment -- inside or outside the organization -- should be trusted by default. Every request for access must be authenticated, authorized, and continuously validated. 05 / 20 Originated in 2011  with John Kindervag (former Forrester analyst)- he wrote the foundational Zero Trust papers. ✔ ZTA is a SECURITY STRATEGY , NOT A PRODUCT - eliminates the assumption of trust within a network ✔ ZTS (Zero Trust Security) -an IT model that demands strict identity checks for every person and device accessing a private network ✔ ZTNA (Zero Trust Network Access) - core technology linked to ZTA",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-7",
            "slideNumber": 7,
            "title": "Why shift to Zero",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Legacy Perimeter & The Castle-and-Moat Breakdown",
            "lead": "Why shift to Zero Trust Architecture?",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Why shift to Zero</h3><p class=\"lead-statement\">Trust Architecture?</p><div class=\"info-card mt-3\"><p>prioritize verification at every step ensuring users and devices are checked continuously detect and respond to potential threats in real time How does ZT A works?</p></div>",
            "cleanText": "Why shift to Zero Trust Architecture? prioritize verification at every step ensuring users and devices are checked continuously detect and respond to potential threats in real time How does ZT A works?",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-8",
            "slideNumber": 8,
            "title": "THE NEW MODEL",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Legacy Perimeter & The Castle-and-Moat Breakdown",
            "lead": "THE NEW MODEL What Is Zero Trust Architecture? 05 / 20",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>THE NEW MODEL</h3><p class=\"lead-statement\">What Is Zero Trust Architecture? 05 / 20</p><div class=\"info-card mt-3\"><p>EXAMPLE SCENARIO An engineer at a software company requests access to the production database from the office. Even though she is on the corporate network, Zero Trust still verifies her identity with MFA, checks that her laptop meets security policy, confirms she is a member of the database-access group, and grants only read access to the specific schema she needs 1 Identity verified → 2 Device checked → 3 Context evaluated → 4 Least-priv. access granted Verification happens for every single request -- not once at the door.</p></div><ul class=\"compact mt-3\"><li>re-checking all of this on her next request.</li></ul>",
            "cleanText": "THE NEW MODEL What Is Zero Trust Architecture? 05 / 20 EXAMPLE SCENARIO An engineer at a software company requests access to the production database from the office. Even though she is on the corporate network, Zero Trust still verifies her identity with MFA, checks that her laptop meets security policy, confirms she is a member of the database-access group, and grants only read access to the specific schema she needs -- re-checking all of this on her next request. 1 Identity verified → 2 Device checked → 3 Context evaluated → 4 Least-priv. access granted Verification happens for every single request -- not once at the door.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "core-principles",
      "title": "Core Principles of Zero Trust (NIST SP 800-207)",
      "eyebrow": "NIST Tenets",
      "summary": "Never Trust, Always Verify; Least-Privilege Access; Assume Breach; and Microsegmentation.",
      "slides": [
          {
            "id": "slide-9",
            "slideNumber": 9,
            "title": "Comparing Zero Trust Arcitecture (ZT A) &",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Core Principles of Zero Trust (NIST SP 800-207)",
            "lead": "Comparing Zero Trust Arcitecture (ZT A) & Perimeter defense (castle-and-moat model(Traditional Security) 05 / 20",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Comparing Zero Trust Arcitecture (ZT A) &amp;</h3><p class=\"lead-statement\">Perimeter defense (castle-and-moat model(Traditional Security) 05 / 20</p><div class=\"info-card mt-3\"><p>Zero Trust Architecture &quot;trust no one&quot; by default Castle-and-moat model &quot;trust anyone inside the network&quot;</p></div>",
            "cleanText": "Comparing Zero Trust Arcitecture (ZT A) & Perimeter defense (castle-and-moat model(Traditional Security) 05 / 20 Zero Trust Architecture \"trust no one\" by default Castle-and-moat model \"trust anyone inside the network\"",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-10",
            "slideNumber": 10,
            "title": "Benefits of ZTA",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Core Principles of Zero Trust (NIST SP 800-207)",
            "lead": "Benefits of ZTA 05 / 20 Better Security and Less Damage",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Benefits of ZTA</h3><p class=\"lead-statement\">05 / 20 Better Security and Less Damage</p><div class=\"info-card mt-3\"><p>Flexibility for Modern Work Control and Compliance ✓ ✓ ✓</p></div><ul class=\"compact mt-3\"><li>No lateral movement: Blocks hackers from moving around even if they break into one device.</li><li>Least privilege: Gives users access only to the exact tools they need for their jobs.</li><li>Continuous checks: Keeps checking user identity and device safety during the entire session.</li><li>Safe remote work: Protects company data when staff log in from home or public Wi-Fi.</li><li>Cloud ready: Secures apps and files moved to cloud servers without needing old VPN setups.</li><li>Device freedom: Allows personal phones and laptops (BYOD) to connect safely after passing checks.</li><li>Deep visibility: Tracks all network traffic and spots weird user behavior fast.</li><li>Easy rules: Simplifies security laws and helps meet standards like GDPR or HIPAA. [1]</li></ul>",
            "cleanText": "Benefits of ZTA 05 / 20 Better Security and Less Damage -No lateral movement: Blocks hackers from moving around even if they break into one device. -Least privilege: Gives users access only to the exact tools they need for their jobs. -Continuous checks: Keeps checking user identity and device safety during the entire session. Flexibility for Modern Work -Safe remote work: Protects company data when staff log in from home or public Wi-Fi. -Cloud ready: Secures apps and files moved to cloud servers without needing old VPN setups. -Device freedom: Allows personal phones and laptops (BYOD) to connect safely after passing checks. Control and Compliance -Deep visibility: Tracks all network traffic and spots weird user behavior fast. -Easy rules: Simplifies security laws and helps meet standards like GDPR or HIPAA. [1] ✓ ✓ ✓",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-11",
            "slideNumber": 11,
            "title": "Four Core Principles of ZTA",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Core Principles of Zero Trust (NIST SP 800-207)",
            "lead": "Four Core Principles of ZTA 01 Never Trust, Always Verify 02 Least-Privilege Access",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Four Core Principles of ZTA</h3><p class=\"lead-statement\">01 Never Trust, Always Verify 02 Least-Privilege Access</p><div class=\"info-card mt-3\"><p>03 Assume Breach 2 04 Microsegmentation Dividing the network into isolated segments with individual security controls Granting minimal access based on the user&#x27;s role. Ongoing validation of users and devices throughout a session.</p></div>",
            "cleanText": "Four Core Principles of ZTA 01 Never Trust, Always Verify 02 Least-Privilege Access 03 Assume Breach 2 04 Microsegmentation Dividing the network into isolated segments with individual security controls Granting minimal access based on the user's role. Ongoing validation of users and devices throughout a session.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-12",
            "slideNumber": 12,
            "title": "CORE PRINCIPLE 01",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Core Principles of Zero Trust (NIST SP 800-207)",
            "lead": "CORE PRINCIPLE 01 Never Trust, Always Verify ?",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>CORE PRINCIPLE 01</h3><p class=\"lead-statement\">Never Trust, Always Verify ?</p><div class=\"info-card mt-3\"><p>No implicit trust is granted based on network location, ownership, or prior access. Every user and device must prove who they are -- every time. ✓ Strong identity proof (MFA, not just passwords) ✓ Device health &amp; compliance checked at request time ✓ Access re-validated continuously, not just at login EVERY REQUEST, RE-VERIFIED 1 Who is asking? 2 What device? 3 What resource? 4 What context (time, location, risk)? 5 Is this the minimum needed? If the answer to any check changes, access changes with it -- in real time. 06 / 20</p></div>",
            "cleanText": "CORE PRINCIPLE 01 Never Trust, Always Verify ? No implicit trust is granted based on network location, ownership, or prior access. Every user and device must prove who they are -- every time. ✓ Strong identity proof (MFA, not just passwords) ✓ Device health & compliance checked at request time ✓ Access re-validated continuously, not just at login EVERY REQUEST, RE-VERIFIED 1 Who is asking? 2 What device? 3 What resource? 4 What context (time, location, risk)? 5 Is this the minimum needed? If the answer to any check changes, access changes with it -- in real time. 06 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-13",
            "slideNumber": 13,
            "title": "CORE PRINCIPLE 01",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Core Principles of Zero Trust (NIST SP 800-207)",
            "lead": "CORE PRINCIPLE 01 Never Trust, Always Verify EXAMPLE SCENARIO",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>CORE PRINCIPLE 01</h3><p class=\"lead-statement\">Never Trust, Always Verify EXAMPLE SCENARIO</p><div class=\"info-card mt-3\"><p>A finance director logs into the payroll portal every morning from the same office desk. Zero Trust still requires her MFA token each session, and if she suddenly tries to access the system from an unfamiliar country at 3 a.m., the system challenges her again and flags the session for review -- regardless of her seniority or past behavior. EVERY REQUEST, RE-VERIFIED 1 Who is asking? 2 What device? 3 What resource? 4 What context (time, location, risk)? 5 Is this the minimum needed? If the answer to any check changes, access changes with it -- in real time. 06 / 20</p></div>",
            "cleanText": "CORE PRINCIPLE 01 Never Trust, Always Verify EXAMPLE SCENARIO A finance director logs into the payroll portal every morning from the same office desk. Zero Trust still requires her MFA token each session, and if she suddenly tries to access the system from an unfamiliar country at 3 a.m., the system challenges her again and flags the session for review -- regardless of her seniority or past behavior. EVERY REQUEST, RE-VERIFIED 1 Who is asking? 2 What device? 3 What resource? 4 What context (time, location, risk)? 5 Is this the minimum needed? If the answer to any check changes, access changes with it -- in real time. 06 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-14",
            "slideNumber": 14,
            "title": "CORE PRINCIPLE 02",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Core Principles of Zero Trust (NIST SP 800-207)",
            "lead": "CORE PRINCIPLE 02 Least-Privilege Access MINIMUM",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>CORE PRINCIPLE 02</h3><p class=\"lead-statement\">Least-Privilege Access MINIMUM</p><div class=\"info-card mt-3\"><p>Just enough access, just in time. Users, apps, and services get only the permissions required for their specific task -- nothing broader, and often only for a limited time window. Broad access &quot;All employees can read the entire shared drive, including HR and finance folders, in case they ever need to.&quot; Least privilege &quot;Each employee sees only their own team&#x27;s folder; HR data is granted per-request, per-case, and expires automatically.&quot; 07 / 20</p></div>",
            "cleanText": "CORE PRINCIPLE 02 Least-Privilege Access MINIMUM Just enough access, just in time. Users, apps, and services get only the permissions required for their specific task -- nothing broader, and often only for a limited time window. Broad access \"All employees can read the entire shared drive, including HR and finance folders, in case they ever need to.\" Least privilege \"Each employee sees only their own team's folder; HR data is granted per-request, per-case, and expires automatically.\" 07 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-15",
            "slideNumber": 15,
            "title": "CORE PRINCIPLE 02",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Core Principles of Zero Trust (NIST SP 800-207)",
            "lead": "CORE PRINCIPLE 02 Least-Privilege Access MINIMUM",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>CORE PRINCIPLE 02</h3><p class=\"lead-statement\">Least-Privilege Access MINIMUM</p><div class=\"info-card mt-3\"><p>Just enough access, just in time. Users, apps, and services get only the permissions required for their specific task -- nothing broader, and often only for a limited time window. EXAMPLE SCENARIO A third-party contractor is hired to fix one bug in a billing microservice. Under least privilege, the access system grants a scoped, time-boxed credential to just that service&#x27;s staging environment for 48 hours -- not the full production network. When the contract ends, access expires automatically instead of lingering as an unused, exploitable account. 07 / 20</p></div>",
            "cleanText": "CORE PRINCIPLE 02 Least-Privilege Access MINIMUM Just enough access, just in time. Users, apps, and services get only the permissions required for their specific task -- nothing broader, and often only for a limited time window. EXAMPLE SCENARIO A third-party contractor is hired to fix one bug in a billing microservice. Under least privilege, the access system grants a scoped, time-boxed credential to just that service's staging environment for 48 hours -- not the full production network. When the contract ends, access expires automatically instead of lingering as an unused, exploitable account. 07 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-16",
            "slideNumber": 16,
            "title": "CORE PRINCIPLE 03",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Core Principles of Zero Trust (NIST SP 800-207)",
            "lead": "CORE PRINCIPLE 03 Assume Breach Design as if an attacker is already inside -- because eventually,",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>CORE PRINCIPLE 03</h3><p class=\"lead-statement\">Assume Breach Design as if an attacker is already inside -- because eventually,</p><div class=\"info-card mt-3\"><p>one will be. 1 Limit blast radius Segment systems so a single compromised account can&#x27;t reach everything. 2 Encrypt everywhere Protect data in transit and at rest so intercepted traffic is useless. 3 Watch for lateral movement Monitor internal traffic patterns, not just the network edge. 08 / 20</p></div>",
            "cleanText": "CORE PRINCIPLE 03 Assume Breach Design as if an attacker is already inside -- because eventually, one will be. 1 Limit blast radius Segment systems so a single compromised account can't reach everything. 2 Encrypt everywhere Protect data in transit and at rest so intercepted traffic is useless. 3 Watch for lateral movement Monitor internal traffic patterns, not just the network edge. 08 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-17",
            "slideNumber": 17,
            "title": "CORE PRINCIPLE 03",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Core Principles of Zero Trust (NIST SP 800-207)",
            "lead": "CORE PRINCIPLE 03 Assume Breach Design as if an attacker is already inside -- because eventually, one will be.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>CORE PRINCIPLE 03</h3><p class=\"lead-statement\">Assume Breach Design as if an attacker is already inside -- because eventually, one will be.</p><div class=\"info-card mt-3\"><p>EXAMPLE SCENARIO A hospital IT team designs its network assuming ransomware will eventually land on a workstation. When it does, encrypted backups, segmented clinical systems, and blast-radius limits mean the infection is contained to one department instead of shutting down every ICU device in the building. BLAST-RADIUS CONTAINMENT Zone A Compromised -- isolated Zone B Unaffected Zone C Unaffected Zone D Unaffected 08 / 20</p></div>",
            "cleanText": "CORE PRINCIPLE 03 Assume Breach Design as if an attacker is already inside -- because eventually, one will be. EXAMPLE SCENARIO A hospital IT team designs its network assuming ransomware will eventually land on a workstation. When it does, encrypted backups, segmented clinical systems, and blast-radius limits mean the infection is contained to one department instead of shutting down every ICU device in the building. BLAST-RADIUS CONTAINMENT Zone A Compromised -- isolated Zone B Unaffected Zone C Unaffected Zone D Unaffected 08 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-18",
            "slideNumber": 18,
            "title": "CORE PRINCIPLE 04",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Core Principles of Zero Trust (NIST SP 800-207)",
            "lead": "CORE PRINCIPLE 04 Microsegmentation Instead of one flat internal network, Zero Trust",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>CORE PRINCIPLE 04</h3><p class=\"lead-statement\">Microsegmentation Instead of one flat internal network, Zero Trust</p><div class=\"info-card mt-3\"><p>divides infrastructure into small, isolated zones -- each with its own access controls. Contains attackers to a single segment Enforces policy between workloads, not just at the edge Makes lateral movement visible and blockable 09 / 20</p></div>",
            "cleanText": "CORE PRINCIPLE 04 Microsegmentation Instead of one flat internal network, Zero Trust divides infrastructure into small, isolated zones -- each with its own access controls. Contains attackers to a single segment Enforces policy between workloads, not just at the edge Makes lateral movement visible and blockable 09 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-19",
            "slideNumber": 19,
            "title": "CORE PRINCIPLE 04",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Core Principles of Zero Trust (NIST SP 800-207)",
            "lead": "CORE PRINCIPLE 04 Microsegmentation EXAMPLE SCENARIO",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>CORE PRINCIPLE 04</h3><p class=\"lead-statement\">Microsegmentation EXAMPLE SCENARIO</p><div class=\"info-card mt-3\"><p>A bank segments its network so the customer-facing web app, the payments processing service, and the internal HR system each sit in isolated segments with explicit allow-listed connections. When a web server is compromised via a bug, the attacker cannot reach the payments segment at all -- the segment boundary simply refuses the connection. Web Tier Payments Service HR System Analytics Workload 🔒 Each tile is its own enforcement boundary unless explicitly allowed. 09 / 20</p></div><ul class=\"compact mt-3\"><li>traffic between tiles is default-deny</li></ul>",
            "cleanText": "CORE PRINCIPLE 04 Microsegmentation EXAMPLE SCENARIO A bank segments its network so the customer-facing web app, the payments processing service, and the internal HR system each sit in isolated segments with explicit allow-listed connections. When a web server is compromised via a bug, the attacker cannot reach the payments segment at all -- the segment boundary simply refuses the connection. Web Tier Payments Service HR System Analytics Workload 🔒 Each tile is its own enforcement boundary -- traffic between tiles is default-deny unless explicitly allowed. 09 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "five-pillars",
      "title": "The Five Pillars of Zero Trust Architecture",
      "eyebrow": "ZTA Pillars",
      "summary": "Identity & Access Management, Device Trust & Posture, Network Segmentation, Application & Workload Security, and Data Encryption.",
      "slides": [
          {
            "id": "slide-20",
            "slideNumber": 20,
            "title": "The Five Pillars of ZTA",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Five Pillars of Zero Trust Architecture",
            "lead": "The Five Pillars of ZTA 01 Identity & Access Management 02 Device Trust & Posture",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>The Five Pillars of ZTA</h3><p class=\"lead-statement\">01 Identity &amp; Access Management 02 Device Trust &amp; Posture</p><div class=\"info-card mt-3\"><p>03 Network Segmentation 2 04 Application &amp; Workload Security 05 Data Security &amp; Encryption</p></div>",
            "cleanText": "The Five Pillars of ZTA 01 Identity & Access Management 02 Device Trust & Posture 03 Network Segmentation 2 04 Application & Workload Security 05 Data Security & Encryption",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-21",
            "slideNumber": 21,
            "title": "PILLAR 1 OF 5",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Five Pillars of Zero Trust Architecture",
            "lead": "PILLAR 1 OF 5 Identity & Access Management ⌘",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>PILLAR 1 OF 5</h3><p class=\"lead-statement\">Identity &amp; Access Management ⌘</p><div class=\"info-card mt-3\"><p>Identity is the new perimeter. Strong, continuously-verified identity -- for people, services, and devices -- is the foundation every other Zero Trust control builds on.✓ Multi-factor authentication (MFA) on every login ✓ Single sign-on (SSO) with centralized policy ✓ Risk-based / adaptive authentication ✓ Just-in-time privilege elevation 10 / 20 ✓</p></div>",
            "cleanText": "PILLAR 1 OF 5 Identity & Access Management ⌘ Identity is the new perimeter. Strong, continuously-verified identity -- for people, services, and devices -- is the foundation every other Zero Trust control builds on.✓ Multi-factor authentication (MFA) on every login ✓ Single sign-on (SSO) with centralized policy ✓ Risk-based / adaptive authentication ✓ Just-in-time privilege elevation 10 / 20 ✓",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-22",
            "slideNumber": 22,
            "title": "PILLAR 1 OF 5",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Five Pillars of Zero Trust Architecture",
            "lead": "PILLAR 1 OF 5 Identity & Access Management EXAMPLE SCENARIO",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>PILLAR 1 OF 5</h3><p class=\"lead-statement\">Identity &amp; Access Management EXAMPLE SCENARIO</p><div class=\"info-card mt-3\"><p>An attacker phishes a valid password from a sales employee. Because MFA is enforced, the login still fails without a second factor from the employee&#x27;s registered phone -- the stolen password alone is worthless, and the failed attempt triggers a security alert. LOGIN, STEP BY STEP 1 Enter username + password 2 Push notification to registered device 3 Device posture check (patched, encrypted) 4 Risk score evaluated (location, time, behavior) 5 Access token issued -- scoped &amp; time-limited 10 / 20</p></div>",
            "cleanText": "PILLAR 1 OF 5 Identity & Access Management EXAMPLE SCENARIO An attacker phishes a valid password from a sales employee. Because MFA is enforced, the login still fails without a second factor from the employee's registered phone -- the stolen password alone is worthless, and the failed attempt triggers a security alert. LOGIN, STEP BY STEP 1 Enter username + password 2 Push notification to registered device 3 Device posture check (patched, encrypted) 4 Risk score evaluated (location, time, behavior) 5 Access token issued -- scoped & time-limited 10 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-23",
            "slideNumber": 23,
            "title": "PILLAR 2 OF 5",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Five Pillars of Zero Trust Architecture",
            "lead": "PILLAR 2 OF 5 Device Trust & Posture A valid user on a compromised, unpatched, or unmanaged device is still a risk. Zero Trust",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>PILLAR 2 OF 5</h3><p class=\"lead-statement\">Device Trust &amp; Posture A valid user on a compromised, unpatched, or unmanaged device is still a risk. Zero Trust</p><div class=\"info-card mt-3\"><p>evaluates the device on every request, not just the human. ✓ Managed &amp; Patched Corporate laptops with current OS and security patches ⚠ Compliant Configuration Disk encryption, screen lock, and endpoint protection enabled ✗ Unknown / BYOD Unmanaged personal devices get restricted or blocked access 11 / 20</p></div>",
            "cleanText": "PILLAR 2 OF 5 Device Trust & Posture A valid user on a compromised, unpatched, or unmanaged device is still a risk. Zero Trust evaluates the device on every request, not just the human. ✓ Managed & Patched Corporate laptops with current OS and security patches ⚠ Compliant Configuration Disk encryption, screen lock, and endpoint protection enabled ✗ Unknown / BYOD Unmanaged personal devices get restricted or blocked access 11 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-24",
            "slideNumber": 24,
            "title": "PILLAR 2 OF 5",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Five Pillars of Zero Trust Architecture",
            "lead": "PILLAR 2 OF 5 Device Trust & Posture EXAMPLE SCENARIO",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>PILLAR 2 OF 5</h3><p class=\"lead-statement\">Device Trust &amp; Posture EXAMPLE SCENARIO</p><div class=\"info-card mt-3\"><p>An employee tries to open the internal wiki from a personal tablet that has never been enrolled in device management. Zero Trust device posture checks can&#x27;t verify its encryption or patch status, so the policy engine allows only a read-only, browser-based view of non-sensitive pages -- full access is denied until the device is enrolled or she switches to her managed laptop. 11 / 20</p></div>",
            "cleanText": "PILLAR 2 OF 5 Device Trust & Posture EXAMPLE SCENARIO An employee tries to open the internal wiki from a personal tablet that has never been enrolled in device management. Zero Trust device posture checks can't verify its encryption or patch status, so the policy engine allows only a read-only, browser-based view of non-sensitive pages -- full access is denied until the device is enrolled or she switches to her managed laptop. 11 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-25",
            "slideNumber": 25,
            "title": "PILLAR 3 OF 5",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Five Pillars of Zero Trust Architecture",
            "lead": "PILLAR 3 OF 5 Network Segmentation Software-defined perimeters and micro-segments replace the flat",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>PILLAR 3 OF 5</h3><p class=\"lead-statement\">Network Segmentation Software-defined perimeters and micro-segments replace the flat</p><div class=\"info-card mt-3\"><p>internal network, enforcing policy between every workload -- not just at the internet edge. Software-Defined Perimeter (SDP) gateways East-west traffic inspection between servers Policy tied to workload identity, not IP address 12 / 20</p></div>",
            "cleanText": "PILLAR 3 OF 5 Network Segmentation Software-defined perimeters and micro-segments replace the flat internal network, enforcing policy between every workload -- not just at the internet edge. Software-Defined Perimeter (SDP) gateways East-west traffic inspection between servers Policy tied to workload identity, not IP address 12 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-26",
            "slideNumber": 26,
            "title": "PILLAR 3 OF 5",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Five Pillars of Zero Trust Architecture",
            "lead": "PILLAR 3 OF 5 Network Segmentation EXAMPLE SCENARIO",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>PILLAR 3 OF 5</h3><p class=\"lead-statement\">Network Segmentation EXAMPLE SCENARIO</p><div class=\"info-card mt-3\"><p>A hospital network isolates ICU medical devices, guest Wi-Fi, and administrative systems into separate segments with strict east-west policy. A ransomware infection introduced through a guest laptop cannot reach the medical device segment at all -- the segmentation policy drops the connection attempt before it ever reaches a ventilator or infusion pump. HOSPITAL NETWORK SEGMENTS Guest Wi-Fi Untrusted ✕ Admin Systems Restricted ✕ Clinical Apps Restricted ✕ ICU Devices Critical -- isolated ✕ 12 / 20</p></div>",
            "cleanText": "PILLAR 3 OF 5 Network Segmentation EXAMPLE SCENARIO A hospital network isolates ICU medical devices, guest Wi-Fi, and administrative systems into separate segments with strict east-west policy. A ransomware infection introduced through a guest laptop cannot reach the medical device segment at all -- the segmentation policy drops the connection attempt before it ever reaches a ventilator or infusion pump. HOSPITAL NETWORK SEGMENTS Guest Wi-Fi Untrusted ✕ Admin Systems Restricted ✕ Clinical Apps Restricted ✕ ICU Devices Critical -- isolated ✕ 12 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-27",
            "slideNumber": 27,
            "title": "PILLAR 4 OF 5",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Five Pillars of Zero Trust Architecture",
            "lead": "PILLAR 4 OF 5 Application & Workload Security ⚙",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>PILLAR 4 OF 5</h3><p class=\"lead-statement\">Application &amp; Workload Security ⚙</p><div class=\"info-card mt-3\"><p>Applications, APIs, and workloads authenticate to each other just like users do -- with their own verified identities, not implicit network trust. ✓ Mutual TLS (mTLS) between services ✓ API gateways enforce per-endpoint policy ✓ Workload identity replaces static IP allow-lists ✓ Runtime protection detects abnormal app behavior 13 / 20</p></div>",
            "cleanText": "PILLAR 4 OF 5 Application & Workload Security ⚙ Applications, APIs, and workloads authenticate to each other just like users do -- with their own verified identities, not implicit network trust. ✓ Mutual TLS (mTLS) between services ✓ API gateways enforce per-endpoint policy ✓ Workload identity replaces static IP allow-lists ✓ Runtime protection detects abnormal app behavior 13 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-28",
            "slideNumber": 28,
            "title": "PILLAR 4 OF 5",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Five Pillars of Zero Trust Architecture",
            "lead": "PILLAR 4 OF 5 Application & Workload Security EXAMPLE SCENARIO",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>PILLAR 4 OF 5</h3><p class=\"lead-statement\">Application &amp; Workload Security EXAMPLE SCENARIO</p><div class=\"info-card mt-3\"><p>An e-commerce platform&#x27;s recommendation microservice is compromised through a vulnerable open-source library. Because every internal API call requires mTLS authentication and is scoped to specific endpoints, the compromised service cannot call the payments API -- it was never issued a credential for that connection. SERVICE-TO-SERVICE POLICY Web Frontend  →  Recommendation Svc ALLOWED Recommendation Svc  →  Payments API DENIED Order Service  →  Payments API ALLOWED Recommendation Svc  →  User Database DENIED 13 / 20</p></div>",
            "cleanText": "PILLAR 4 OF 5 Application & Workload Security EXAMPLE SCENARIO An e-commerce platform's recommendation microservice is compromised through a vulnerable open-source library. Because every internal API call requires mTLS authentication and is scoped to specific endpoints, the compromised service cannot call the payments API -- it was never issued a credential for that connection. SERVICE-TO-SERVICE POLICY Web Frontend  →  Recommendation Svc ALLOWED Recommendation Svc  →  Payments API DENIED Order Service  →  Payments API ALLOWED Recommendation Svc  →  User Database DENIED 13 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-29",
            "slideNumber": 29,
            "title": "PILLAR 5 OF 5",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "The Five Pillars of Zero Trust Architecture",
            "lead": "PILLAR 5 OF 5 Data Security & Encryption Ultimately, Zero Trust protects data itself -- classifying, encrypting, and controlling it regardless of where it travels or who",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>PILLAR 5 OF 5</h3><p class=\"lead-statement\">Data Security &amp; Encryption Ultimately, Zero Trust protects data itself -- classifying, encrypting, and controlling it regardless of where it travels or who</p><div class=\"info-card mt-3\"><p>requests it. 01 Classify Tag data by sensitivity (public, internal, confidential, restricted) 02 Encrypt Protect data at rest and in transit, end to end 03 Control Apply data-loss-prevention (DLP) rules based on classification 04 Audit Log every access to sensitive data for forensic review EXAMPLE SCENARIO A departing employee copies a spreadsheet of customer records to a personal USB drive before their last day. Because the file is classified &quot;restricted&quot; and protected by a DLP policy, the encrypted document requires an active corporate identity token to open -- once their account is disabled at offboarding, the exfiltrated copy becomes unreadable. 14 / 20</p></div>",
            "cleanText": "PILLAR 5 OF 5 Data Security & Encryption Ultimately, Zero Trust protects data itself -- classifying, encrypting, and controlling it regardless of where it travels or who requests it. 01 Classify Tag data by sensitivity (public, internal, confidential, restricted) 02 Encrypt Protect data at rest and in transit, end to end 03 Control Apply data-loss-prevention (DLP) rules based on classification 04 Audit Log every access to sensitive data for forensic review EXAMPLE SCENARIO A departing employee copies a spreadsheet of customer records to a personal USB drive before their last day. Because the file is classified \"restricted\" and protected by a DLP policy, the encrypted document requires an active corporate identity token to open -- once their account is disabled at offboarding, the exfiltrated copy becomes unreadable. 14 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "continuous-monitoring",
      "title": "Continuous Monitoring, Analytics & Implementation",
      "eyebrow": "Operations & Roadmap",
      "summary": "Dynamic behavioral risk scoring, continuous telemetry evaluation, and phased enterprise migration roadmaps.",
      "slides": [
          {
            "id": "slide-30",
            "slideNumber": 30,
            "title": "MAKING IT WORK",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Continuous Monitoring, Analytics & Implementation",
            "lead": "MAKING IT WORK Continuous Monitoring & Analytics Zero Trust is not \"set and forget.\" Behavioral",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>MAKING IT WORK</h3><p class=\"lead-statement\">Continuous Monitoring &amp; Analytics Zero Trust is not &quot;set and forget.&quot; Behavioral</p><div class=\"info-card mt-3\"><p>analytics and telemetry continuously reassess risk, feeding every access decision in real time. SIEM aggregates logs across identity, device, and network UEBA flags behavior that deviates from a user&#x27;s norm Automated response can revoke access within seconds 15 / 20</p></div>",
            "cleanText": "MAKING IT WORK Continuous Monitoring & Analytics Zero Trust is not \"set and forget.\" Behavioral analytics and telemetry continuously reassess risk, feeding every access decision in real time. SIEM aggregates logs across identity, device, and network UEBA flags behavior that deviates from a user's norm Automated response can revoke access within seconds 15 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-31",
            "slideNumber": 31,
            "title": "MAKING IT WORK",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Continuous Monitoring, Analytics & Implementation",
            "lead": "MAKING IT WORK Continuous Monitoring & Analytics EXAMPLE SCENARIO",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>MAKING IT WORK</h3><p class=\"lead-statement\">Continuous Monitoring &amp; Analytics EXAMPLE SCENARIO</p><div class=\"info-card mt-3\"><p>A marketing account that normally logs in from one city suddenly authenticates successfully (with a stolen but valid password) from three different countries within an hour. The behavioral analytics engine flags the impossible-travel pattern, automatically suspends the session, and forces a re-verification -- stopping the account takeover before any data is accessed. RISK SIGNAL FEED Login -- New York, NY Normal Login -- Lagos, Nigeria (42 min later) Impossible travel Bulk file download initiated High risk Session auto-suspended Response triggered 15 / 20</p></div>",
            "cleanText": "MAKING IT WORK Continuous Monitoring & Analytics EXAMPLE SCENARIO A marketing account that normally logs in from one city suddenly authenticates successfully (with a stolen but valid password) from three different countries within an hour. The behavioral analytics engine flags the impossible-travel pattern, automatically suspends the session, and forces a re-verification -- stopping the account takeover before any data is accessed. RISK SIGNAL FEED Login -- New York, NY Normal Login -- Lagos, Nigeria (42 min later) Impossible travel Bulk file download initiated High risk Session auto-suspended Response triggered 15 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-32",
            "slideNumber": 32,
            "title": "SIDE BY SIDE",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Continuous Monitoring, Analytics & Implementation",
            "lead": "SIDE BY SIDE Zero Trust vs. Perimeter Defense PERIMETER DEFENSE ZERO TRUST",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>SIDE BY SIDE</h3><p class=\"lead-statement\">Zero Trust vs. Perimeter Defense PERIMETER DEFENSE ZERO TRUST</p><div class=\"info-card mt-3\"><p>Trust model Trusted inside, untrusted outside Never trust; verify every request Access scope Broad access once inside the network Least privilege, scoped per resource Verification One-time, at login or network entry Continuous, re-checked per request Breach impact Attacker can move laterally, unchecked Blast radius contained by segmentation Best fit for Fixed offices, on-prem-only networks Cloud, remote work, hybrid environments EXAMPLE SCENARIO Google&#x27;s internal BeyondCorp initiative replaced VPN-based perimeter access with per-request, identity- and device-aware verification for every employee application -- a widely cited real-world case of the shift this table describes. 16 / 20</p></div>",
            "cleanText": "SIDE BY SIDE Zero Trust vs. Perimeter Defense PERIMETER DEFENSE ZERO TRUST Trust model Trusted inside, untrusted outside Never trust; verify every request Access scope Broad access once inside the network Least privilege, scoped per resource Verification One-time, at login or network entry Continuous, re-checked per request Breach impact Attacker can move laterally, unchecked Blast radius contained by segmentation Best fit for Fixed offices, on-prem-only networks Cloud, remote work, hybrid environments EXAMPLE SCENARIO Google's internal BeyondCorp initiative replaced VPN-based perimeter access with per-request, identity- and device-aware verification for every employee application -- a widely cited real-world case of the shift this table describes. 16 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-33",
            "slideNumber": 33,
            "title": "GETTING THERE",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Continuous Monitoring, Analytics & Implementation",
            "lead": "GETTING THERE Implementation Roadmap 1",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>GETTING THERE</h3><p class=\"lead-statement\">Implementation Roadmap 1</p><div class=\"info-card mt-3\"><p>Assess Inventory identities, devices, data flows, and existing controls 2 Identity First Roll out MFA and SSO; retire shared/static credentials 3 Segment Introduce microsegmentation and device posture checks 4 Automate Policy Move from static rules to adaptive, risk-based policy 5 Monitor &amp; RefineDeploy analytics; continuously tune based on real signals 17 / 20</p></div>",
            "cleanText": "GETTING THERE Implementation Roadmap 1 Assess Inventory identities, devices, data flows, and existing controls 2 Identity First Roll out MFA and SSO; retire shared/static credentials 3 Segment Introduce microsegmentation and device posture checks 4 Automate Policy Move from static rules to adaptive, risk-based policy 5 Monitor & RefineDeploy analytics; continuously tune based on real signals 17 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-34",
            "slideNumber": 34,
            "title": "GETTING THERE",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Continuous Monitoring, Analytics & Implementation",
            "lead": "GETTING THERE Implementation Roadmap 1",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>GETTING THERE</h3><p class=\"lead-statement\">Implementation Roadmap 1</p><div class=\"info-card mt-3\"><p>Assess Inventory identities, devices, data flows, and existing controls 2 Identity First Roll out MFA and SSO; retire shared/static credentials 3 Segment Introduce microsegmentation and device posture checks 4 Automate Policy Move from static rules to adaptive, risk-based policy 5 Monitor &amp; RefineDeploy analytics; continuously tune based on real signals EXAMPLE SCENARIO A mid-size insurance firm spends month one mapping which apps hold sensitive claims data. In months two-3, it rolls out MFA company-wide and retires its old shared &quot;admin&quot; login. By month six, its claims-processing servers sit behind microsegmentation, and by month twelve, a UEBA platform is auto-flagging anomalous access -- turning a two-year &quot;someday&quot; project into a phased, funded roadmap. 17 / 20</p></div>",
            "cleanText": "GETTING THERE Implementation Roadmap 1 Assess Inventory identities, devices, data flows, and existing controls 2 Identity First Roll out MFA and SSO; retire shared/static credentials 3 Segment Introduce microsegmentation and device posture checks 4 Automate Policy Move from static rules to adaptive, risk-based policy 5 Monitor & RefineDeploy analytics; continuously tune based on real signals EXAMPLE SCENARIO A mid-size insurance firm spends month one mapping which apps hold sensitive claims data. In months two-3, it rolls out MFA company-wide and retires its old shared \"admin\" login. By month six, its claims-processing servers sit behind microsegmentation, and by month twelve, a UEBA platform is auto-flagging anomalous access -- turning a two-year \"someday\" project into a phased, funded roadmap. 17 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-35",
            "slideNumber": 35,
            "title": "LESSONS LEARNED",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Continuous Monitoring, Analytics & Implementation",
            "lead": "LESSONS LEARNED Common Pitfalls & Challenges !",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>LESSONS LEARNED</h3><p class=\"lead-statement\">Common Pitfalls &amp; Challenges !</p><div class=\"info-card mt-3\"><p>Treating it as one product Zero Trust is an architecture and a process, not a single tool you buy and switch on. ! Ignoring legacy systems Old applications that can&#x27;t support modern auth become silent gaps in the model. ! Over-restricting users Excessive friction drives risky workarounds like shadow IT and shared logins. ! Skipping the culture shift Without leadership buy-in and training, teams quietly route around new controls. EXAMPLE SCENARIO A manufacturer rolls out strict device-posture checks company-wide overnight, blocking access for the many plant-floor terminals still running legacy Windows 7 software that can&#x27;t be updated. Frustrated staff start emailing production data to personal accounts to keep working -- the very shadow-IT risk Zero Trust was meant to prevent. The fix: a phased exception process with compensating controls for legacy systems, not a blanket cutover. 18 / 20</p></div>",
            "cleanText": "LESSONS LEARNED Common Pitfalls & Challenges ! Treating it as one product Zero Trust is an architecture and a process, not a single tool you buy and switch on. ! Ignoring legacy systems Old applications that can't support modern auth become silent gaps in the model. ! Over-restricting users Excessive friction drives risky workarounds like shadow IT and shared logins. ! Skipping the culture shift Without leadership buy-in and training, teams quietly route around new controls. EXAMPLE SCENARIO A manufacturer rolls out strict device-posture checks company-wide overnight, blocking access for the many plant-floor terminals still running legacy Windows 7 software that can't be updated. Frustrated staff start emailing production data to personal accounts to keep working -- the very shadow-IT risk Zero Trust was meant to prevent. The fix: a phased exception process with compensating controls for legacy systems, not a blanket cutover. 18 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "landmark-case-studies",
      "title": "Landmark Case Studies: SolarWinds & MS Exchange",
      "eyebrow": "Case Analyses",
      "summary": "Examining lateral traversal and supply chain compromise in the 2020 SolarWinds and 2021 Microsoft Exchange breaches.",
      "slides": [
          {
            "id": "slide-36",
            "slideNumber": 36,
            "title": "Microsoft Exchange Hack (2021)",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Landmark Case Studies: SolarWinds & MS Exchange",
            "lead": "Microsoft Exchange Hack (2021) What Happened: Attackers exploited vulnerabilities in Microsoft Exchange's email",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Microsoft Exchange Hack (2021)</h3><p class=\"lead-statement\">What Happened: Attackers exploited vulnerabilities in Microsoft Exchange&#x27;s email</p><div class=\"info-card mt-3\"><p>servers, bypassing insufficient access controls to compromise sensitive data and leaked some of the data information. Implications: Highlighted the need for robust identity verification and continuous monitoring to detect unusual behavior. Meta&#x27;s Internal Tool Breach (2022) What Happened: Phishing attacks granted hackers access to Meta&#x27;s internal tools, underscoring the risks of inadequate device authentication. Implications: Reinforced the importance of endpoint security in Zero Trust frameworks. The Cost of Failure: Case Studies of ZTA Breaches</p></div>",
            "cleanText": "Microsoft Exchange Hack (2021) What Happened: Attackers exploited vulnerabilities in Microsoft Exchange's email servers, bypassing insufficient access controls to compromise sensitive data and leaked some of the data information. Implications: Highlighted the need for robust identity verification and continuous monitoring to detect unusual behavior. Meta's Internal Tool Breach (2022) What Happened: Phishing attacks granted hackers access to Meta's internal tools, underscoring the risks of inadequate device authentication. Implications: Reinforced the importance of endpoint security in Zero Trust frameworks. The Cost of Failure: Case Studies of ZTA Breaches",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-37",
            "slideNumber": 37,
            "title": "SolarWinds Supply Chain Attack (2020)",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Landmark Case Studies: SolarWinds & MS Exchange",
            "lead": "SolarWinds Supply Chain Attack (2020) - What Happened: Compromised software updates allowed attackers to infiltrate thousands of networks, exposing",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>SolarWinds Supply Chain Attack (2020)</h3><p class=\"lead-statement\">attackers to infiltrate thousands of networks, exposing gaps in vendor and third-party management.</p><div class=\"info-card mt-3\"><p>external access points and monitoring supply chain security. The Cost of Failure: Case Studies of ZTA Breaches</p></div><ul class=\"compact mt-3\"><li>What Happened: Compromised software updates allowed</li><li>Implications: Demonstrated the necessity of auditing</li></ul>",
            "cleanText": "SolarWinds Supply Chain Attack (2020) - What Happened: Compromised software updates allowed attackers to infiltrate thousands of networks, exposing gaps in vendor and third-party management. - Implications: Demonstrated the necessity of auditing external access points and monitoring supply chain security. The Cost of Failure: Case Studies of ZTA Breaches",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-38",
            "slideNumber": 38,
            "title": "SUMMARY",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Landmark Case Studies: SolarWinds & MS Exchange",
            "lead": "SUMMARY Key Takeaways 1 The network perimeter no longer defines the security boundary -- identity, device, and",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>SUMMARY</h3><p class=\"lead-statement\">Key Takeaways 1 The network perimeter no longer defines the security boundary -- identity, device, and</p><div class=\"info-card mt-3\"><p>context do. 2 &quot;Never trust, always verify&quot; means continuous, per-request verification -- not a one-time login check. 3 Least privilege and microsegmentation shrink the blast radius when -- not if -- a breach occurs. 4 Zero Trust is a phased journey across identity, devices, network, apps, and data -- not a single product. The goal isn&#x27;t a perfect, unbreachable network -- it&#x27;s a network where a single stolen password or infected laptop never becomes a full-scale breach. 19 / 20</p></div>",
            "cleanText": "SUMMARY Key Takeaways 1 The network perimeter no longer defines the security boundary -- identity, device, and context do. 2 \"Never trust, always verify\" means continuous, per-request verification -- not a one-time login check. 3 Least privilege and microsegmentation shrink the blast radius when -- not if -- a breach occurs. 4 Zero Trust is a phased journey across identity, devices, network, apps, and data -- not a single product. The goal isn't a perfect, unbreachable network -- it's a network where a single stolen password or infected laptop never becomes a full-scale breach. 19 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-39",
            "slideNumber": 39,
            "title": "Never Trust. Always Verify.",
            "eyebrow": "CIT 220 • Unit 02.1",
            "subtitle": "Landmark Case Studies: SolarWinds & MS Exchange",
            "lead": "✓ Never Trust. Always Verify. Thank you -- Questions & Discussion",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<div class=\"intro-author-card\"><div class=\"institution-badge\"><span>West Visayas State University • CICT Main Campus, Iloilo City</span></div><h2>Thank You!</h2><p class=\"intro-tagline\">CIT 220 Information Assurance and Security 2 • Unit 02.1 Complete</p><p class=\"mt-4 text-xs text-slate-500 dark:text-slate-400\">Curriculum instruction by Prof. Chin Ann Feliprada • WVSU CICT</p></div>",
            "cleanText": "✓ Never Trust. Always Verify. Thank you -- Questions & Discussion Zero Trust Architecture & Perimeter Defense 20 / 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    }
  ]
};
