import { Topic } from '../../../types/content';

export const TOPIC_02_2: Topic = {
  "id": "cit220-unit-02-seg",
  "slug": "02-2-network-segmentation-microsegmentation",
  "topicNumber": "02.2",
  "title": "Network Segmentation & Microsegmentation",
  "subtitle": "Defending East-West Data Center Traffic from VLANs to Layer 7 Microsegmentation",
  "description": "Modern enterprise network isolation: lateral movement risks, VLAN architectural constraints, Layer 4 port-filtering limits, process-level Layer 7 allowlisting, and automated ransomware containment.",
  "author": "Chin Ann Feliprada",
  "originalPath": "cit220_02_2_network_segmentation_microsegmentation",
  "badge": "Microsegmentation",
  "tags": ["Microsegmentation", "VLANs", "East-West Traffic", "Layer 7", "Process Allowlisting", "Ransomware Defense", "Data Center Security"],
  "totalSlides": 29,
  "sections": [
    {
      "id": "east-west-problem",
      "title": "The East-West Traffic Problem in Data Centers",
      "eyebrow": "Lateral Movement",
      "summary": "Why legacy North-South firewalls cannot see or control East-West server-to-server traffic inside the data center perimeter.",
      "slides": [
          {
            "id": "slide-1",
            "slideNumber": 1,
            "title": "A MODERN ENTERPRISE SECURITY BRIEFING",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "The East-West Traffic Problem in Data Centers",
            "lead": "A MODERN ENTERPRISE SECURITY BRIEFING Network Segmentation & Microsegmentation",
            "byline": "Prof. Chin Ann Feliprada • WVSU CICT Main Campus, Iloilo City",
            "isTitleSlide": true,
            "isSectionDivider": false,
            "rawHtml": "<div class=\"intro-author-card\"><div class=\"institution-badge\"><span>West Visayas State University • CICT Main Campus, Iloilo City</span></div><h2>Network Segmentation &amp; Microsegmentation</h2><p class=\"intro-tagline\">CIT 220 Information Assurance and Security 2 • Unit 02.2</p><p class=\"mt-4 text-xs text-slate-500 dark:text-slate-400\">Course Instructor: Prof. Chin Ann Feliprada</p></div>",
            "cleanText": "A MODERN ENTERPRISE SECURITY BRIEFING Network Segmentation & Microsegmentation Why legacy perimeter defenses fall short in the data center -- and how segmentation strategies evolve from VLANs to Layer 7 microsegmentation. Based on: Network Segmentation and Microsegmentation in Modern Enterprise Environments -- Akamai White Paper",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-2",
            "slideNumber": 2,
            "title": "AGENDA",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "The East-West Traffic Problem in Data Centers",
            "lead": "AGENDA What We'll Cover 01",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>AGENDA</h3><p class=\"lead-statement\">What We&#x27;ll Cover 01</p><div class=\"info-card mt-3\"><p>The Problem Why legacy firewalls can&#x27;t handle east-west traffic 02 Three Approaches Environment, application, and tier segmentation 03 VLANs The traditional method -- and its hard limits 04 Layer 4 Controls Application segmentation and where it falls short 05 Layer 7 Microsegmentation Process-level control and real visibility 06 Zero Trust &amp; Takeaways Tying it together, and future-proofing the enterprise NETWORK SEGMENTATION &amp; MICROSEGMENTATION 2</p></div>",
            "cleanText": "AGENDA What We'll Cover 01 The Problem Why legacy firewalls can't handle east-west traffic 02 Three Approaches Environment, application, and tier segmentation 03 VLANs The traditional method -- and its hard limits 04 Layer 4 Controls Application segmentation and where it falls short 05 Layer 7 Microsegmentation Process-level control and real visibility 06 Zero Trust & Takeaways Tying it together, and future-proofing the enterprise NETWORK SEGMENTATION & MICROSEGMENTATION 2",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-3",
            "slideNumber": 3,
            "title": "Network segmentation is the act of dividing a computer network into",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "The East-West Traffic Problem in Data Centers",
            "lead": "Network segmentation is the act of dividing a computer network into smaller physical or logical components in order to increase security and protect data.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Network segmentation is the act of dividing a computer network into</h3><p class=\"lead-statement\">smaller physical or logical components in order to increase security and protect data.</p><div class=\"info-card mt-3\"><p>Microsegmentation is a network security technique that divides a data center or cloud environment into isolated logical zones, right down to the individual workload level. Instead of placing a firewall at the network perimeter and trusting everything inside, microsegmentation enforces security policies between every workload -- every VM, container, server, and function. Network Segmentation &amp; Microsegmentation</p></div>",
            "cleanText": "Network segmentation is the act of dividing a computer network into smaller physical or logical components in order to increase security and protect data. Microsegmentation is a network security technique that divides a data center or cloud environment into isolated logical zones, right down to the individual workload level. Instead of placing a firewall at the network perimeter and trusting everything inside, microsegmentation enforces security policies between every workload -- every VM, container, server, and function. Network Segmentation & Microsegmentation",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-4",
            "slideNumber": 4,
            "title": "Network Segmentation",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "The East-West Traffic Problem in Data Centers",
            "lead": "Network Segmentation",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Network Segmentation</h3>",
            "cleanText": "Network Segmentation",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-5",
            "slideNumber": 5,
            "title": "Microsegmentation",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "The East-West Traffic Problem in Data Centers",
            "lead": "Microsegmentation",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Microsegmentation</h3>",
            "cleanText": "Microsegmentation",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-6",
            "slideNumber": 6,
            "title": "Microsegmentation vs. Traditional Network Segmentation",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "The East-West Traffic Problem in Data Centers",
            "lead": "A direct comparison across architectural scope, traffic focus, enforcement mechanisms, and Zero Trust alignment.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Microsegmentation vs. Traditional Network Segmentation</h3><p class=\"lead-statement\">A direct comparison across architectural scope, traffic focus, enforcement mechanisms, and Zero Trust alignment.</p><div class=\"info-card mt-3\"><p><strong>Architectural Paradigm Shift:</strong> Traditional segmentation treats the internal network as trusted once past the perimeter firewall. Microsegmentation eliminates internal implicit trust by enforcing security at each individual workload boundary.</p></div>",
            "cleanText": "Microsegmentation vs. Traditional Network Segmentation A direct comparison across architectural scope, traffic focus, enforcement mechanisms, and Zero Trust alignment. Architectural Paradigm Shift: Traditional segmentation treats the internal network as trusted once past the perimeter firewall. Microsegmentation eliminates internal implicit trust by enforcing security at each individual workload boundary.",
            "codeSnippets": [],
            "tables": [
              {
                "headers": ["Feature / Dimension", "Traditional Network Segmentation", "Microsegmentation"],
                "rows": [
                  ["Scope", "Broad network zones, subnets, and VLANs", "Granular, individual workloads, containers, and processes"],
                  ["Traffic Focus", "North-South (perimeter ingress and egress)", "East-West (lateral server-to-server communications)"],
                  ["Enforcement Point", "Centralized hardware firewalls, routers, and switches", "Distributed host-level agents, hypervisors, and service meshes"],
                  ["Policy Criteria", "Static IP addresses, subnets, and port numbers", "Application identities, cryptographic tags, and environment labels"],
                  ["Operational Agility", "Manual rule updates, slow deployment, prone to firewall rule sprawl", "Automated, policy-as-code synchronized with container lifecycles"],
                  ["Zero Trust Fit", "Perimeter-centric; leaves internal lateral paths vulnerable", "Fundamental core building block for Zero Trust Architecture"]
                ]
              }
            ],
            "images": [
              "/assets/microseg-vs-traditional-table.jpg"
            ]
          },
          {
            "id": "slide-7",
            "slideNumber": 7,
            "title": "01 -- THE PROBLEM",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "The East-West Traffic Problem in Data Centers",
            "lead": "01 -- THE PROBLEM Segmentation Isn't New -- But the Stakes Are Perimeter firewalls, VLANs, and ACLs have long been how enterprises segment IT infrastructure. But the environment they were built for no",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>01 -- THE PROBLEM</h3><p class=\"lead-statement\">Segmentation Isn&#x27;t New -- But the Stakes Are Perimeter firewalls, VLANs, and ACLs have long been how enterprises segment IT infrastructure. But the environment they were built for no longer exists.</p><div class=\"info-card mt-3\"><p>Containerization Workloads spin up and down far faster than static network rules can track. Public &amp; multicloud Infrastructure now spans providers, each with its own segmentation model. Software-defined networking The network fabric itself is now programmable, not just the endpoints on it. Ransomware &amp; nation-state actors Sophisticated adversaries now target any business, not just high-profile ones. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 3</p></div>",
            "cleanText": "01 -- THE PROBLEM Segmentation Isn't New -- But the Stakes Are Perimeter firewalls, VLANs, and ACLs have long been how enterprises segment IT infrastructure. But the environment they were built for no longer exists. Containerization Workloads spin up and down far faster than static network rules can track. Public & multicloud Infrastructure now spans providers, each with its own segmentation model. Software-defined networking The network fabric itself is now programmable, not just the endpoints on it. Ransomware & nation-state actors Sophisticated adversaries now target any business, not just high-profile ones. NETWORK SEGMENTATION & MICROSEGMENTATION 3",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-8",
            "slideNumber": 8,
            "title": "01 -- THE PROBLEM",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "The East-West Traffic Problem in Data Centers",
            "lead": "01 -- THE PROBLEM Legacy Firewalls Watch the Wrong Traffic Traditional perimeter devices were built to monitor traffic moving north-south -- from external clients to servers. They were never designed ",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>01 -- THE PROBLEM</h3><p class=\"lead-statement\">Legacy Firewalls Watch the Wrong Traffic Traditional perimeter devices were built to monitor traffic moving north-south -- from external clients to servers. They were never designed for what happens</p><div class=\"info-card mt-3\"><p>once traffic is already inside. External Client NORTH-SOUTH  --  monitored by legacy firewalls Web App Database Storage EAST-WEST  --  server-to-server traffic, historically unmonitored The growth of virtualization, hypervisors, VPCs, and container-based computing has made east-west traffic the dominant flow inside the modern data center. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 4</p></div>",
            "cleanText": "01 -- THE PROBLEM Legacy Firewalls Watch the Wrong Traffic Traditional perimeter devices were built to monitor traffic moving north-south -- from external clients to servers. They were never designed for what happens once traffic is already inside. External Client NORTH-SOUTH  --  monitored by legacy firewalls Web App Database Storage EAST-WEST  --  server-to-server traffic, historically unmonitored The growth of virtualization, hypervisors, VPCs, and container-based computing has made east-west traffic the dominant flow inside the modern data center. NETWORK SEGMENTATION & MICROSEGMENTATION 4",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-9",
            "slideNumber": 9,
            "title": "01 -- THE PROBLEM",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "The East-West Traffic Problem in Data Centers",
            "lead": "01 -- THE PROBLEM Once Inside, Attackers Go Unnoticed for Weeks TLS encryption and traffic that piggybacks on open, legitimate application ports let many attacks slip",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>01 -- THE PROBLEM</h3><p class=\"lead-statement\">Once Inside, Attackers Go Unnoticed for Weeks TLS encryption and traffic that piggybacks on open, legitimate application ports let many attacks slip</p><div class=\"info-card mt-3\"><p>past perimeter firewalls entirely -- leaving dwell time uncontrolled. 15 days average median attacker dwell time across enterprises 34 days average dwell time seen in small businesses and specific industries 0% protection legacy firewalls provide once an attacker is already past the edge Source: Sophos, Active Adversary Playbook 2022 -- cited in Akamai&#x27;s Network Segmentation and Microsegmentation white paper. The longer the dwell time, the more catastrophic the eventual breach -- and legacy firewalls have no mechanism to shorten it. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 5</p></div>",
            "cleanText": "01 -- THE PROBLEM Once Inside, Attackers Go Unnoticed for Weeks TLS encryption and traffic that piggybacks on open, legitimate application ports let many attacks slip past perimeter firewalls entirely -- leaving dwell time uncontrolled. 15 days average median attacker dwell time across enterprises 34 days average dwell time seen in small businesses and specific industries 0% protection legacy firewalls provide once an attacker is already past the edge Source: Sophos, Active Adversary Playbook 2022 -- cited in Akamai's Network Segmentation and Microsegmentation white paper. The longer the dwell time, the more catastrophic the eventual breach -- and legacy firewalls have no mechanism to shorten it. NETWORK SEGMENTATION & MICROSEGMENTATION 5",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-10",
            "slideNumber": 10,
            "title": "01 -- THE PROBLEM",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "The East-West Traffic Problem in Data Centers",
            "lead": "01 -- THE PROBLEM You Can't Firewall Your Way to Scale Virtualized firewalls can't realistically cover thousands of",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>01 -- THE PROBLEM</h3><p class=\"lead-statement\">You Can&#x27;t Firewall Your Way to Scale Virtualized firewalls can&#x27;t realistically cover thousands of</p><div class=\"info-card mt-3\"><p>applications and workloads -- and even if they could, managing them across constantly shifting environments isn&#x27;t practical. Thousands of workloads, each potentially needing its own policy Hybrid cloud requires firewalls to work across environments and track workloads across clouds Everything needs to be controlled from a single point -- something legacy tooling wasn&#x27;t built for One perimeter control point, thousands of workloads to protect NETWORK SEGMENTATION &amp; MICROSEGMENTATION 6</p></div>",
            "cleanText": "01 -- THE PROBLEM You Can't Firewall Your Way to Scale Virtualized firewalls can't realistically cover thousands of applications and workloads -- and even if they could, managing them across constantly shifting environments isn't practical. Thousands of workloads, each potentially needing its own policy Hybrid cloud requires firewalls to work across environments and track workloads across clouds Everything needs to be controlled from a single point -- something legacy tooling wasn't built for One perimeter control point, thousands of workloads to protect NETWORK SEGMENTATION & MICROSEGMENTATION 6",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "segmentation-approaches",
      "title": "Three Approaches to East-West Segmentation",
      "eyebrow": "Strategy Overview",
      "summary": "Comparing VLAN segmentation, Layer 4 firewall controls, and Layer 7 microsegmentation.",
      "slides": [
          {
            "id": "slide-11",
            "slideNumber": 11,
            "title": "02 -- THREE APPROACHES",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Three Approaches to East-West Segmentation",
            "lead": "02 -- THREE APPROACHES Three Ways to Segment East-West Traffic Without strong segmentation, any port or server can reach any other -- so a single breach can spread freely. These",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>02 -- THREE APPROACHES</h3><p class=\"lead-statement\">Three Ways to Segment East-West Traffic Without strong segmentation, any port or server can reach any other -- so a single breach can spread freely. These</p><div class=\"info-card mt-3\"><p>three approaches can be combined for increasingly granular control. Environment Segmentation Separates entire environments -- e.g. development from production. The first, foundational stage of any segmentation strategy. Application Segmentation &quot;Ringfences&quot; high-value applications, isolating each critical app from the rest of the network -- down to the process level. Tier Segmentation The tightest form: policy within an application itself, controlling traffic between web, application, and database tiers. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 7</p></div>",
            "cleanText": "02 -- THREE APPROACHES Three Ways to Segment East-West Traffic Without strong segmentation, any port or server can reach any other -- so a single breach can spread freely. These three approaches can be combined for increasingly granular control. Environment Segmentation Separates entire environments -- e.g. development from production. The first, foundational stage of any segmentation strategy. Application Segmentation \"Ringfences\" high-value applications, isolating each critical app from the rest of the network -- down to the process level. Tier Segmentation The tightest form: policy within an application itself, controlling traffic between web, application, and database tiers. NETWORK SEGMENTATION & MICROSEGMENTATION 7",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-12",
            "slideNumber": 12,
            "title": "02 -- THREE APPROACHES",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Three Approaches to East-West Segmentation",
            "lead": "02 -- THREE APPROACHES Layering the Three Approaches Each approach nests inside the last -- combined, they let you build increasingly granular policy for your most critical or",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>02 -- THREE APPROACHES</h3><p class=\"lead-statement\">Layering the Three Approaches Each approach nests inside the last -- combined, they let you build increasingly granular policy for your most critical or</p><div class=\"info-card mt-3\"><p>highest-risk applications. ENVIRONMENT SEGMENTATION  --  e.g. production APPLICATION SEGMENTATION  --  ringfenced critical app Web App Database TIER SEGMENTATION -- process-level control between tiers NETWORK SEGMENTATION &amp; MICROSEGMENTATION 8</p></div>",
            "cleanText": "02 -- THREE APPROACHES Layering the Three Approaches Each approach nests inside the last -- combined, they let you build increasingly granular policy for your most critical or highest-risk applications. ENVIRONMENT SEGMENTATION  --  e.g. production APPLICATION SEGMENTATION  --  ringfenced critical app Web App Database TIER SEGMENTATION -- process-level control between tiers NETWORK SEGMENTATION & MICROSEGMENTATION 8",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "vlan-segmentation",
      "title": "Approach One: Segmenting With VLANs & Limitations",
      "eyebrow": "Network Layer Controls",
      "summary": "VLAN broadcast domains, routing complexities, operational friction, and vulnerability to subnet-wide lateral movement.",
      "slides": [
          {
            "id": "slide-13",
            "slideNumber": 13,
            "title": "03 -- VLANS: Approach One: Segmenting With VLANs",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach One: Segmenting With VLANs & Limitations",
            "lead": "03 -- VLANS Approach One: Segmenting With VLANs Most companies start here. Virtual local area networks let a business allocate each segment its own communication path, enforced through a firewall or",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>03 -- VLANS: Approach One: Segmenting With VLANs</h3><p class=\"lead-statement\">Approach One: Segmenting With VLANs Most companies start here. Virtual local area networks let a business allocate each segment its own communication path, enforced through a firewall or</p><div class=\"info-card mt-3\"><p>router-level ACLs. Uses existing architecture No new platform to buy or deploy -- it works with switches and routers already in place. Feels low cost Because it reuses infrastructure, the sticker price looks attractive up front. Familiar to network teams ACLs and VLAN tagging are well-understood, long-standing networking concepts. But underneath... VLANs are rigid, complex to reconfigure, expensive to maintain at scale, and typically require downtime to implement changes. Next: the specific limitations → NETWORK SEGMENTATION &amp; MICROSEGMENTATION 9</p></div>",
            "cleanText": "03 -- VLANS Approach One: Segmenting With VLANs Most companies start here. Virtual local area networks let a business allocate each segment its own communication path, enforced through a firewall or router-level ACLs. Uses existing architecture No new platform to buy or deploy -- it works with switches and routers already in place. Feels low cost Because it reuses infrastructure, the sticker price looks attractive up front. Familiar to network teams ACLs and VLAN tagging are well-understood, long-standing networking concepts. But underneath... VLANs are rigid, complex to reconfigure, expensive to maintain at scale, and typically require downtime to implement changes. Next: the specific limitations → NETWORK SEGMENTATION & MICROSEGMENTATION 9",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-14",
            "slideNumber": 14,
            "title": "03 -- VLANS: VLANs Were Never Built for Segmentation",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach One: Segmenting With VLANs & Limitations",
            "lead": "03 -- VLANS VLANs Were Never Built for Segmentation VLANs were originally designed to reduce network congestion -- not to control security communications. Using",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>03 -- VLANS: VLANs Were Never Built for Segmentation</h3><p class=\"lead-statement\">VLANs Were Never Built for Segmentation VLANs were originally designed to reduce network congestion -- not to control security communications. Using</p><div class=\"info-card mt-3\"><p>them for segmentation is, in many ways, a misuse of the technology. Doesn&#x27;t extend to the cloud VLANs and traditional ACLs can&#x27;t reach cloud workloads directly -- you end up bolting on SDN and third-party virtualized firewalls just to cover the gap. Containers stay exposed Every container on a host shares the same kernel. One exploited container can put every other container on that host at risk -- VLANs have no answer for this. Hits a hard protocol ceiling VLANs cap out at 4,096 segments -- a real constraint in a large data center where far more granular boundaries are needed. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 10</p></div>",
            "cleanText": "03 -- VLANS VLANs Were Never Built for Segmentation VLANs were originally designed to reduce network congestion -- not to control security communications. Using them for segmentation is, in many ways, a misuse of the technology. Doesn't extend to the cloud VLANs and traditional ACLs can't reach cloud workloads directly -- you end up bolting on SDN and third-party virtualized firewalls just to cover the gap. Containers stay exposed Every container on a host shares the same kernel. One exploited container can put every other container on that host at risk -- VLANs have no answer for this. Hits a hard protocol ceiling VLANs cap out at 4,096 segments -- a real constraint in a large data center where far more granular boundaries are needed. NETWORK SEGMENTATION & MICROSEGMENTATION 10",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-15",
            "slideNumber": 15,
            "title": "03 -- VLANS: Example Scenario: Reconfiguring a VLAN Segment",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach One: Segmenting With VLANs & Limitations",
            "lead": "03 -- VLANS Example Scenario: Reconfiguring a VLAN Segment A network team needs to add a new segment for a business unit's servers. Here's what that typically looks like with",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>03 -- VLANS: Example Scenario: Reconfiguring a VLAN Segment</h3><p class=\"lead-statement\">Example Scenario: Reconfiguring a VLAN Segment A network team needs to add a new segment for a business unit&#x27;s servers. Here&#x27;s what that typically looks like with</p><div class=\"info-card mt-3\"><p>VLANs. 1 Map dependencies Engineers manually document every server and dependency in the target segment 2 Design the config New switch-level configuration is drafted for each affected switch 3 Schedule a window Because traffic may be interrupted, the change needs a maintenance window 4 Roll out across sites Multiple physical locations mean the same change repeated many times over Result: a process that can take many days and cost a disproportionate amount of time and money -- while traffic sits interrupted or slowed. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 11</p></div>",
            "cleanText": "03 -- VLANS Example Scenario: Reconfiguring a VLAN Segment A network team needs to add a new segment for a business unit's servers. Here's what that typically looks like with VLANs. 1 Map dependencies Engineers manually document every server and dependency in the target segment 2 Design the config New switch-level configuration is drafted for each affected switch 3 Schedule a window Because traffic may be interrupted, the change needs a maintenance window 4 Roll out across sites Multiple physical locations mean the same change repeated many times over Result: a process that can take many days and cost a disproportionate amount of time and money -- while traffic sits interrupted or slowed. NETWORK SEGMENTATION & MICROSEGMENTATION 11",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "layer4-application-controls",
      "title": "Approach Two: Application Segmentation (Layer 4)",
      "eyebrow": "Transport Layer Controls",
      "summary": "IP and port-based filtering, firewall rule explosion, compliance vs actual security, and port spoofing risks.",
      "slides": [
          {
            "id": "slide-16",
            "slideNumber": 16,
            "title": "04 -- LAYER 4 CONTROLS",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach Two: Application Segmentation (Layer 4)",
            "lead": "04 -- LAYER 4 CONTROLS Approach Two: Application Segmentation Many VLAN issues are improved by application segmentation --",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>04 -- LAYER 4 CONTROLS</h3><p class=\"lead-statement\">Approach Two: Application Segmentation Many VLAN issues are improved by application segmentation --</p><div class=\"info-card mt-3\"><p>using cloud security groups or hypervisor-based firewalls to implement Layer 4 controls between service tiers. Isolates service tiers so each application has a secure boundary Each tier gets only the access it needs to function -- nothing more Reduces attack surface by segmenting a whole application cluster from the rest of the business LAYER 4 Transport Layer Focuses on how data itself is delivered -- IP addresses, ports, and the segmenting of data into blocks for transit. Enforced via: NETWORK SEGMENTATION &amp; MICROSEGMENTATION 12</p></div><ul class=\"compact mt-3\"><li>Cloud security groups</li><li>Hypervisor-based firewalls</li><li>IP / port allowlists</li></ul>",
            "cleanText": "04 -- LAYER 4 CONTROLS Approach Two: Application Segmentation Many VLAN issues are improved by application segmentation -- using cloud security groups or hypervisor-based firewalls to implement Layer 4 controls between service tiers. Isolates service tiers so each application has a secure boundary Each tier gets only the access it needs to function -- nothing more Reduces attack surface by segmenting a whole application cluster from the rest of the business LAYER 4 Transport Layer Focuses on how data itself is delivered -- IP addresses, ports, and the segmenting of data into blocks for transit. Enforced via: -  Cloud security groups -  Hypervisor-based firewalls -  IP / port allowlists NETWORK SEGMENTATION & MICROSEGMENTATION 12",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-17",
            "slideNumber": 17,
            "title": "04 -- LAYER 4 CONTROLS",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach Two: Application Segmentation (Layer 4)",
            "lead": "04 -- LAYER 4 CONTROLS Example Scenario: Isolating a Payment Application A business keeps its database tier from communicating with the internet at all, and ensures a breached",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>04 -- LAYER 4 CONTROLS</h3><p class=\"lead-statement\">Example Scenario: Isolating a Payment Application A business keeps its database tier from communicating with the internet at all, and ensures a breached</p><div class=\"info-card mt-3\"><p>load balancer can&#x27;t pivot to sensitive data. Internet Load Balancer App Servers (DMZ) Database Tier allow: 443 allow: app port allow: DB port only Database has no direct path to the internet, at all If the load balancer is breached, the attacker is still confined to the app tier&#x27;s allowed ports -- they cannot reach the database directly. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 13</p></div>",
            "cleanText": "04 -- LAYER 4 CONTROLS Example Scenario: Isolating a Payment Application A business keeps its database tier from communicating with the internet at all, and ensures a breached load balancer can't pivot to sensitive data. Internet Load Balancer App Servers (DMZ) Database Tier allow: 443 allow: app port allow: DB port only Database has no direct path to the internet, at all If the load balancer is breached, the attacker is still confined to the app tier's allowed ports -- they cannot reach the database directly. NETWORK SEGMENTATION & MICROSEGMENTATION 13",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-18",
            "slideNumber": 18,
            "title": "04 -- LAYER 4 CONTROLS",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach Two: Application Segmentation (Layer 4)",
            "lead": "04 -- LAYER 4 CONTROLS The Limits of Layer 4 Controls Layer 4 controls are essential, but attackers have shown they can work around IP- and port-based rules -- and Layer",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>04 -- LAYER 4 CONTROLS</h3><p class=\"lead-statement\">The Limits of Layer 4 Controls Layer 4 controls are essential, but attackers have shown they can work around IP- and port-based rules -- and Layer</p><div class=\"info-card mt-3\"><p>4 does nothing to stop movement once inside a tier. IP spoofing Attackers can forge source IP addresses to slip past rules written only against IP ranges. Port piggybacking Malicious traffic hides inside open, legitimate application ports -- the port is allowed, so Layer 4 waves it through. No intra-tier control Layer 4 protection doesn&#x27;t limit lateral movement within an application or a single tier once an attacker is inside it. The key insight: a Layer 4 port is either open or closed. It can&#x27;t tell the difference between the right process using that port and the wrong one impersonating it. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 14</p></div>",
            "cleanText": "04 -- LAYER 4 CONTROLS The Limits of Layer 4 Controls Layer 4 controls are essential, but attackers have shown they can work around IP- and port-based rules -- and Layer 4 does nothing to stop movement once inside a tier. IP spoofing Attackers can forge source IP addresses to slip past rules written only against IP ranges. Port piggybacking Malicious traffic hides inside open, legitimate application ports -- the port is allowed, so Layer 4 waves it through. No intra-tier control Layer 4 protection doesn't limit lateral movement within an application or a single tier once an attacker is inside it. The key insight: a Layer 4 port is either open or closed. It can't tell the difference between the right process using that port and the wrong one impersonating it. NETWORK SEGMENTATION & MICROSEGMENTATION 14",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-19",
            "slideNumber": 19,
            "title": "04 -- LAYER 4 CONTROLS",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach Two: Application Segmentation (Layer 4)",
            "lead": "04 -- LAYER 4 CONTROLS Compliant Isn't the Same as Secure Layer 4 segmentation has historically been accepted for regulatory scope reduction -- keeping a CDE separate for",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>04 -- LAYER 4 CONTROLS</h3><p class=\"lead-statement\">Compliant Isn&#x27;t the Same as Secure Layer 4 segmentation has historically been accepted for regulatory scope reduction -- keeping a CDE separate for</p><div class=\"info-card mt-3\"><p>PCI-DSS, or isolating PHI for HIPAA. But compliance and security are not the same test. 43% of companies are &quot;fully compliant&quot; with PCI-DSS, per Verizon&#x27;s 2022 Payment Security Report 100% compliance still doesn&#x27;t mean 100% security -- attackers can ride an open Layer 4 port straight to Layer 7 and take what they want Source: Verizon 2022 Payment Security Report -- cited in Akamai&#x27;s Network Segmentation and Microsegmentation white paper. Layer 4 controls may satisfy an auditor -- they don&#x27;t reduce the attack surface enough to make a meaningful security difference on their own. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 15</p></div>",
            "cleanText": "04 -- LAYER 4 CONTROLS Compliant Isn't the Same as Secure Layer 4 segmentation has historically been accepted for regulatory scope reduction -- keeping a CDE separate for PCI-DSS, or isolating PHI for HIPAA. But compliance and security are not the same test. 43% of companies are \"fully compliant\" with PCI-DSS, per Verizon's 2022 Payment Security Report 100% compliance still doesn't mean 100% security -- attackers can ride an open Layer 4 port straight to Layer 7 and take what they want Source: Verizon 2022 Payment Security Report -- cited in Akamai's Network Segmentation and Microsegmentation white paper. Layer 4 controls may satisfy an auditor -- they don't reduce the attack surface enough to make a meaningful security difference on their own. NETWORK SEGMENTATION & MICROSEGMENTATION 15",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-20",
            "slideNumber": 20,
            "title": "04 -- LAYER 4 CONTROLS",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach Two: Application Segmentation (Layer 4)",
            "lead": "04 -- LAYER 4 CONTROLS Segmenting in the Dark Neither network- nor Layer 4 application segmentation reliably gives you what you actually need at",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>04 -- LAYER 4 CONTROLS</h3><p class=\"lead-statement\">Segmenting in the Dark Neither network- nor Layer 4 application segmentation reliably gives you what you actually need at</p><div class=\"info-card mt-3\"><p>every stage: an accurate, real-time view of your environment. Before segmenting Visualize application dependencies so policy rules are drawn up accurately -- guessing here breaks applications later. After segmenting Prove the policy is working as intended -- for your own security posture and for regulators. Ongoing Without real-time and historical visibility, evidence has to be collected manually -- slow, costly, and error-prone. A segmentation solution that can&#x27;t provide this kind of visibility, at every stage, is simply not enough. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 16</p></div>",
            "cleanText": "04 -- LAYER 4 CONTROLS Segmenting in the Dark Neither network- nor Layer 4 application segmentation reliably gives you what you actually need at every stage: an accurate, real-time view of your environment. Before segmenting Visualize application dependencies so policy rules are drawn up accurately -- guessing here breaks applications later. After segmenting Prove the policy is working as intended -- for your own security posture and for regulators. Ongoing Without real-time and historical visibility, evidence has to be collected manually -- slow, costly, and error-prone. A segmentation solution that can't provide this kind of visibility, at every stage, is simply not enough. NETWORK SEGMENTATION & MICROSEGMENTATION 16",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "layer7-microsegmentation",
      "title": "Approach Three: Microsegmentation to Layer 7 & Ransomware Defense",
      "eyebrow": "Layer 7 Microsegmentation",
      "summary": "Process-level allowlisting, full workload telemetry, and step-by-step containment of enterprise ransomware attacks.",
      "slides": [
          {
            "id": "slide-21",
            "slideNumber": 21,
            "title": "05 -- LAYER 7 MICROSEGMENTATION",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach Three: Microsegmentation to Layer 7 & Ransomware Defense",
            "lead": "05 -- LAYER 7 MICROSEGMENTATION Approach Three: Microsegmentation to Layer 7 Layer 7 is the application layer -- where network services integrate",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>05 -- LAYER 7 MICROSEGMENTATION</h3><p class=\"lead-statement\">Approach Three: Microsegmentation to Layer 7 Layer 7 is the application layer -- where network services integrate</p><div class=\"info-card mt-3\"><p>with the operating system itself, and where protocols like HTTP , FTP , TFTP , and SMTP live. Process- and flow-based Policy references specific processes and flows, not just IP addresses and ports. Effective within a tier Limits lateral movement even inside a single application cluster or tier. Sensitive to the smallest signal Can spot a threat from something as small as the wrong hash, even if an attacker mirrors an authorized process. LAYER 7 Application Layer HTTP  ·  FTP  ·  TFTP  ·  SMTP Default-deny allowlisting: Only exact, approved processes or flows communicate. Everything else is blocked automatically. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 17</p></div>",
            "cleanText": "05 -- LAYER 7 MICROSEGMENTATION Approach Three: Microsegmentation to Layer 7 Layer 7 is the application layer -- where network services integrate with the operating system itself, and where protocols like HTTP , FTP , TFTP , and SMTP live. Process- and flow-based Policy references specific processes and flows, not just IP addresses and ports. Effective within a tier Limits lateral movement even inside a single application cluster or tier. Sensitive to the smallest signal Can spot a threat from something as small as the wrong hash, even if an attacker mirrors an authorized process. LAYER 7 Application Layer HTTP  ·  FTP  ·  TFTP  ·  SMTP Default-deny allowlisting: Only exact, approved processes or flows communicate. Everything else is blocked automatically. NETWORK SEGMENTATION & MICROSEGMENTATION 17",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-22",
            "slideNumber": 22,
            "title": "05 -- LAYER 7 MICROSEGMENTATION",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach Three: Microsegmentation to Layer 7 & Ransomware Defense",
            "lead": "05 -- LAYER 7 MICROSEGMENTATION Example Scenario: Process-Level Allowlisting An app server is allowed to reach the database only via its known, signed payment process -- on the exact expected port.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>05 -- LAYER 7 MICROSEGMENTATION</h3><p class=\"lead-statement\">Example Scenario: Process-Level Allowlisting An app server is allowed to reach the database only via its known, signed payment process -- on the exact expected port.</p><div class=\"info-card mt-3\"><p>Everything else is blocked by default, automatically. App Server payment-svc.exe hash: a1f9...c02e (verified) attempted-shell.exe hash: 7bd2...91aa (unknown) Database Only payment-svc.exe with a verified hash is allowlisted on port 5432. allowed blocked -- unrecognized process Even a process that mirrors the right pathway or port is stopped -- because the policy checks the process identity itself, not just the network path. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 18</p></div>",
            "cleanText": "05 -- LAYER 7 MICROSEGMENTATION Example Scenario: Process-Level Allowlisting An app server is allowed to reach the database only via its known, signed payment process -- on the exact expected port. Everything else is blocked by default, automatically. App Server payment-svc.exe hash: a1f9...c02e (verified) attempted-shell.exe hash: 7bd2...91aa (unknown) Database Only payment-svc.exe with a verified hash is allowlisted on port 5432. allowed blocked -- unrecognized process Even a process that mirrors the right pathway or port is stopped -- because the policy checks the process identity itself, not just the network path. NETWORK SEGMENTATION & MICROSEGMENTATION 18",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-23",
            "slideNumber": 23,
            "title": "05 -- LAYER 7 MICROSEGMENTATION",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach Three: Microsegmentation to Layer 7 & Ransomware Defense",
            "lead": "05 -- LAYER 7 MICROSEGMENTATION Catching What Layer 4 Can't See Layer 4 only asks: is this port open? Layer 7 asks a sharper question: is this the exact, verified process I",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>05 -- LAYER 7 MICROSEGMENTATION</h3><p class=\"lead-statement\">Catching What Layer 4 Can&#x27;t See Layer 4 only asks: is this port open? Layer 7 asks a sharper question: is this the exact, verified process I</p><div class=\"info-card mt-3\"><p>expect to see here? ATTACK TECHNIQUE LAYER 4 RESULT LAYER 7 RESULT Attacker rides an open port Allowed -- port is open Blocked -- process identity doesn&#x27;t match Spoofed source IP address May pass -- rule matches IP range Irrelevant -- policy isn&#x27;t based on IP alone Lateral move within same tier Not addressed -- tier boundary already crossed Blocked -- each flow is evaluated individually NETWORK SEGMENTATION &amp; MICROSEGMENTATION 19</p></div>",
            "cleanText": "05 -- LAYER 7 MICROSEGMENTATION Catching What Layer 4 Can't See Layer 4 only asks: is this port open? Layer 7 asks a sharper question: is this the exact, verified process I expect to see here? ATTACK TECHNIQUE LAYER 4 RESULT LAYER 7 RESULT Attacker rides an open port Allowed -- port is open Blocked -- process identity doesn't match Spoofed source IP address May pass -- rule matches IP range Irrelevant -- policy isn't based on IP alone Lateral move within same tier Not addressed -- tier boundary already crossed Blocked -- each flow is evaluated individually NETWORK SEGMENTATION & MICROSEGMENTATION 19",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-24",
            "slideNumber": 24,
            "title": "05 -- LAYER 7 MICROSEGMENTATION",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach Three: Microsegmentation to Layer 7 & Ransomware Defense",
            "lead": "05 -- LAYER 7 MICROSEGMENTATION One Map, Every Workload Agents on every workload -- hypervisor- or VPC-based, containers, bare-metal servers, even IoT/OT systems -- build a single,",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>05 -- LAYER 7 MICROSEGMENTATION</h3><p class=\"lead-statement\">One Map, Every Workload Agents on every workload -- hypervisor- or VPC-based, containers, bare-metal servers, even IoT/OT systems -- build a single,</p><div class=\"info-card mt-3\"><p>holistic visual map of the entire IT estate. Real-time visual map Hypervisor / VPC Containers Bare-metal servers IoT / OT systems Multicloud Data center NETWORK SEGMENTATION &amp; MICROSEGMENTATION 20</p></div>",
            "cleanText": "05 -- LAYER 7 MICROSEGMENTATION One Map, Every Workload Agents on every workload -- hypervisor- or VPC-based, containers, bare-metal servers, even IoT/OT systems -- build a single, holistic visual map of the entire IT estate. Real-time visual map Hypervisor / VPC Containers Bare-metal servers IoT / OT systems Multicloud Data center NETWORK SEGMENTATION & MICROSEGMENTATION 20",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-25",
            "slideNumber": 25,
            "title": "05 -- LAYER 7 MICROSEGMENTATION",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach Three: Microsegmentation to Layer 7 & Ransomware Defense",
            "lead": "05 -- LAYER 7 MICROSEGMENTATION Visibility Pays Off at Every Stage Before deployment",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>05 -- LAYER 7 MICROSEGMENTATION</h3><p class=\"lead-statement\">Visibility Pays Off at Every Stage Before deployment</p><div class=\"info-card mt-3\"><p>Segmentation rules can be pre-built for new or updated applications before they ever go live. In production Real-time detection flags application activity outside the norm before it becomes an active exploit. After an incident Historical context shows exactly which environment allowed an anomaly -- tighten policy and document for compliance. Traditional application segmentation struggles to deliver this all-in-one view because it leans on a patchwork of network-centric technologies. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 21</p></div>",
            "cleanText": "05 -- LAYER 7 MICROSEGMENTATION Visibility Pays Off at Every Stage Before deployment Segmentation rules can be pre-built for new or updated applications before they ever go live. In production Real-time detection flags application activity outside the norm before it becomes an active exploit. After an incident Historical context shows exactly which environment allowed an anomaly -- tighten policy and document for compliance. Traditional application segmentation struggles to deliver this all-in-one view because it leans on a patchwork of network-centric technologies. NETWORK SEGMENTATION & MICROSEGMENTATION 21",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-26",
            "slideNumber": 26,
            "title": "06 -- ZERO TRUST",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach Three: Microsegmentation to Layer 7 & Ransomware Defense",
            "lead": "06 -- ZERO TRUST \"No traffic or user is trusted",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>06 -- ZERO TRUST</h3><p class=\"lead-statement\">&quot;No traffic or user is trusted</p><div class=\"info-card mt-3\"><p>until proven so.&quot; Coined by Forrester in 2010. Microsegmentation is what makes it operationally real. Forrester&#x27;s three principles of Zero Trust All entities are untrusted by default Nothing -- internal or external -- is assumed safe. Every connection attempt has to prove itself, every time. Comprehensive security monitoring is implemented Continuous, granular visibility replaces the old assumption that anything inside the perimeter is already cleared. Least-privilege access is enforced Every entity gets exactly the access it needs to function The &quot;castle and moat&quot; is obsolete -- most companies no longer have a single contained network or data center to defend. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 22</p></div><ul class=\"compact mt-3\"><li>and no more -- enforced down to the process level.</li></ul>",
            "cleanText": "06 -- ZERO TRUST \"No traffic or user is trusted until proven so.\" Coined by Forrester in 2010. Microsegmentation is what makes it operationally real. Forrester's three principles of Zero Trust All entities are untrusted by default Nothing -- internal or external -- is assumed safe. Every connection attempt has to prove itself, every time. Comprehensive security monitoring is implemented Continuous, granular visibility replaces the old assumption that anything inside the perimeter is already cleared. Least-privilege access is enforced Every entity gets exactly the access it needs to function -- and no more -- enforced down to the process level. The \"castle and moat\" is obsolete -- most companies no longer have a single contained network or data center to defend. NETWORK SEGMENTATION & MICROSEGMENTATION 22",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-27",
            "slideNumber": 27,
            "title": "06 -- ZERO TRUST",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach Three: Microsegmentation to Layer 7 & Ransomware Defense",
            "lead": "06 -- ZERO TRUST Three Approaches, Side by Side VLANS LAYER 4 (APPLICATION) LAYER 7 (MICRO-)",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>06 -- ZERO TRUST</h3><p class=\"lead-statement\">Three Approaches, Side by Side VLANS LAYER 4 (APPLICATION) LAYER 7 (MICRO-)</p><div class=\"info-card mt-3\"><p>Granularity Subnet / segment Service tier Individual process or flow Extends to cloud No -- needs bolt-on SDN Yes, via security groups Yes, natively Container-aware No Partially Yes Blocks port piggybacking No No Yes Change speed Days, needs downtime Faster, still coarse Near real-time Segment limit 4,096 (protocol cap) No hard cap No hard cap NETWORK SEGMENTATION &amp; MICROSEGMENTATION 23</p></div>",
            "cleanText": "06 -- ZERO TRUST Three Approaches, Side by Side VLANS LAYER 4 (APPLICATION) LAYER 7 (MICRO-) Granularity Subnet / segment Service tier Individual process or flow Extends to cloud No -- needs bolt-on SDN Yes, via security groups Yes, natively Container-aware No Partially Yes Blocks port piggybacking No No Yes Change speed Days, needs downtime Faster, still coarse Near real-time Segment limit 4,096 (protocol cap) No hard cap No hard cap NETWORK SEGMENTATION & MICROSEGMENTATION 23",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-28",
            "slideNumber": 28,
            "title": "EXAMPLE SCENARIO",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach Three: Microsegmentation to Layer 7 & Ransomware Defense",
            "lead": "EXAMPLE SCENARIO A Ransomware Attempt, Layer by Layer Tracing one attack attempt through all three segmentation approaches shows why depth matters more than any single control.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>EXAMPLE SCENARIO</h3><p class=\"lead-statement\">A Ransomware Attempt, Layer by Layer Tracing one attack attempt through all three segmentation approaches shows why depth matters more than any single control.</p><div class=\"info-card mt-3\"><p>01 Initial access Phishing email compromises a single endpoint in the corporate environment segment. 02 Environment segmentation holds The compromised endpoint sits in the corporate segment CDE environments stay separate. 03 Attacker tries east-west spread Malware attempts to reach application servers by piggybacking on an open Layer 4 port. 04 Layer 7 policy blocks itThe process attempting the connection doesn&#x27;t match the allowlisted, verified hash -- traffic is denied by default. 05 Full visibility capturedThe attempted flow, process hash, and timing are logged in real time for the security team and for compliance evidence. Any single layer might have missed this. Layered, combined segmentation caught it. NETWORK SEGMENTATION &amp; MICROSEGMENTATION 24</p></div><ul class=\"compact mt-3\"><li>production and</li></ul>",
            "cleanText": "EXAMPLE SCENARIO A Ransomware Attempt, Layer by Layer Tracing one attack attempt through all three segmentation approaches shows why depth matters more than any single control. 01 Initial access Phishing email compromises a single endpoint in the corporate environment segment. 02 Environment segmentation holds The compromised endpoint sits in the corporate segment -- production and CDE environments stay separate. 03 Attacker tries east-west spread Malware attempts to reach application servers by piggybacking on an open Layer 4 port. 04 Layer 7 policy blocks itThe process attempting the connection doesn't match the allowlisted, verified hash -- traffic is denied by default. 05 Full visibility capturedThe attempted flow, process hash, and timing are logged in real time for the security team and for compliance evidence. Any single layer might have missed this. Layered, combined segmentation caught it. NETWORK SEGMENTATION & MICROSEGMENTATION 24",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-29",
            "slideNumber": 29,
            "title": "CONCLUSION",
            "eyebrow": "CIT 220 • Unit 02.2",
            "subtitle": "Approach Three: Microsegmentation to Layer 7 & Ransomware Defense",
            "lead": "CONCLUSION Future-Proof the Business With Microsegmentation",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<div class=\"intro-author-card\"><div class=\"institution-badge\"><span>West Visayas State University • CICT Main Campus, Iloilo City</span></div><h2>Thank You!</h2><p class=\"intro-tagline\">CIT 220 Information Assurance and Security 2 • Unit 02.2 Complete</p><p class=\"mt-4 text-xs text-slate-500 dark:text-slate-400\">Curriculum instruction by Prof. Chin Ann Feliprada • WVSU CICT</p></div>",
            "cleanText": "CONCLUSION Future-Proof the Business With Microsegmentation Start with environment segmentation It's the crucial first stage -- separate dev, prod, and other environments before going more granular. Layer the three approaches Environment, application, and tier segmentation combine to build increasingly granular policy for critical apps. Push to Layer 7 where it matters Process- and flow-level control catches what IP- and port-based rules alone will miss. Demand real visibility A segmentation solution that can't show you what's happening, in real time, isn't enough. A good microsegmentation solution won't ask you to choose between security and agility. Source material: \"Network Segmentation and Microsegmentation in Modern Enterprise Environments,\" Akamai White Paper, published 05/23. akamai.com/guardicore NETWORK SEGMENTATION & MICROSEGMENTATION 25",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    }
  ]
};
