import { Topic } from '../../../types/content';

export const TOPIC_02: Topic = {
  "id": "cit220-unit-02",
  "slug": "02-advanced-network-and-system-security",
  "topicNumber": "02",
  "title": "Advanced Network & System Security",
  "subtitle": "Intrusion Detection/Prevention (IDPS), SIEM Analytics, and Virtual Private Networks (VPNs)",
  "description": "Network traffic inspection and defenses: signature vs anomaly IDPS, enterprise SIEM aggregation, microsegmentation fundamentals, and secure encrypted VPN tunneling protocols.",
  "author": "Chin Ann Feliprada",
  "originalPath": "cit220_02_advanced_network_and_system_security",
  "badge": "Network Defense",
  "tags": ["IDPS", "Snort", "Suricata", "SIEM", "Splunk", "Microsegmentation", "VPNs", "IPsec", "OpenVPN", "WireGuard"],
  "totalSlides": 38,
  "sections": [
    {
      "id": "idps-overview",
      "title": "Intrusion Detection & Prevention Systems (IDPS)",
      "eyebrow": "Network Defense",
      "summary": "Signature vs anomaly-based monitoring, network IDS (NIDS) vs host IDS (HIDS), and active inline prevention.",
      "slides": [
          {
            "id": "slide-1",
            "slideNumber": 1,
            "title": "Advanced Network",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Intrusion Detection & Prevention Systems (IDPS)",
            "lead": "Advanced Network and System Security Unit 2",
            "byline": "Prof. Chin Ann Feliprada • WVSU CICT Main Campus, Iloilo City",
            "isTitleSlide": true,
            "isSectionDivider": false,
            "rawHtml": "<div class=\"intro-author-card\"><div class=\"institution-badge\"><span>West Visayas State University • CICT Main Campus, Iloilo City</span></div><h2>Advanced Network &amp; System Security</h2><p class=\"intro-tagline\">CIT 220 Information Assurance and Security 2 • Unit 02</p><p class=\"mt-4 text-xs text-slate-500 dark:text-slate-400\">Course Instructor: Prof. Chin Ann Feliprada</p></div>",
            "cleanText": "Advanced Network and System Security Unit 2 CIT 220 - Information Assurance and Security 2",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-2",
            "slideNumber": 2,
            "title": "2.1 Intrusion Detection/Prevention Systems (IDPS)",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Intrusion Detection & Prevention Systems (IDPS)",
            "lead": "2.1 Intrusion Detection/Prevention Systems (IDPS) 2.2 Zero Trust Architecture & Microsegmentation 2.3 Virtual Private Networks (VPNs)",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>2.1 Intrusion Detection/Prevention Systems (IDPS)</h3><p class=\"lead-statement\">2.2 Zero Trust Architecture &amp; Microsegmentation 2.3 Virtual Private Networks (VPNs)</p><div class=\"info-card mt-3\"><p>Secure communication channels History of VPNs Types of VPNs When to use and how does it work Installing VPNs Secure Configuration Management and Hardening Vulnerability Management and Penetration Testing Methodologies Implementing Zero Trust to Microsegmentation Primary challenges with implementing micro-segmentation Security Information and Event Management (SIEM) Advanced Firewall Concepts and Next-Generation Firewalls (NGFW)</p></div>",
            "cleanText": "2.1 Intrusion Detection/Prevention Systems (IDPS) 2.2 Zero Trust Architecture & Microsegmentation 2.3 Virtual Private Networks (VPNs) Secure communication channels History of VPNs Types of VPNs When to use and how does it work Installing VPNs Secure Configuration Management and Hardening Vulnerability Management and Penetration Testing Methodologies Implementing Zero Trust to Microsegmentation Primary challenges with implementing micro-segmentation Security Information and Event Management (SIEM) Advanced Firewall Concepts and Next-Generation Firewalls (NGFW)",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-3",
            "slideNumber": 3,
            "title": "2.1 Intrusion Detection",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Intrusion Detection & Prevention Systems (IDPS)",
            "lead": "2.1 Intrusion Detection and Prevention Systems (IDPS)",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>2.1 Intrusion Detection</h3><p class=\"lead-statement\">and Prevention Systems (IDPS)</p>",
            "cleanText": "2.1 Intrusion Detection and Prevention Systems (IDPS)",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-4",
            "slideNumber": 4,
            "title": "Intrusion Detection Systems (IDS):",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Intrusion Detection & Prevention Systems (IDPS)",
            "lead": "Intrusion Detection Systems (IDS): Function: Monitors network traffic and system activity for malicious",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Intrusion Detection Systems (IDS):</h3><p class=\"lead-statement\">Function: Monitors network traffic and system activity for malicious</p><div class=\"info-card mt-3\"><p>behavior or policy violations. Action: Generates alerts and logs suspicious activity for review by security teams. Examples: Can be software applications, hardware devices, or cloud-based solutions.</p></div>",
            "cleanText": "Intrusion Detection Systems (IDS): Function: Monitors network traffic and system activity for malicious behavior or policy violations. Action: Generates alerts and logs suspicious activity for review by security teams. Examples: Can be software applications, hardware devices, or cloud-based solutions.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-5",
            "slideNumber": 5,
            "title": "Intrusion Prevention Systems",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Intrusion Detection & Prevention Systems (IDPS)",
            "lead": "Intrusion Prevention Systems (IPS): Function: Acts on detected",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Intrusion Prevention Systems</h3><p class=\"lead-statement\">(IPS): Function: Acts on detected</p><div class=\"info-card mt-3\"><p>threats by blocking or mitigating malicious activity. Action: May drop malicious packets, block IP addresses, or modify network traffic to prevent attacks. Examples: Often integrated with or incorporated into IDS solutions.</p></div>",
            "cleanText": "Intrusion Prevention Systems (IPS): Function: Acts on detected threats by blocking or mitigating malicious activity. Action: May drop malicious packets, block IP addresses, or modify network traffic to prevent attacks. Examples: Often integrated with or incorporated into IDS solutions.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-6",
            "slideNumber": 6,
            "title": "Intrusion Detection and",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Intrusion Detection & Prevention Systems (IDPS)",
            "lead": "Intrusion Detection and Prevention Systems Intrusion Detection and Prevention Systems (IDPS)",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Intrusion Detection and</h3><p class=\"lead-statement\">Prevention Systems Intrusion Detection and Prevention Systems (IDPS)</p><div class=\"info-card mt-3\"><p>are security tools that monitor networks and systems for malicious activity and take action to block or mitigate threats. They combine the capabilities of Intrusion Detection Systems (IDS) and Intrusion Prevention Systems (IPS) to provide comprehensive security.</p></div>",
            "cleanText": "Intrusion Detection and Prevention Systems Intrusion Detection and Prevention Systems (IDPS) are security tools that monitor networks and systems for malicious activity and take action to block or mitigate threats. They combine the capabilities of Intrusion Detection Systems (IDS) and Intrusion Prevention Systems (IPS) to provide comprehensive security.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-7",
            "slideNumber": 7,
            "title": "IDPS in Practice:",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Intrusion Detection & Prevention Systems (IDPS)",
            "lead": "IDPS in Practice: Monitoring: IDPS analyze network traffic, looking for patterns that match",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>IDPS in Practice:</h3><p class=\"lead-statement\">Monitoring: IDPS analyze network traffic, looking for patterns that match</p><div class=\"info-card mt-3\"><p>known attack signatures or unusual behavior (anomalies). Alerting: When suspicious activity is detected, IDPS generate alerts that are sent to security teams for investigation and response. Prevention: IPS components of IDPS can automatically block or mitigate attacks, potentially stopping them before they cause harm. Reporting: IDPS provide detailed logs and reports about detected threats, which can be used for forensic analysis and improving security policies.</p></div>",
            "cleanText": "IDPS in Practice: Monitoring: IDPS analyze network traffic, looking for patterns that match known attack signatures or unusual behavior (anomalies). Alerting: When suspicious activity is detected, IDPS generate alerts that are sent to security teams for investigation and response. Prevention: IPS components of IDPS can automatically block or mitigate attacks, potentially stopping them before they cause harm. Reporting: IDPS provide detailed logs and reports about detected threats, which can be used for forensic analysis and improving security policies.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "siem-platforms",
      "title": "Security Information & Event Management (SIEM)",
      "eyebrow": "Security Analytics",
      "summary": "Real-time visibility, log aggregation, event correlation, and industry SIEM solutions (Splunk, QRadar, Microsoft Sentinel).",
      "slides": [
          {
            "id": "slide-8",
            "slideNumber": 8,
            "title": "is a cybersecurity solution that",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Security Information & Event Management (SIEM)",
            "lead": "is a cybersecurity solution that provides real-time visibility into an organization's IT environment",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>is a cybersecurity solution that</h3><p class=\"lead-statement\">provides real-time visibility into an organization&#x27;s IT environment</p><div class=\"info-card mt-3\"><p>by collecting, analyzing, and correlating security logs and event data from various sources. SIEM tools help detect security threats, streamline incident response, support compliance efforts, and provide centralized security insights by centralizing data, identifying abnormal activities, and generating alerts for potential security issues. Security Information and Event Management (SIEM)</p></div>",
            "cleanText": "is a cybersecurity solution that provides real-time visibility into an organization's IT environment by collecting, analyzing, and correlating security logs and event data from various sources. SIEM tools help detect security threats, streamline incident response, support compliance efforts, and provide centralized security insights by centralizing data, identifying abnormal activities, and generating alerts for potential security issues. Security Information and Event Management (SIEM)",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-9",
            "slideNumber": 9,
            "title": "How: SIEM works",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Security Information & Event Management (SIEM)",
            "lead": "How SIEM works For example, when SIEM",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>How: SIEM works</h3><p class=\"lead-statement\">SIEM works For example, when SIEM</p><div class=\"info-card mt-3\"><p>identifies a threat, it generates an alert and notifies and flags the attack to appropriate stakeholders. SIEM&#x27;s custom dashboards also help reduce the time spent looking into false positives.</p></div>",
            "cleanText": "How SIEM works For example, when SIEM identifies a threat, it generates an alert and notifies and flags the attack to appropriate stakeholders. SIEM's custom dashboards also help reduce the time spent looking into false positives.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-10",
            "slideNumber": 10,
            "title": "EXAMPLES OF SIEM",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Security Information & Event Management (SIEM)",
            "lead": "EXAMPLES OF SIEM Popular SIEM platforms like Splunk, IBM",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>EXAMPLES OF SIEM</h3><p class=\"lead-statement\">Popular SIEM platforms like Splunk, IBM</p><div class=\"info-card mt-3\"><p>QRadar, and ArcSight provide real-time threat monitoring, centralized dashboards, and automated responses to handle such incidents by collecting and analyzing data from across an organization&#x27;s network infrastructure.</p></div>",
            "cleanText": "EXAMPLES OF SIEM Popular SIEM platforms like Splunk, IBM QRadar, and ArcSight provide real-time threat monitoring, centralized dashboards, and automated responses to handle such incidents by collecting and analyzing data from across an organization's network infrastructure.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "zero-trust-microsegmentation",
      "title": "Zero Trust & Microsegmentation Integration",
      "eyebrow": "Network Architecture",
      "summary": "Moving beyond perimeter firewalls, network-level vs host-level microsegmentation, and shared responsibility enforcement.",
      "slides": [
          {
            "id": "slide-11",
            "slideNumber": 11,
            "title": "2.2 Zero Trust",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Zero Trust & Microsegmentation Integration",
            "lead": "2.2 Zero Trust Architecture and Micro Segmentation",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>2.2 Zero Trust</h3><p class=\"lead-statement\">Architecture and Micro Segmentation</p>",
            "cleanText": "2.2 Zero Trust Architecture and Micro Segmentation",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-12",
            "slideNumber": 12,
            "title": "MICRO-SEGMENTATION",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Zero Trust & Microsegmentation Integration",
            "lead": "MICRO-SEGMENTATION 1 -Creates secure zones across cloud and data center",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>MICRO-SEGMENTATION</h3><p class=\"lead-statement\">1 environments to isolate application workloads from one another and</p><div class=\"info-card mt-3\"><p>secure them individually. With micro-segmentation, firewall policies limit east-west traffic between workloads based on a zero-trust security approach to reduce attack surfaces, prevent the lateral movement of threats to contain breaches, and strengthen regulatory compliance. multicloud data center. https://www.cisco.com/site/us/en/learn/topics/security</p></div><ul class=\"compact mt-3\"><li>Creates secure zones across cloud and data center</li><li>Application segmentation or east-west segmentation in a</li></ul>",
            "cleanText": "MICRO-SEGMENTATION 1 -Creates secure zones across cloud and data center environments to isolate application workloads from one another and secure them individually. With micro-segmentation, firewall policies limit east-west traffic between workloads based on a zero-trust security approach to reduce attack surfaces, prevent the lateral movement of threats to contain breaches, and strengthen regulatory compliance. - Application segmentation or east-west segmentation in a multicloud data center. https://www.cisco.com/site/us/en/learn/topics/security",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-13",
            "slideNumber": 13,
            "title": "Advanced Network & System Security - Slide 13",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Zero Trust & Microsegmentation Integration",
            "lead": "Key conceptual lecture material.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Advanced Network &amp; System Security - Slide 13</h3>",
            "cleanText": "Advanced Network & System Security - Slide 13",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-14",
            "slideNumber": 14,
            "title": "Benefits of micro-segmentation",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Zero Trust & Microsegmentation Integration",
            "lead": "Benefits of micro-segmentation 1",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Benefits of micro-segmentation</h3><p class=\"lead-statement\">1</p>",
            "cleanText": "Benefits of micro-segmentation 1",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-15",
            "slideNumber": 15,
            "title": "Implementing Zero Trust with",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Zero Trust & Microsegmentation Integration",
            "lead": "Implementing Zero Trust with Micro- segmentation 1",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Implementing Zero Trust with</h3><p class=\"lead-statement\">Micro- segmentation 1</p><div class=\"info-card mt-3\"><p>Zero Trust security strategy to reduce your organization&#x27;s cyber risk and exposure to attacks. Zero trust is restricting access to systems and resources to only what is required. Following network authentication, each request is checked against established access control policies and either granted or denied. Access to apps is allowed based on business logic and is limited to minimal essential permissions. Enforcing zero trust security necessitates the use of micro-segmentation. Micro-segmentation creates boundaries between workloads, allowing for stringent access control enforcement. This decreases network system susceptibility. Also, it limits an attacker&#x27;s access during a successful attack. https://www.cisco.com/site/us/en/learn/topics/security</p></div>",
            "cleanText": "Implementing Zero Trust with Micro- segmentation 1 Zero Trust security strategy to reduce your organization's cyber risk and exposure to attacks. Zero trust is restricting access to systems and resources to only what is required. Following network authentication, each request is checked against established access control policies and either granted or denied. Access to apps is allowed based on business logic and is limited to minimal essential permissions. Enforcing zero trust security necessitates the use of micro-segmentation. Micro-segmentation creates boundaries between workloads, allowing for stringent access control enforcement. This decreases network system susceptibility. Also, it limits an attacker's access during a successful attack. https://www.cisco.com/site/us/en/learn/topics/security",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-16",
            "slideNumber": 16,
            "title": "CHALLENGES IMPLEMENTING MICRO-SEGMENTATION?",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Zero Trust & Microsegmentation Integration",
            "lead": "CHALLENGES IMPLEMENTING MICRO-SEGMENTATION? 1  Micro-segmentation is the implementation of granular firewall policy controls",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>CHALLENGES IMPLEMENTING MICRO-SEGMENTATION?</h3><p class=\"lead-statement\">1  Micro-segmentation is the implementation of granular firewall policy controls</p><div class=\"info-card mt-3\"><p>using the host workload firewall as the enforcement point across any workload type (virtual machines, bare metal servers, containers).  Policy lifecycle management is the most challenging part of implementing an effective micro-segmentation policy that adapts to support changes to your applications and your business.  You begin at the macro level and continually refine through policy automation, leveraging application and workload context and behavior. https://www.cisco.com/site/us/en/learn/topics/security</p></div>",
            "cleanText": "CHALLENGES IMPLEMENTING MICRO-SEGMENTATION? 1  Micro-segmentation is the implementation of granular firewall policy controls using the host workload firewall as the enforcement point across any workload type (virtual machines, bare metal servers, containers).  Policy lifecycle management is the most challenging part of implementing an effective micro-segmentation policy that adapts to support changes to your applications and your business.  You begin at the macro level and continually refine through policy automation, leveraging application and workload context and behavior. https://www.cisco.com/site/us/en/learn/topics/security",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-17",
            "slideNumber": 17,
            "title": "What can micro-segmentation do that a firewall cannot?",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Zero Trust & Microsegmentation Integration",
            "lead": "What can micro-segmentation do that a firewall cannot? Micro-segmentation goes beyond a firewall by applying granular security policies at the",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>What can micro-segmentation do that a firewall cannot?</h3><p class=\"lead-statement\">Micro-segmentation goes beyond a firewall by applying granular security policies at the</p><div class=\"info-card mt-3\"><p>individual workload level, even within the same subnet, to prevent lateral threat movement and contain breaches, whereas firewalls typically focus on broad network perimeter control. Micro-segmentation provides enhanced security by creating isolated, secure zones for applications and servers, reducing the overall attack surface and supporting a zero- trust security model more effectively than traditional firewalls alone.</p></div>",
            "cleanText": "What can micro-segmentation do that a firewall cannot? Micro-segmentation goes beyond a firewall by applying granular security policies at the individual workload level, even within the same subnet, to prevent lateral threat movement and contain breaches, whereas firewalls typically focus on broad network perimeter control. Micro-segmentation provides enhanced security by creating isolated, secure zones for applications and servers, reducing the overall attack surface and supporting a zero- trust security model more effectively than traditional firewalls alone.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-18",
            "slideNumber": 18,
            "title": "Types of Micro-segmentation",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Zero Trust & Microsegmentation Integration",
            "lead": "Types of Micro-segmentation Network- based",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Types of Micro-segmentation</h3><p class=\"lead-statement\">Network- based</p><div class=\"info-card mt-3\"><p>Regulate who and what may access various areas of your network. It is simple to administer and takes little administrative work. Note that managing security restrictions becomes difficult and costly if your segments get too vast. Hypervisor- based Te With this technique, agents are placed on each endpoint to provide visibility and control over data, processes, software, and communications. A central manager controls everything, keeping an eye out for any flaws. This agent-based installation does not guarantee Zero Trust. It is also time-consuming for both administrators and end users to get it installed on every node on the network/host Host-based A software or hardware used to run virtual computers. Allows for complete tracking and management of the network traffic. This is a huge win. Because now you can use existing firewalls and transfer security settings between hypervisors. Not suitable for cloud installations or certain types of applications. https://accuknox.com/blog/micro-segmentation This strategies depend on organizational needs and circumstances. Whether you choose network-based micro-segmentation, hypervisor-based micro-segmentation, or host-based micro-segmentation, you&#x27;re taking a significant step toward improving network security.</p></div>",
            "cleanText": "Types of Micro-segmentation Network- based Regulate who and what may access various areas of your network. It is simple to administer and takes little administrative work. Note that managing security restrictions becomes difficult and costly if your segments get too vast. Hypervisor- based Te With this technique, agents are placed on each endpoint to provide visibility and control over data, processes, software, and communications. A central manager controls everything, keeping an eye out for any flaws. This agent-based installation does not guarantee Zero Trust. It is also time-consuming for both administrators and end users to get it installed on every node on the network/host Host-based A software or hardware used to run virtual computers. Allows for complete tracking and management of the network traffic. This is a huge win. Because now you can use existing firewalls and transfer security settings between hypervisors. Not suitable for cloud installations or certain types of applications. https://accuknox.com/blog/micro-segmentation This strategies depend on organizational needs and circumstances. Whether you choose network-based micro-segmentation, hypervisor-based micro-segmentation, or host-based micro-segmentation, you're taking a significant step toward improving network security.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-19",
            "slideNumber": 19,
            "title": "Finally, micro-segmentation is an integral ingredient of",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Zero Trust & Microsegmentation Integration",
            "lead": "Finally, micro-segmentation is an integral ingredient of the shared responsibility security paradigm. It improves the efficacy of network-wide security measures.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Finally, micro-segmentation is an integral ingredient of</h3><p class=\"lead-statement\">the shared responsibility security paradigm. It improves the efficacy of network-wide security measures.</p><div class=\"info-card mt-3\"><p>Understanding this approach is critical for initiatives involving secure cloud and digital transformation. Integrating micro-segmentation with suitable procedures and policies can assure your stakeholders and customers with the highest levels of security. Profit off a secure environment beyond the typical and deprecated perimeter. Conclusion</p></div>",
            "cleanText": "Finally, micro-segmentation is an integral ingredient of the shared responsibility security paradigm. It improves the efficacy of network-wide security measures. Understanding this approach is critical for initiatives involving secure cloud and digital transformation. Integrating micro-segmentation with suitable procedures and policies can assure your stakeholders and customers with the highest levels of security. Profit off a secure environment beyond the typical and deprecated perimeter. Conclusion",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "vpn-architectures",
      "title": "Virtual Private Networks (VPNs) & Protocols",
      "eyebrow": "Secure Communications",
      "summary": "Site-to-site vs remote access VPNs, IPsec, OpenVPN, WireGuard, and encryption mechanisms.",
      "slides": [
          {
            "id": "slide-20",
            "slideNumber": 20,
            "title": "2.3 Virtual Private",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Virtual Private Networks (VPNs) & Protocols",
            "lead": "2.3 Virtual Private Networks (VPNs) CIT 220 - Information Assurance and Security 2",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>2.3 Virtual Private</h3><p class=\"lead-statement\">Networks (VPNs) CIT 220 - Information Assurance and Security 2</p><div class=\"info-card mt-3\"><p>VPN stands for &quot;Virtual Private Network&quot; and describes the opportunity to establish a protected network connection when using public networks. VPNs encrypt your internet traffic and disguise your online identity. This makes it more difficult for third parties to track your activities online and steal data. The encryption takes place in real time. https://www.kaspersky.com/resource-center/definitions/what-is-a-vpn</p></div>",
            "cleanText": "2.3 Virtual Private Networks (VPNs) CIT 220 - Information Assurance and Security 2 VPN stands for \"Virtual Private Network\" and describes the opportunity to establish a protected network connection when using public networks. VPNs encrypt your internet traffic and disguise your online identity. This makes it more difficult for third parties to track your activities online and steal data. The encryption takes place in real time. https://www.kaspersky.com/resource-center/definitions/what-is-a-vpn",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-21",
            "slideNumber": 21,
            "title": "VPN Client: Tunneling Protocols",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Virtual Private Networks (VPNs) & Protocols",
            "lead": "VPN Client Tunneling Protocols Encryption",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>VPN Client: Tunneling Protocols</h3><p class=\"lead-statement\">Tunneling Protocols Encryption</p><div class=\"info-card mt-3\"><p>VPN Server Authentication Public/Transit Network Hardware &amp; Software Infrastructure This is a server that receives, authenticates, and authorizes connection requests from VPN clients. It is responsible for managing the secure tunnel and directing traffic. This is the software application on user&#x27;s device (like a laptop or smartphone) that initiates the VPN connection. It is configured to send and receive data over the VPN tunnel. These protocols establish a secure &quot;tunnel&quot; through which your data travels over a public network, such as the internet. This process scrambles the data so it cannot be read by unauthorized parties. Strong encryption algorithms ensure that data remains secure during transmission. This is the process by which the VPN server verifies the identity of the connecting client. This typically involves usernames, passwords, or digital certificates. This is the shared or public network, often the internet, that the VPN uses to carry the tunneled and encrypted data between the client and the server. Depending on the VPN&#x27;s scale, components can include dedicated hardware devices like VPN concentrators or firewalls, as well as network access servers for remote access. Key Components of VPN</p></div>",
            "cleanText": "VPN Client Tunneling Protocols Encryption VPN Server Authentication Public/Transit Network Hardware & Software Infrastructure This is a server that receives, authenticates, and authorizes connection requests from VPN clients. It is responsible for managing the secure tunnel and directing traffic. This is the software application on user's device (like a laptop or smartphone) that initiates the VPN connection. It is configured to send and receive data over the VPN tunnel. These protocols establish a secure \"tunnel\" through which your data travels over a public network, such as the internet. This process scrambles the data so it cannot be read by unauthorized parties. Strong encryption algorithms ensure that data remains secure during transmission. This is the process by which the VPN server verifies the identity of the connecting client. This typically involves usernames, passwords, or digital certificates. This is the shared or public network, often the internet, that the VPN uses to carry the tunneled and encrypted data between the client and the server. Depending on the VPN's scale, components can include dedicated hardware devices like VPN concentrators or firewalls, as well as network access servers for remote access. Key Components of VPN",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-22",
            "slideNumber": 22,
            "title": "IPsec (Internet Protocol Security)",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Virtual Private Networks (VPNs) & Protocols",
            "lead": "01 02 03",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>IPsec (Internet Protocol Security)</h3><p class=\"lead-statement\">02 03</p><div class=\"info-card mt-3\"><p>04 05 06 IPsec (Internet Protocol Security) OpenVPN L2TP (Layer 2 Tunneling Protocol) PPTP (Point-to-Point Tunneling Protocol) SSTP (Secure Socket Tunneling Protocol) Tunneling Protocols</p></div>",
            "cleanText": "01 02 03 04 05 06 IPsec (Internet Protocol Security) OpenVPN L2TP (Layer 2 Tunneling Protocol) PPTP (Point-to-Point Tunneling Protocol) SSTP (Secure Socket Tunneling Protocol) Tunneling Protocols",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-23",
            "slideNumber": 23,
            "title": "THE HISTORY OF VPNs",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Virtual Private Networks (VPNs) & Protocols",
            "lead": "THE HISTORY OF VPNs The first VPNs therefore started in",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>THE HISTORY OF VPNs</h3><p class=\"lead-statement\">The first VPNs therefore started in</p><div class=\"info-card mt-3\"><p>the early 2000s but were almost exclusively used by companies. However, after a flood of security breaches, especially in the early 2010s, the consumer market for VPNs started to pick up. Wei Xu developed the IPSec network, an internet security protocol that authenticates and encrypts information packets shared online. In 1996, a Microsoft employee named Gurdeep Singh-Pall created a Peer- to-Peer Tunneling Protocol (PPTP). In 1993, a team from Columbia University and AT&amp;T Bell Labs finally succeeded in creating a kind of first version of the modern VPN, known as swIPe: Software IP encryption protocol. A certain movement to protect and encrypt internet browser data existed. The US Department of Defense already got involved in projects working on the encryption of internet communication data back in the 1960s.</p></div>",
            "cleanText": "THE HISTORY OF VPNs The first VPNs therefore started in the early 2000s but were almost exclusively used by companies. However, after a flood of security breaches, especially in the early 2010s, the consumer market for VPNs started to pick up. Wei Xu developed the IPSec network, an internet security protocol that authenticates and encrypts information packets shared online. In 1996, a Microsoft employee named Gurdeep Singh-Pall created a Peer- to-Peer Tunneling Protocol (PPTP). In 1993, a team from Columbia University and AT&T Bell Labs finally succeeded in creating a kind of first version of the modern VPN, known as swIPe: Software IP encryption protocol. A certain movement to protect and encrypt internet browser data existed. The US Department of Defense already got involved in projects working on the encryption of internet communication data back in the 1960s.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-24",
            "slideNumber": 24,
            "title": "Site-to-site VPN - are mainly used in large",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Virtual Private Networks (VPNs) & Protocols",
            "lead": "Site-to-site VPN - are mainly used in large companies. They are complex to implement and do not offer the same flexibility as SSL VPNs. They are the most",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Site-to-site VPN - are mainly used in large</h3><p class=\"lead-statement\">companies. They are complex to implement and do not offer the same flexibility as SSL VPNs. They are the most</p><div class=\"info-card mt-3\"><p>effective way to ensure communication within and between large departments. Client-to-Server VPN - establishing a direct connection through a VPN provider which shortens the tunnel phase of the VPN journey. VPN can automatically encrypt the data before it is made available to the user. SSL VPN - implemented via a corresponding hardware box, HTML-5-capable browser, which is used to call up the company&#x27;s login page. HTML-5 capable browsers are available for virtually any operating system. Access is guarded with a username and password. TYPES OF VPNS The use of a private device (PC, laptop, tablet, mobile phone) A private network designed to hide private intranets and allow users of these secure networks to access each other&#x27;s resources The advantage of this type of VPN access is greater efficiency and universal access to company resources. Provided an appropriate telephone system is available, the employee can, for example, connect to the system with a headset and act as if he/she were at their company workplace. Connecting via a VPN client can be imagined as if you were connecting your home PC to the company with an extension cable.  VPN client must first be installed and configured on the computer.</p></div>",
            "cleanText": "Site-to-site VPN - are mainly used in large companies. They are complex to implement and do not offer the same flexibility as SSL VPNs. They are the most effective way to ensure communication within and between large departments. Client-to-Server VPN - establishing a direct connection through a VPN provider which shortens the tunnel phase of the VPN journey. VPN can automatically encrypt the data before it is made available to the user. SSL VPN - implemented via a corresponding hardware box, HTML-5-capable browser, which is used to call up the company's login page. HTML-5 capable browsers are available for virtually any operating system. Access is guarded with a username and password. TYPES OF VPNS The use of a private device (PC, laptop, tablet, mobile phone) A private network designed to hide private intranets and allow users of these secure networks to access each other's resources The advantage of this type of VPN access is greater efficiency and universal access to company resources. Provided an appropriate telephone system is available, the employee can, for example, connect to the system with a headset and act as if he/she were at their company workplace. Connecting via a VPN client can be imagined as if you were connecting your home PC to the company with an extension cable.  VPN client must first be installed and configured on the computer.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-25",
            "slideNumber": 25,
            "title": "How does VPN work?",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Virtual Private Networks (VPNs) & Protocols",
            "lead": "How does VPN work? 1 A VPN works by creating a secure, encrypted",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>How does VPN work?</h3><p class=\"lead-statement\">1 A VPN works by creating a secure, encrypted</p><div class=\"info-card mt-3\"><p>&quot;tunnel&quot; for your internet traffic to pass through, routing it via a remote VPN server instead of your ISP. This process encrypts your data, making it unreadable to third parties like hackers, your ISP, and governments, and hides your real IP address. As a result, your online activities are more private, and it appears you are browsing from the location of the VPN server, allowing you to bypass geographical restrictions.</p></div>",
            "cleanText": "How does VPN work? 1 A VPN works by creating a secure, encrypted \"tunnel\" for your internet traffic to pass through, routing it via a remote VPN server instead of your ISP. This process encrypts your data, making it unreadable to third parties like hackers, your ISP, and governments, and hides your real IP address. As a result, your online activities are more private, and it appears you are browsing from the location of the VPN server, allowing you to bypass geographical restrictions.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-26",
            "slideNumber": 26,
            "title": "A VPN encrypts your surfing behavior, which can only be decoded with the help of a",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Virtual Private Networks (VPNs) & Protocols",
            "lead": "A VPN encrypts your surfing behavior, which can only be decoded with the help of a key. Only your computer and the VPN know this key, so your ISP cannot recognize where you are surfing. Different VPNs",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>A VPN encrypts your surfing behavior, which can only be decoded with the help of a</h3><p class=\"lead-statement\">key. Only your computer and the VPN know this key, so your ISP cannot recognize where you are surfing. Different VPNs use different encryption processes, but</p><div class=\"info-card mt-3\"><p>generally function in three steps: Once you are online, start your VPN. The VPN acts as a secure tunnel between you and the internet. Your ISP and other third parties cannot detect this tunnel. Your device is now on the local network of the VPN, and your IP address can be changed to an IP address provided by the VPN server. You can now surf the internet at will, as the VPN protects all your personal data. Here&#x27;s how to surf securely with a VPN https://www.kaspersky.com/resource-center/definitions/what-is-a-vpn</p></div>",
            "cleanText": "A VPN encrypts your surfing behavior, which can only be decoded with the help of a key. Only your computer and the VPN know this key, so your ISP cannot recognize where you are surfing. Different VPNs use different encryption processes, but generally function in three steps: Once you are online, start your VPN. The VPN acts as a secure tunnel between you and the internet. Your ISP and other third parties cannot detect this tunnel. Your device is now on the local network of the VPN, and your IP address can be changed to an IP address provided by the VPN server. You can now surf the internet at will, as the VPN protects all your personal data. Here's how to surf securely with a VPN https://www.kaspersky.com/resource-center/definitions/what-is-a-vpn",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-27",
            "slideNumber": 27,
            "title": "Here's a breakdown of VPN examples:",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Virtual Private Networks (VPNs) & Protocols",
            "lead": "Here's a breakdown of VPN examples: Commercial VPN Services These are services you can subscribe to for personal use to encrypt your",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Here&#x27;s a breakdown of VPN examples:</h3><p class=\"lead-statement\">Commercial VPN Services These are services you can subscribe to for personal use to encrypt your</p><div class=\"info-card mt-3\"><p>internet traffic and hide your IP address.  ExpressVPN: Known for its user-friendly interface and fast speeds.  NordVPN: Offers strong privacy features and is often considered a top choice.  Surfshark: A secure option with the ability to connect unlimited devices.  ProtonVPN: Praised for its speed and reliability.  CyberGhost: A beginner-friendly and secure VPN service.  Hide.me VPN: Another example of a personal VPN provider.</p></div>",
            "cleanText": "Here's a breakdown of VPN examples: Commercial VPN Services These are services you can subscribe to for personal use to encrypt your internet traffic and hide your IP address.  ExpressVPN: Known for its user-friendly interface and fast speeds.  NordVPN: Offers strong privacy features and is often considered a top choice.  Surfshark: A secure option with the ability to connect unlimited devices.  ProtonVPN: Praised for its speed and reliability.  CyberGhost: A beginner-friendly and secure VPN service.  Hide.me VPN: Another example of a personal VPN provider.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-28",
            "slideNumber": 28,
            "title": "Here's a breakdown of VPN examples:",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Virtual Private Networks (VPNs) & Protocols",
            "lead": "Here's a breakdown of VPN examples: VPN Protocols These are the underlying technologies used to create a secure connection",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Here&#x27;s a breakdown of VPN examples:</h3><p class=\"lead-statement\">VPN Protocols These are the underlying technologies used to create a secure connection</p><div class=\"info-card mt-3\"><p>over a public network.  OpenVPN: A widely used, open-source VPN protocol.  WireGuard: A newer, faster, and more modern VPN protocol.  IPsec (Internet Protocol Security): A suite of protocols that provides authentication and encryption.  L2TP/IPsec (Layer 2 Tunneling Protocol): A common VPN tunneling protocol often paired with IPsec.  SSL/TLS (Secure Socket Tunneling Protocol): Used in web-based VPNs to provide encrypted access to applications and data.</p></div>",
            "cleanText": "Here's a breakdown of VPN examples: VPN Protocols These are the underlying technologies used to create a secure connection over a public network.  OpenVPN: A widely used, open-source VPN protocol.  WireGuard: A newer, faster, and more modern VPN protocol.  IPsec (Internet Protocol Security): A suite of protocols that provides authentication and encryption.  L2TP/IPsec (Layer 2 Tunneling Protocol): A common VPN tunneling protocol often paired with IPsec.  SSL/TLS (Secure Socket Tunneling Protocol): Used in web-based VPNs to provide encrypted access to applications and data.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-29",
            "slideNumber": 29,
            "title": "Here's a breakdown of VPN examples:",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Virtual Private Networks (VPNs) & Protocols",
            "lead": "Here's a breakdown of VPN examples: Enterprise & Business VPNs These are designed to connect employees to a company network",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Here&#x27;s a breakdown of VPN examples:</h3><p class=\"lead-statement\">Enterprise &amp; Business VPNs These are designed to connect employees to a company network</p><div class=\"info-card mt-3\"><p>or link multiple office locations.  Remote Access VPN: Allows individual users to connect to a private network. Examples include Cisco AnyConnect and Access Server by OpenVPN.  Site-to-Site VPN: Connects two or more separate networks, such as different office branches, to create a unified network.</p></div>",
            "cleanText": "Here's a breakdown of VPN examples: Enterprise & Business VPNs These are designed to connect employees to a company network or link multiple office locations.  Remote Access VPN: Allows individual users to connect to a private network. Examples include Cisco AnyConnect and Access Server by OpenVPN.  Site-to-Site VPN: Connects two or more separate networks, such as different office branches, to create a unified network.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-30",
            "slideNumber": 30,
            "title": "A VPN connection establishes a secure connection",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "Virtual Private Networks (VPNs) & Protocols",
            "lead": "A VPN connection establishes a secure connection between you and the internet. Via the VPN, all your data traffic is routed through an encrypted virtual tunnel. This",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>A VPN connection establishes a secure connection</h3><p class=\"lead-statement\">between you and the internet. Via the VPN, all your data traffic is routed through an encrypted virtual tunnel. This</p><div class=\"info-card mt-3\"><p>disguises your IP address when you use the internet, making its location invisible to everyone. A VPN connection is also secure against external attacks. That&#x27;s because only you can access the data in the encrypted tunnel - and nobody else can because they don&#x27;t have the key. A VPN allows you to access regionally restricted content from anywhere in the world. Conclusion</p></div>",
            "cleanText": "A VPN connection establishes a secure connection between you and the internet. Via the VPN, all your data traffic is routed through an encrypted virtual tunnel. This disguises your IP address when you use the internet, making its location invisible to everyone. A VPN connection is also secure against external attacks. That's because only you can access the data in the encrypted tunnel - and nobody else can because they don't have the key. A VPN allows you to access regionally restricted content from anywhere in the world. Conclusion",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    },
    {
      "id": "vpn-lab-risks",
      "title": "VPN Laboratory, Attack Surfaces & Risk Mitigation",
      "eyebrow": "Hands-On Lab",
      "summary": "Practical VPN configuration, untrustworthy providers, DNS/WebRTC leaks, and enterprise hardening best practices.",
      "slides": [
          {
            "id": "slide-31",
            "slideNumber": 31,
            "title": "LABORATORY ACTIVITY No. 1",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "VPN Laboratory, Attack Surfaces & Risk Mitigation",
            "lead": "LABORATORY ACTIVITY No. 1 Getting connected with VPN Application A VPN is only as secure as the VPN provider and",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>LABORATORY ACTIVITY No. 1</h3><p class=\"lead-statement\">Getting connected with VPN Application A VPN is only as secure as the VPN provider and</p><div class=\"info-card mt-3\"><p>the network it connects to, making it crucial to use a reputable VPN, enable multi-factor authentication (MFA), and ensure your own devices are free from malware to protect against these threats.</p></div>",
            "cleanText": "LABORATORY ACTIVITY No. 1 Getting connected with VPN Application A VPN is only as secure as the VPN provider and the network it connects to, making it crucial to use a reputable VPN, enable multi-factor authentication (MFA), and ensure your own devices are free from malware to protect against these threats.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-32",
            "slideNumber": 32,
            "title": "Specific Risks in using VPN",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "VPN Laboratory, Attack Surfaces & Risk Mitigation",
            "lead": "Specific Risks in using VPN Connecting to a network via a VPN presents risks such as data leaks, malware infection, Man-in-the-Middle (MitM) attacks, and untrusted VPN",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Specific Risks in using VPN</h3><p class=\"lead-statement\">Connecting to a network via a VPN presents risks such as data leaks, malware infection, Man-in-the-Middle (MitM) attacks, and untrusted VPN</p><div class=\"info-card mt-3\"><p>providers who may log or sell your data. Data Leaks: Despite the &quot;tunnel,&quot; data can leak outside the VPN, revealing your real IP address, browsing history, or other sensitive information. Malware and Virus Risk: If your device or the device on the other end of the VPN is compromised, malware can traverse the VPN tunnel and infect the target network. Man-in-the-Middle (MitM) Attacks: Attackers can intercept communications between your device and the VPN server, allowing them to steal or manipulate data.</p></div>",
            "cleanText": "Specific Risks in using VPN Connecting to a network via a VPN presents risks such as data leaks, malware infection, Man-in-the-Middle (MitM) attacks, and untrusted VPN providers who may log or sell your data. Data Leaks: Despite the \"tunnel,\" data can leak outside the VPN, revealing your real IP address, browsing history, or other sensitive information. Malware and Virus Risk: If your device or the device on the other end of the VPN is compromised, malware can traverse the VPN tunnel and infect the target network. Man-in-the-Middle (MitM) Attacks: Attackers can intercept communications between your device and the VPN server, allowing them to steal or manipulate data.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-33",
            "slideNumber": 33,
            "title": "Getting connected with VPN Application",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "VPN Laboratory, Attack Surfaces & Risk Mitigation",
            "lead": "Getting connected with VPN Application Untrustworthy VPNs: Free or low-cost VPNs can be run by malicious entities, leading to",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Getting connected with VPN Application</h3><p class=\"lead-statement\">Untrustworthy VPNs: Free or low-cost VPNs can be run by malicious entities, leading to</p><div class=\"info-card mt-3\"><p>data logging, selling, or even providing access to hostile actors. Weak Encryption/Protocols: If the VPN uses weak encryption standards or out-of-date protocols, your data can be intercepted and compromised more easily. Server Vulnerabilities: The VPN server itself can be a target for attacks, with vulnerabilities in server software or misconfigurations leading to data exposure. Dropped Connections: A dropped VPN connection can expose your network and traffic to threats that the VPN was meant to protect against.</p></div>",
            "cleanText": "Getting connected with VPN Application Untrustworthy VPNs: Free or low-cost VPNs can be run by malicious entities, leading to data logging, selling, or even providing access to hostile actors. Weak Encryption/Protocols: If the VPN uses weak encryption standards or out-of-date protocols, your data can be intercepted and compromised more easily. Server Vulnerabilities: The VPN server itself can be a target for attacks, with vulnerabilities in server software or misconfigurations leading to data exposure. Dropped Connections: A dropped VPN connection can expose your network and traffic to threats that the VPN was meant to protect against.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-34",
            "slideNumber": 34,
            "title": "How to Mitigate Risks",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "VPN Laboratory, Attack Surfaces & Risk Mitigation",
            "lead": "How to Mitigate Risks Choose a reputable VPN provider: Opt for a paid VPN with a strict no-logs policy that has been independently",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>How to Mitigate Risks</h3><p class=\"lead-statement\">Choose a reputable VPN provider: Opt for a paid VPN with a strict no-logs policy that has been independently</p><div class=\"info-card mt-3\"><p>audited. Enable strong authentication: Use multi-factor authentication (MFA) to prevent unauthorized access to your VPN connection. Secure your devices: Ensure that the devices you use to connect to the VPN are free from malware and are regularly updated. Use strong encryption: Verify that your VPN uses strong encryption protocols like AES-256. Beware of free VPNs: Avoid free VPN services, as they often compromise on security and privacy to make money.</p></div>",
            "cleanText": "How to Mitigate Risks Choose a reputable VPN provider: Opt for a paid VPN with a strict no-logs policy that has been independently audited. Enable strong authentication: Use multi-factor authentication (MFA) to prevent unauthorized access to your VPN connection. Secure your devices: Ensure that the devices you use to connect to the VPN are free from malware and are regularly updated. Use strong encryption: Verify that your VPN uses strong encryption protocols like AES-256. Beware of free VPNs: Avoid free VPN services, as they often compromise on security and privacy to make money.",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-35",
            "slideNumber": 35,
            "title": "END OF SLIDE",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "VPN Laboratory, Attack Surfaces & Risk Mitigation",
            "lead": "END OF SLIDE",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>END OF SLIDE</h3>",
            "cleanText": "END OF SLIDE",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-36",
            "slideNumber": 36,
            "title": "Advanced Network & System Security - Slide 36",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "VPN Laboratory, Attack Surfaces & Risk Mitigation",
            "lead": "Key conceptual lecture material.",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>Advanced Network &amp; System Security - Slide 36</h3>",
            "cleanText": "Advanced Network & System Security - Slide 36",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-37",
            "slideNumber": 37,
            "title": "How do you install a VPN on your computer?",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "VPN Laboratory, Attack Surfaces & Risk Mitigation",
            "lead": "How do you install a VPN on your computer?",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<h3>How do you install a VPN on your computer?</h3>",
            "cleanText": "How do you install a VPN on your computer?",
            "codeSnippets": [],
            "tables": [],
            "images": []
          },
          {
            "id": "slide-38",
            "slideNumber": 38,
            "title": "How do you install a VPN on your computer?",
            "eyebrow": "CIT 220 • Unit 02",
            "subtitle": "VPN Laboratory, Attack Surfaces & Risk Mitigation",
            "lead": "How do you install a VPN on your computer?",
            "isTitleSlide": false,
            "isSectionDivider": false,
            "rawHtml": "<div class=\"intro-author-card\"><div class=\"institution-badge\"><span>West Visayas State University • CICT Main Campus, Iloilo City</span></div><h2>Thank You!</h2><p class=\"intro-tagline\">CIT 220 Information Assurance and Security 2 • Unit 02 Complete</p><p class=\"mt-4 text-xs text-slate-500 dark:text-slate-400\">Curriculum instruction by Prof. Chin Ann Feliprada • WVSU CICT</p></div>",
            "cleanText": "How do you install a VPN on your computer?",
            "codeSnippets": [],
            "tables": [],
            "images": []
          }
        ]
    }
  ]
};
